### ISSUE TITLE
Builder Skipping swipe-controls

### ISSUE THREAD

**Issue by mohamed-sameer** [reisxd/revanced-builder#100]
**Describe the bug**
The builder does not include swip controls in the created revanced.apk
I tried many times and the output is the same

```
INFO: Skipping swipe-controls: Not explicitly included
```

**revanced-builder Version:**  [2.1.1]

**Comment by shrihanDev** [comment]
Dup #98

**Comment by rickninja765** [comment]
So there are no way to include Swipe patch?
