### ISSUE TITLE
Couldn't download youtube

### ISSUE THREAD

**Issue by mhwd1102** [reisxd/revanced-builder#101]
**Describe the bug**
Error occurs when I try to download YouTube

**To Reproduce**

After selecting all the features

**Screenshots**
![Screenshot_20220728-174433_Termux](https://user-images.githubusercontent.com/89073998/181564734-6c0772bf-77f1-4e08-aaf1-d638f463ef45.jpg)

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**

**Comment by reisxd** [comment]
Read.
