### ISSUE TITLE
Adding disabled patches/features

### ISSUE THREAD

**Issue by SahibzadaAliNoor** [reisxd/revanced-builder#102]
**Describe the bug**
Some features have been disabled by the revanced team such as swipe controls and HDR. These can be added via the -i command while compiling the app manually.

Kindly add the functionality to the rebuilder, if possible.

Message from core revanced team "They are not removed permanently. They are just disabled by default. Include them using -i patchname when building to apply them."

**To Reproduce**
Disabled features give the message "not exclusively included" when building revanced apk via the rebuilder.

**Comment by reisxd** [comment]
I'll change the function to exclude to include the patched that weren't excluded.

**Comment by SahibzadaAliNoor** [comment]
Thank you very very much 🥰🥰🥰
