### ISSUE TITLE
Patch descriptions don't match patch name

### ISSUE THREAD

**Issue by ShlomitoGames** [reisxd/revanced-builder#104]
I was choosing the patches to exclude when I noticed the descriptions didn't match the actual patch, like enable-wide-searchbar saying "integrate sponsorblock". They are offset by one, starting at old-quality-layout.

![image_2022-07-28_121656560](https://user-images.githubusercontent.com/69548875/181598359-02bde64a-f258-461d-b0af-74381d26c473.png)

![image_2022-07-28_121507690](https://user-images.githubusercontent.com/69548875/181598075-3c5ee15f-84b3-4b79-8104-256995fe2637.png)

**Comment by reisxd** [comment]
The fix is implemented, I didn't create an release yet.
