### ISSUE TITLE
App not installed as package conflicts with an existing package

### ISSUE THREAD

**Issue by StephanBruh** [reisxd/revanced-builder#106]
**Describe the bug**
Cannot install reddit & twitter revanced. When trying to install the apk my phone returns ' App not installed as package conflicts with an existing package '. On the discord they are referring to a wrong usage of the cli

**revanced-builder Version:**
2.1.2

**Comment by reisxd** [comment]
Uninstall the app and reinstall the APK.

**Comment by StephanBruh** [comment]
App isn't even installed. Thats the problem
