### ISSUE TITLE
TypeError on Termux

### ISSUE THREAD

**Issue by jakito1** [reisxd/revanced-builder#107]
Hi, I followed the instructions to build on Termux and I'm getting this error right at the beginning. Let me know if you need logs and if yes, where to find them please. Also, if this is a mistake on my part, I apologize and would like to ask if you could guide me to where to read. Thanks!

Error:

```
Downloading required files...
[app-release-unsigned.apk] ✓
[microg.apk] ✓
revanced-builder has detected that you are using Android (Termux)!
JDK is already installed.
Checking for aapt2... aapt2 is already installed.
? Select what app you want to patch: YouTube
An error occured.
TypeError: patchesArray is not iterable
    at /data/data/com.termux/files/home/revanced-builder-cli/index.js:637:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...
```

![Screenshot_20220730-022058__01](https://user-images.githubusercontent.com/23082107/181864919-a6f03bf0-53aa-4127-b185-3f00a1c42378.jpg)

**Comment by naserkesetovic** [comment]
I've got the same issue, with YT and YT music.

**Comment by reisxd** [comment]
I cannot reproduce this on the latest commit.
![IMG_20220730_073213.jpg](https://user-images.githubusercontent.com/29177546/181872496-e3a17b65-3d27-4805-a0be-85eb2b2999c0.jpg)
![IMG_20220730_073257.jpg](https://user-images.githubusercontent.com/29177546/181872499-f1926a61-53fb-4e1c-83f4-88e082eec905.jpg)

**Comment by shrihanDev** [comment]
Try re-downloading the patches:
```bash
$ cd revanced-builder-cli
$ rm -rf revanced revanced-cache
$ pkg up
$ node .
```

**Comment by jakito1** [comment]
Tried that and tried clearing termux data and redoing everything
Exactly what the same results unfortunately

**Comment by shrihanDev** [comment]
@jakito1 @naserkesetovic Can you please apply this patch:

```patch
From c015c7645f0f124df438694de6f2587b9680432e Mon Sep 17 00:00:00 2001
From: shrihanDev <shrihankp198725@gmail.com>
Date: Sun, 31 Jul 2022 00:01:32 +0530
Subject: [PATCH] #107 test

---
 index.js | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/index.js b/index.js
index 3567830..d008052 100644
--- a/index.js
+++ b/index.js
@@ -628,7 +628,7 @@ async function mountReVanced(pkg) {
       const patchRegex = new RegExp('\\t\\s([^\\t]+)', 'g');
 
       const patchesArray = patchesText.match(patchRegex);
-
+      console.log({patchesText, firstWord, patchesArray});
       const pkgRegex = new RegExp(`${firstWord}\\s([^\\t]+)`, 'g');
       const pkgNameArray = patchesText.match(pkgRegex);
       if (pkgNameArray.includes('com.twitter.android')) {
@@ -653,6 +653,7 @@ async function mountReVanced(pkg) {
       }
       const patchDescRegex = new RegExp(`\\t(.*) ${require('os').EOL}`, 'g');
       const patchDescsArray = patchesText.match(patchDescRegex);
+      console.log({patchDescsArray});
 
       const patchesChoice = [];
       let index = -1;
-- 
2.37.1
From c015c7645f0f124df438694de6f2587b9680432e Mon Sep 17 00:00:00 2001
From: shrihanDev <shrihankp198725@gmail.com>
Date: Sun, 31 Jul 2022 00:01:32 +0530
Subject: [PATCH] #107 test

---
 index.js | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/index.js b/index.js
index 3567830..d008052 100644
--- a/index.js
+++ b/index.js
@@ -628,7 +628,7 @@ async function mountReVanced(pkg) {
       const patchRegex = new RegExp('\\t\\s([^\\t]+)', 'g');
 
       const patchesArray = patchesText.match(patchRegex);
-
+      console.log({patchesText, firstWord, patchesArray});
       const pkgRegex = new RegExp(`${firstWord}\\s([^\\t]+)`, 'g');
       const pkgNameArray = patchesText.match(pkgRegex);
       if (pkgNameArray.includes('com.twitter.android')) {
@@ -653,6 +653,7 @@ async function mountReVanced(pkg) {
       }
       const patchDescRegex = new RegExp(`\\t(.*) ${require('os').EOL}`, 'g');
       const patchDescsArray = patchesText.match(patchDescRegex);
+      console.log({patchDescsArray});
 
       const patchesChoice = [];
       let index = -1;
-- 
2.37.1
```

Copy the above code, and run
```bash
$ cd revanced-builder-cli
$ patch -p1 # the cursor will wait here. paste the above code, then press Ctrl+D.
$ node .
```
Upload the log here.

**Comment by jakito1** [comment]
First, I'm getting stuck on "The architecture is arm64" after applying the patch. I've tried waiting 5 minutes and still nothing.

![Screenshot_20220730-194939](https://user-images.githubusercontent.com/23082107/181937557-ff77b7b9-fd45-401c-9015-e422b8e6482f.jpg)
 
Second: where can I find the logs exactly? Or how should I collect them?
I tried looking for them on the termux data folder without success.

![Screenshot_20220730-194732](https://user-images.githubusercontent.com/23082107/181937418-bfcebae4-338a-4491-818a-a4e5fddc6bea.jpg)

**Comment by naserkesetovic** [comment]
Jep, the same "The architecture is arm" and just hangs.

**Comment by shrihanDev** [comment]
Welp, I forgot to mention this: the patch would only work in the newest commit.

Delete the revanced-builder-cli folder and re-download using the commands from the wiki.

**Comment by naserkesetovic** [comment]
No changes as far as I can see. Removed, replaced and everything.

The error persists.
![IMG_20220731_074405](https://user-images.githubusercontent.com/65071690/182012079-10a4aecc-8748-4174-9781-dd94ba564b4d.jpg)

**Comment by naserkesetovic** [comment]
Problem is that the "getPatches.stderr || getPatches.stdout" on returns:

`libc: SetHeapTaggingLevel: tag level set to 0`

This is from the error. The stdout contains info about the patches. This in turn gives that the patchesArray is null.

![Screenshot_2022-07-31-08-41-39-130_com termux](https://user-images.githubusercontent.com/65071690/182013637-d217e4e2-8fe1-4ed5-a652-efffec89a4c2.jpg)

**Comment by shrihanDev** [comment]
I really can't see what's happening:
![Screenshot_2022-07-31-13-06-51-16](https://user-images.githubusercontent.com/54971391/182015294-8a87caca-5eca-47c3-a3e7-e59ff03e02aa.png)
---
@naserkesetovic In the above screenshot, `stderr` is empty. I don't see any interferences of `libc`.

**Comment by naserkesetovic** [comment]
In your case the stderr is empty, but in my case it contains the error:
`libc: SetHeapTaggingLevel: tag level set to 0`

and the stdout contains the list of patches, like in your case.

When running the original code (under my Termux), the patchesText returns only above quoted error, not the patches (not familiar with JS, I presume || only if empty first). This in turn returns empty from regex, which in turn gives that the 
`patchesArray is null`

And you can go through empty array. 

On line 284 of "utils/builder.js" change:
`let patchesText = getPatches.stderr || getPatches.stdout;`
to
`let patchesText = getPatches.stdout;`

**Comment by shrihanDev** [comment]
@naserkesetovic #110
