### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by TeaqariaWTF** [reisxd/revanced-builder#109]
Currently, rooted builds aren't supported on ReVanced Builder
Are you sure you want to build rooted ReVanced
(You'll have to mount/install it yourself.) Yes
? Select the version to download. 17.29.34
Downloading the APK, this'll take some time!
[youtube.apk] ✓
Download complete!
Building ReVanced, please be patient!

Copying ReVanced and MicroG to phones storage...
An error occured.
Error: Command failed: cp revanced/revanced.apk /storage/emulated/0/revanced.apk
cp: cannot stat 'revanced/revanced.apk': No such file or directory

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'cp revanced/revanced.apk /storage/emulated/0/revanced.apk',
  stdout: '',
  stderr: "cp: cannot stat 'revanced/revanced.apk': No such file or directory\n"
}

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...

microG and YouTube music install fine but YouTube app gives this error

**Comment by reisxd** [comment]
Cannot reproduce:
![IMG_20220731_062551.jpg](https://user-images.githubusercontent.com/29177546/182008568-6fac37af-1665-47eb-802d-0e10e0b5432a.jpg)

**Comment by TeaqariaWTF** [comment]
> Cannot reproduce: ![IMG_20220731_062551.jpg](https://user-images.githubusercontent.com/29177546/182008568-6fac37af-1665-47eb-802d-0e10e0b5432a.jpg)

i tried again and i get the same error

**Comment by reisxd** [comment]
Could you try again?

**Comment by TeaqariaWTF** [comment]
the problem still continues

![Uploading Screenshot_20220731-114907_Termux.png…]()

**Comment by TeaqariaWTF** [comment]
the problem still continues


![Screenshot_20220731-114907_Termux](https://user-images.githubusercontent.com/90970076/182018449-7f184b66-1c97-4de8-afe3-533fa23bbf1c.png)

**Comment by TheSingular** [comment]
Try `termux-setup-storage` maybe?

**Comment by reisxd** [comment]
If you have a armv7 (arm32) device, that might be the cause. And I cannot reproduce this issue on my armv7 tablet.

**Comment by TeaqariaWTF** [comment]
> If you have a armv7 (arm32) device, that might be the cause. And I cannot reproduce this issue on my armv7 tablet.

no, i have an arm64v8a android 12 device and i am trying to build builds on that device
