### ISSUE TITLE
Cannot build on BlueStacks, WSA

### ISSUE THREAD

**Issue by Dr-Sauce** [reisxd/revanced-builder#113]
**Describe the bug**

ReVanced Builder cannot find the storage location on BlueStacks and WSA.

**To Reproduce**

1. Use ReVanced Builder on BlueStacks or WSA.
2. See error

**Screenshots**
![Screenshot_2022 08 01_10 30 01 438](https://user-images.githubusercontent.com/82555878/182055715-a627b08a-0808-410a-bc2b-8de83ce802e4.png)

**revanced-builder Version:** [e.g. v1.2.10]
revanced-builder v2.1.2

**Desktop (please complete the following information):**
Windows 11

**Comment by reisxd** [comment]
Because only ARM devices are supported. Which your PC isn't.
