### ISSUE TITLE
Can't not apply all options 

### ISSUE THREAD

**Issue by blueblade747** [reisxd/revanced-builder#114]
![Screenshot_2022-08-01-03-08-55-37](https://user-images.githubusercontent.com/102870336/182059069-52e5ecb3-c8c7-4785-8594-d1250cd2e36a.jpg)

Error: You excluded every single patch... I guess you want to use YouTube?
    at /data/data/com.termux/files/home/revanced-builder-cli/index.js:672:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by reisxd** [comment]
You are excluding patches, not including them.
