### ISSUE TITLE
GUI Builder can't find ADB installed

### ISSUE THREAD

**Issue by levix2015** [reisxd/revanced-builder#115]
I wanted to install ReVanced with root, but I can't get past an error screen on the GUI Builder. It says that I don't have ADB installed even though I have the latest version. I downloaded it from the Android Studio site [https://developer.android.com/studio/releases/platform-tools](url). I also enabled USB debugging on my phone and ran the `.\adb devices` command.

OS: Windows 11 Pro
ADB version: 33.0.2
Android version: 12

**Comment by reisxd** [comment]
You need to add it to PATH.

**Comment by levix2015** [comment]
Thanks, It's working now!
