### ISSUE TITLE
wanting to view shorts on my app

### ISSUE THREAD

**Issue by animelol123** [reisxd/revanced-builder#12]
when i go to build the apk i type in `node . --patch --exclude disable-shorts-button` but after installing the app the shorts feature is still disabled pls help

**Comment by reisxd** [comment]
> when i go to build the apk i type in `node . --patch --exclude disable-shorts-button` but after installing the app the shorts feature is still disabled pls help

Try using the "noob" way (just run `node .`), I might have broke that. It should work with more excluded patches but might have broke that.

**Comment by reisxd** [comment]
Should be fixed with 8aa283ef444ed4be85ae15a58737cde5c28a09e6, closing.
