### ISSUE TITLE
Show which patches require root

### ISSUE THREAD

**Issue by zekiz774** [reisxd/revanced-builder#120]
I always get the error message that my device is not connected and I don't know which patch it is that requires root. This is quite annoying since I have to build it with one more patch at a time to test if it requires root.

Edit: it could be that I just forgot to clear the revanced folder after it build and it's actually just the hide cast button patch that i forgot to incude

**Comment by reisxd** [comment]
It litterally says `( Root required to exclude)` for `microg-support` and `hide-cast-button`.

**Comment by zekiz774** [comment]
I enabled these and it still won't build.

**Comment by zekiz774** [comment]
nvm. I read it the wrong way. I read "select patches to include"
