### ISSUE TITLE
FetchError when excluding patches that require root

### ISSUE THREAD

**Issue by aliantonio** [reisxd/revanced-builder#123]
I'm getting an error when trying to exclude microg support and hide cast button patches. My phone is plugged in with USB debugging enabled and rooted. I get the error message below:

FetchError: request to https://www.apkmirror.comundefined/ failed, reason: getaddrinfo ENOTFOUND www.apkmirror.comundefined
    at ClientRequest.<anonymous> (C:\Users\Anthony\Downloads\revanced-builder-windows\revanced-builder\dist\index.js:2:547862)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**To Reproduce**
1) Select Youtube apk
2) Select microg support and hide cast button patches
3) Try to build

revanced-builder Version: 2.1.2

- OS: Windows 10

**Comment by reisxd** [comment]
Do you have YouTube installed on your phone?

**Comment by reisxd** [comment]
Can you try running `adb shell dumpsys package com.google.android.youtune` and send the output here?

**Comment by aliantonio** [comment]
> Can you try running `adb shell dumpsys package com.google.android.youtube` and send the output here?

[output.txt](https://github.com/reisxd/revanced-builder/files/9242589/output.txt)

**Comment by reisxd** [comment]
Why do you have a very old version?

**Comment by aliantonio** [comment]
The old vanced method of patching with root recommended uninstalling youtube updates, disabling auto-update in the play store, and/or detaching from the play store altogether. I never bothered to update since doing this. I can try updating my youtube version if you think this is the issue?

**Comment by reisxd** [comment]
Yep, it's an issue with the version. That APK version doesn't exists on APKMirror.

**Comment by aliantonio** [comment]
That resolved that issue, thank you! I probably should have checked that before opening this issue, however now I'm getting this message:

INFO: Copying revanced_aligned.apk to revanced.apk 
INFO: Failed to clean up cache directory 
INFO: Installing by mounting 
Permission denied

Is there an additional step I need to do here? If I need to open a separate issue, let me know. Thanks.

**Comment by aliantonio** [comment]
Got it working! Thank you for your help, and for this tool!
