### ISSUE TITLE
Android GUI disabling patches doesn't work

### ISSUE THREAD

**Issue by wedsa5** [reisxd/revanced-builder#125]
**Describe the bug**
When building the YouTube apk using the Android gui run from Termux, if i first "Select All" then deselect "premium-heading" and "custom-branding", the patches are still applied and seen when installing the app.

**To Reproduce**
Install Termux
Follow wiki for building on Android
Go to localhost
Select Youtube
Select all patches
Deselect premium-heading and custom-branding
Continue
Select latest Youtube apk
See that the patching process succeeds in patching the deselected patches
Install apk
See that it has the branding/header I don't want

Note:
It works fine if I use the CLI - only the GUI fails

**Comment by reisxd** [comment]
Known issue, will fix tomorrow.

**Comment by reisxd** [comment]
Fixed.
