### ISSUE TITLE
Root support 

### ISSUE THREAD

**Issue by suhasholla** [reisxd/revanced-builder#129]
How can I enable root support,

I can't see in patch settings for android

**Comment by reisxd** [comment]
Currently, you can't build for root due to a bug but even if the bug didn't exist, mounting is currently not supported. To actually answer your question, don't include the patches that requires root to be excluded.

**Comment by suhasholla** [comment]
There is no way to build root version in android? Mounting we can do on pc

**Comment by reisxd** [comment]
> There is no way to build root version in android? Mounting we can do on pc 

Yes, for now.
