### ISSUE TITLE
Crash when open SponsorBlock settings

### ISSUE THREAD

**Issue by 100doses** [reisxd/revanced-builder#134]
**Describe the bug**

**To Reproduce**

1. Go to 'Profile Pic > Settings'
2. Click on 'SponsorBlock settings'
3. Crash without error

add screenshots to help explain your problem.
Can't screen a crash

revanced-builder Version: 2.1.2

Desktop (please complete the following information): Termux

- OS: Termux
- Version: Android 12

**Additional context**

**Comment by reisxd** [comment]
Try clearing cache/data. If that doesn't work, make an issue at revanced/revanced-patches.
