### ISSUE TITLE
Suggestion: Add 'Finished' or 'Build Again' button after finishing one task

### ISSUE THREAD

**Issue by arshit09** [reisxd/revanced-builder#135]
**To Reproduce**
Steps to reproduce the behaviour:

1. After building the YouTube ReVanced apk, there was no flag or button to show the user that the task is completed. ("INFO: Finished" is there but as this is GUI - some better message should be there)

**Screenshot**
![Screenshot_20220803-124050](https://user-images.githubusercontent.com/31356599/182664414-bcf6ff30-29f5-4939-aaec-4e51c7053a1d.png)

**revanced-builder Version:** [v2.1.2]

**Comment by reisxd** [comment]
Added in v3.
