### ISSUE TITLE
[Windows][Reddit] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space Error

### ISSUE THREAD

**Issue by crestcere** [reisxd/revanced-builder#137]
I can't build reddit apk from windows 11. Got not enough space error (though it uses only 200mb of ram, I got 8gb ram)

> When building ReVanced finishes, please copy these two files and install them:
revanced/revanced.apk
revanced/microg.apk (if you are building YT/YTM)
WARNING: Skipping package group: com.reddit.frontpage.creatorkit_dynamicfeature 
INFO: Only decoding AndroidManifest.xml because resource patching is disabled 
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7e0c0000 
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7e0e0000 
INFO: Reading dex files 
INFO: Merging .\revanced\app-release-unsigned.apk 
WARNING: Skipping timeline-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.twitter.android 
INFO: Skipping general-reddit-ads: Explicitly excluded 
WARNING: Skipping minimized-playback-music: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping tasteBuilder-remover: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping hide-get-premium: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping upgrade-button-remover: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping background-play: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping music-microg-support: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping music-video-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping codecs-unlock: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
INFO: Skipping compact-header: Not explicitly included 
WARNING: Skipping exclusive-audio-playback: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping swipe-controls: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping seekbar-tapping: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping minimized-playback: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping amoled: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping disable-create-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-cast-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping return-youtube-dislike: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-autoplay-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping premium-heading: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping custom-branding: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping disable-fullscreen-panels: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping old-quality-layout: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-shorts-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-watermark: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping sponsorblock: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping enable-wide-searchbar: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping custom-video-buffer: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping always-autorepeat: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping microg-support: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping settings: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping custom-playback-speed: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hdr-auto-brightness: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping remember-video-quality: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
INFO: Skipping enable-debugging: Not explicitly included 
WARNING: Skipping video-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping general-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-infocard-suggestions: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube 
INFO: Writing modified dex files 
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

**Comment by reisxd** [comment]
Not an issue with ReVanced Builder.

**Comment by mindstop** [comment]
Had this same issue, this is because you are using 32 bit JDK. Change it to 64 bit JDK and it will work fine. @crestcere
