### ISSUE TITLE
ReVanced Builder v3, The Cross Platform Update

### ISSUE THREAD

**Issue by reisxd** [reisxd/revanced-builder#139]
I'm going to discontinue CLI and Desktop GUI version of ReVanced Builder, because we're maintaining 3 different codebases and that's not really good. 
But maintaining one codebase and making it work with all of the platforms will make our jobs much more eaiser! Android GUI is actually "cross platform", most of the functions like mounting on PC, ADB check, Java check, etc. isn't implemented yet. I'll implement and release it maybe today 👀.

**Comment by crok** [comment]
FYI: Just saw the update notification about [v3.0.0](https://github.com/reisxd/revanced-builder/releases/tag/v3.0.0) and tried it immediately in Termux on Android - and it's broken:

Last log I see in Termux:
```
inflating: revanced-builder-main/wsEvents/index.js
bash: cd: revanced-builder-android-gui: No such file or directory
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /data/data/com.termux/files/home/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent


npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-08-04T13_01_10_404Z-debug-0.log
node:internal/modules/cjs/loader:936
  throw err;
  ^


Error: Cannot find module '/data/data/com.termux/files/home'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
~ $

```

And the mentioned log is attached
[2022-08-04T13_01_10_404Z-debug-0.log](https://github.com/reisxd/revanced-builder/files/9259896/2022-08-04T13_01_10_404Z-debug-0.log)
Last few lines are:
```
59 verbose stack Error: ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
60 verbose cwd /data/data/com.termux/files/home
61 verbose Linux 4.14.180-perf-g87c951f8a94a
62 verbose node v16.15.1
63 verbose npm  v8.11.0
64 error code ENOENT
65 error syscall open
66 error path /data/data/com.termux/files/home/package.json
67 error errno -2
68 error enoent ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
69 error enoent This is related to npm not being able to find a file.
69 error enoent
70 verbose exit -2
71 timing npm Completed in 308ms
72 verbose code -2
73 error A complete log of this run can be found in:
73 error     /data/data/com.termux/files/home/.npm/_logs/2022-08-04T13_01_10_404Z-debug-0.log

```

**Comment by reisxd** [comment]
You aren't changing directories, use `cd revanced-builder-main`

**Comment by crok** [comment]
> You aren't changing directories, use `cd revanced-builder-main`

My bad, indeed - I had a saved copy of the steps from [the Wiki](https://github.com/reisxd/revanced-builder/wiki/How-to-use-revanced-builder-on-Android) but it's been updated, too (: Thanks!

**Comment by ArjixWasTaken** [comment]
windows build does nothing, unless i am supposed to know the actual path for the web app
![image](https://user-images.githubusercontent.com/53124886/182862467-9ea9e1e4-4f8d-4ee4-ab55-9218f58cda66.png)

**Comment by reisxd** [comment]
> windows build does nothing, unless i am supposed to know the actual path for the web app ![image](https://user-images.githubusercontent.com/53124886/182862467-9ea9e1e4-4f8d-4ee4-ab55-9218f58cda66.png)

Hi, I'm trying to fix this issue, sorry!

**Comment by aliantonio** [comment]
Tried building both youtube and youtube music with root and there are no apk versions to select from.

![image](https://user-images.githubusercontent.com/24923847/182867224-e6819d02-8fca-4309-a9f5-eb77c451649d.png)

**Comment by reisxd** [comment]
> Tried building both youtube and youtube music with root and there are no apk versions to select from.
> 
> ![image](https://user-images.githubusercontent.com/24923847/182867224-e6819d02-8fca-4309-a9f5-eb77c451649d.png)

Do you have your device plugged in?

**Comment by aliantonio** [comment]
Yes I do

**Comment by reisxd** [comment]
> Yes I do

Open up DevTools by doing `CTRL + SHIFT + I`, do `CTRL + R`, go to the `Network` tab and look at the websocket requests.

**Comment by aliantonio** [comment]
> > Yes I do
> 
> Open up DevTools by doing `CTRL + SHIFT + I`, do `CTRL + R`, go to the `Network` tab and look at the websocket requests.

![image](https://user-images.githubusercontent.com/24923847/182869469-636efaba-bcf3-4d5d-bf90-0b1677138ca2.png)

**Comment by reisxd** [comment]
> > > Yes I do
> > 
> > 
> > Open up DevTools by doing `CTRL + SHIFT + I`, do `CTRL + R`, go to the `Network` tab and look at the websocket requests.
> 
> ![image](https://user-images.githubusercontent.com/24923847/182869469-636efaba-bcf3-4d5d-bf90-0b1677138ca2.png)

I see why, gonna make a new version!

**Comment by reisxd** [comment]
@aliantonio Can you try the new release?

**Comment by reisxd** [comment]
> Hmm, I see more resources being loaded in the network monitor but same issue..
> 
> ![image](https://user-images.githubusercontent.com/24923847/182872023-c4a8fb56-e41b-4a40-8b54-a50f9df428bc.png)

Hmm, you probably can continue though, if not, go to `http://localhost:8080/patch` manually.

**Comment by reisxd** [comment]
Also, looks like my stupidity took over my brain today... Creating a new release.

**Comment by aliantonio** [comment]
When I hit continue, I get a popup saying I didn't select an apk version, which makes sense. When I go to /patch manually, it does proceed with the build and the patches I included.

It's been stuck on "writing modified dex files" for a little over 10 minutes. 
![image](https://user-images.githubusercontent.com/24923847/182875032-2a375e38-be08-4c98-9d03-841dd9883bb7.png)


I took a look at my phone and Youtube was open on my phone, seemingly with all the patches (not sure if it's the new build or an old one I did yesterday using your tool). I also keep getting superuser toasts saying "Shell was granted superuser rights" so it is trying to build with root it seems

**Comment by reisxd** [comment]
> When I hit continue, I get a popup saying I didn't select an apk version, which makes sense. When I go to /patch manually, it does proceed with the build and the patches I included.
> 
> It's been stuck on "writing modified dex files" for a little over 10 minutes. ![image](https://user-images.githubusercontent.com/24923847/182875032-2a375e38-be08-4c98-9d03-841dd9883bb7.png)
> 
> I took a look at my phone and Youtube was open on my phone, seemingly with all the patches (not sure if it's the new build or an old one I did yesterday using your tool). I also keep getting superuser toasts saying "Shell was granted superuser rights" so it is trying to build with root it seems

Then I really can't help you since this tool uses ReVanced CLI and probably somethings going wrong in the behind, join the ReVanced [Discord](https://discord.gg/revanced) and make a support thread.

**Comment by aliantonio** [comment]
No worries, thanks!

**Comment by ifelixculpa** [comment]
> > When I hit continue, I get a popup saying I didn't select an apk version, which makes sense. When I go to /patch manually, it does proceed with the build and the patches I included.
> > It's been stuck on "writing modified dex files" for a little over 10 minutes. ![image](https://user-images.githubusercontent.com/24923847/182875032-2a375e38-be08-4c98-9d03-841dd9883bb7.png)
> > I took a look at my phone and Youtube was open on my phone, seemingly with all the patches (not sure if it's the new build or an old one I did yesterday using your tool). I also keep getting superuser toasts saying "Shell was granted superuser rights" so it is trying to build with root it seems
> 
> Then I really can't help you since this tool uses ReVanced CLI and probably somethings going wrong in the behind, join the ReVanced [Discord](https://discord.gg/revanced) and make a support thread.

hi sir this is not issue but a question i build sucessfully on windows where does the buiuld revanced apk file goes or saves itself

**Comment by reisxd** [comment]
In the revanced folder, thanks for reminding me to add that message!

**Comment by reisxd** [comment]
> how do i get revanced builder 3 to recognise or set where i have adb because it says i don;t have it

Can you run adb in CMD? If not, add it to PATH. If yes, try restarting ReVanced Builder/Your PC.

**Comment by reisxd** [comment]
> how do i get revanced builder 3 to recognise or set where i have adb because it says i don;t have it

Can you run adb in CMD? If not, add it to PATH. If yes, try restarting ReVanced Builder/Your PC.

**Comment by ifelixculpa** [comment]
> > how do i get revanced builder 3 to recognise or set where i have adb because it says i don;t have it
> 
> Can you run adb in CMD? If not, add it to PATH. If yes, try restarting ReVanced Builder/Your PC.

ran and work flawlessly , thanks sir :)

**Comment by keatit71** [comment]
> > how do i get revanced builder 3 to recognise or set where i have adb because it says i don;t have it
> 
> Can you run adb in CMD? If not, add it to PATH. If yes, try restarting ReVanced Builder/Your PC.

i added it to path and even restarted my pc even though it was working in windows terminal and its still not working in revanced builder 3 even though without path being added for adb revanced builder 2 was working fine.

**Comment by rufusin** [comment]
![asas](https://user-images.githubusercontent.com/10528442/182926312-6c40270d-8595-4e06-9432-bbc9d21d85ca.jpg)
How to solve a problem?

**Comment by shrihanDev** [comment]
@reisxd I guess this one could be closed?

**Comment by reisxd** [comment]
> @reisxd I guess this one could be closed?

Yep, now that I think theres nothing to implement now (theres prob but eh)
