### ISSUE TITLE
Mirror title issue

### ISSUE THREAD

**Issue by WatermelonOof** [reisxd/revanced-builder#140]
**Describe the bug**
Just a typo on the title in android-gui. Referring to the screenshot it should be "Select patches to **exclude**"

**Screenshots**
![Screenshot_20220804-174259__01](https://user-images.githubusercontent.com/68735408/182817209-404a73e9-9d39-404c-91b9-a5b870c98a05.jpg)

**revanced-builder Version:** v2.1.3 android-gui branch

**Desktop (please complete the following information):**

- OS: Android
- Version: 11

**Additional context**
N/A

**Comment by reisxd** [comment]
That's not an typo, you include patches, not exclude them anymore.

**Comment by WatermelonOof** [comment]
I see, because what I did was "not selecting anything" but instead it included everything. It's quite misleading but I guess that's an expected behaviour from revanced-cli? And no one will choose not to include anything either so I assume this is not an issue.
