### ISSUE TITLE
Explicitly ask for rooted/not-rooted setup.

### ISSUE THREAD

**Issue by Rtizer-9** [reisxd/revanced-builder#141]
**Describe the bug**
Since this an automation of the main project it's also plagued by same errors so it would nice to ask user which setup -rooted/non-root they want to use. Right now the rooted users ends up installing non-rooted version.

**To Reproduce**

1. Run the script with requirements satisfied for root version and you'll end up installing non root version. Also the script downloads microg in all cases which isn't needed in root version.
2. The solution is to disable the microg integration while selecting modules to unselect while patching.
3. A better solution is to ask a user explicitly which version they want to install and then disable the microg setup all together if user is installing rooted version.

**Comment by reisxd** [comment]
Not including microg-support will trigger for building rooted ReVanced, which also says that it requires root to be excluded and also the patch descriptions exists. A non rooted user won't be able to see features that requires root to be excluded.

**Comment by Rtizer-9** [comment]
What I simply meant is that it would be nice if like those version and app option gui ask before, it also asks for root/non-root and disable that microg automatically without user needing to find out what needs to be done.

In the official revanced-cli instructions the -e microg flag is specifically mentioned for rooted cases so it's a just a matter of adding that command.

I was confused at first why microg is getting installed again and again unlike the official revanced-cli script thus the issue.

Thanks.
