### ISSUE TITLE
There's no way to select youtube version

### ISSUE THREAD

**Issue by Caticer** [reisxd/revanced-builder#145]
**Describe the bug**
Theres no way to select youtube version

**To Reproduce**

1. Go to 'versions'
2. Click on 'contiune'
`You didn't select an app version!`

**Screenshots**
![image](https://user-images.githubusercontent.com/25691875/182936265-04d3cc38-b4e7-4ac7-a4d8-183596ed4280.png)

**revanced-builder Version:** 3.0.2

- OS: FEdora 36 (Silverblue)

**Comment by reisxd** [comment]
This was fixed in the latest commits, I'll make a new release when i fix some other stuff tomorrow.
