### ISSUE TITLE
Cant build a file with working patches 

### ISSUE THREAD

**Issue by 22350** [reisxd/revanced-builder#146]
**Describe the bug**
I run the new version with Twitter or YouTube. Everything appears to work. Install the apk and none of the patches work 

**revanced-builder Version:** [e.g. v1.2.10]
3.0

**Desktop (please complete the following information):**

- windows 10
- 
- *Additional context**
If I run RV.Apk.Patcher it builds YouTube fine and everything works

**Comment by reisxd** [comment]
Send the build log here.

**Comment by 22350** [comment]
where is the build log located?

**Comment by reisxd** [comment]
Rebuild ReVanced with selected patches and when patching finishes, send the log.

**Comment by 22350** [comment]
![2022-08-04 22_10_59-Patching](https://user-images.githubusercontent.com/2864726/183005964-c662cc2b-81bb-4c6d-a445-40ab617656ca.png)

**Comment by reisxd** [comment]
I don't see any issues, it has built successfully with the patches.

**Comment by 22350** [comment]
trying to install again.  maybe i grabbed the wrong file out of the revanced folder

**Comment by 22350** [comment]
yep, i am an idiot
thanks for helping
