### ISSUE TITLE
Cast

### ISSUE THREAD

**Issue by sac23** [reisxd/revanced-builder#147]
Hello i don't know if anyone has posted this sorry if anyone did already but the cast button doesn't see anything google chrome cast anyone having issues like this thanks

**Comment by reisxd** [comment]
Are you using rooted ReVanced or not?

**Comment by sac23** [comment]
yes rooted and i tried without root same i enabled the cast button but doesn't see anything via chrome cast

**Comment by reisxd** [comment]
> yes rooted and i tried without root same i enabled the cast button but doesn't see anything via chrome cast

Have you excluded microg-support and hide-cast-button? And do you have MicroG instead of GMS?

**Comment by sac23** [comment]
i have both micro G and GMS

**Comment by sac23** [comment]
i have also included micro G support

**Comment by reisxd** [comment]
> i have also included micro G support thank u very much for the replies back much appreciated
> 
> 

Casting v2 only gets enabled when you have GMS and not MicroG (not to be mistaken with Vanced MicroG) and also when you exclude `microg-support` and `hide-cast-button`. If it still isn't showing up after disabling those patches, try connecting to your device with code.

**Comment by sac23** [comment]
ok thank u will try that

**Comment by sac23** [comment]
have u ever had a issue reinstalling the app that says update the existing app but i uninstalled it already?

**Comment by reisxd** [comment]
> have u ever had a issue reinstalling the app that says update the existing app but i uninstalled it already?

Try restarting your phone.

**Comment by sac23** [comment]
tryed that is says install now but then it says conflicts with existing package

**Comment by reisxd** [comment]
> tryed that is says install now but then it says conflicts with existing package
> 

Weird, because that shouldn't happen, unless you built rooted ReVanced and somehow failed to install it, then transfer the revanced.apk to your device and try to install it.

**Comment by sac23** [comment]
yea its weird ill try again now thanks bro

**Comment by sac23** [comment]
so i got it installed the cast button shows but it says connect only with pin

**Comment by reisxd** [comment]
> so i got it installed the cast button shows but it says connect only with pin

Oh well, I don't know this and I can't test this. Closing.
