### ISSUE TITLE
Revanced Builder crashes on Youtube Version

### ISSUE THREAD

**Issue by chiefjazzdiewltr** [reisxd/revanced-builder#148]
As per the title the the revanced builder web server crashes when I get to the selecting the YouTube version screen,
![Screenshot_1](https://user-images.githubusercontent.com/16767027/183006610-f2d5cc86-f01e-4163-bd74-a30083cbe419.png)
and also here is the pastebin link for what the console output says: https://pastebin.com/pM7Au9D0

**Comment by reisxd** [comment]
Do you have YouTube installed on your device? If so, what version is it?

**Comment by chiefjazzdiewltr** [comment]
I do it's version 17.31.33, do I need to downgrade it?

**Comment by reisxd** [comment]
Yep, that version doesn't exists on APKMirror, causing the scraper to fail. Also, after downloading the APK, go to /patch manually because of a bug. It's fixed but not in a release yet.

**Comment by chiefjazzdiewltr** [comment]
Ah okay, that worked thanks.
