### ISSUE TITLE
The package is not installed (Conflicts).

### ISSUE THREAD

**Issue by DrimTim2020** [reisxd/revanced-builder#149]
After a successful assembly, I threw the package on the phone and decided to install it, but the package began to conflict.
I started to understand, and found out that the signature of the package is com.google.android.youtube .

**Comment by reisxd** [comment]
Did you exclude microg-support while building on your PC? Because this shouldn't be possible.

On PC, it tries to mount ReVanced on to your device and checks if you have your device plugged in. On Android, it tries to mount it and also check if your device has root.

**Comment by DrimTim2020** [comment]
> Did you exclude microg-support while building on your PC? Because this shouldn't be possible.
> 
> On PC, it tries to mount ReVanced on to your device and checks if you have your device plugged in. On Android, it tries to mount it and also check if your device has root.

Я создавал пакет без подключенного устройства , и root у меня нет !
Создавал пакет без root функций .
Но ошибок куча .
amoled
hide-autoplay-button
custom-branding
disable-fullscreen-panels
always-autorepeat

**Comment by DrimTim2020** [comment]
> Did you exclude microg-support while building on your PC? Because this shouldn't be possible.
> 
> On PC, it tries to mount ReVanced on to your device and checks if you have your device plugged in. On Android, it tries to mount it and also check if your device has root.

I created the package without a connected device and I don't have root!
Created a package without root functions.
Here is the list that I have chosen.
amoled
hide-autoplay-button
custom-branding
disable-fullscreen-panels
always-autorepeat
custom-playback-speed
hdr-auto-brightness

**Comment by reisxd** [comment]
The tool has changed, it no longer excludes patches but include them, press "Select all Patches" and then don't select the ones you don't want.

**Comment by DrimTim2020** [comment]
> The tool has changed, it no longer excludes patches but include them, press "Select all Patches" and then don't select the ones you don't want.
OK, I'll try to do as you say.

**Comment by DrimTim2020** [comment]
Again , I put together a package and what awaited me .
You broke everything - the descriptions do not carry any clear description of what will happen when I select the item, or leave it by default. ((

**Comment by reisxd** [comment]
Nothing is wrong, nothing broken, it does give you a clear description of what does the patch does.

**Comment by baiorett** [comment]
skill issue
