### ISSUE TITLE
Error - Rooted Device: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by Milor123** [reisxd/revanced-builder#15]
Hi dears, I am trying to install ReVanced Using the Root Variant without external MicroG because i have native MicroG

The first time compile and install nice without `--manual-apk`, then I try recompile and install **(then i've uninstalled YouTube APK from my phone _[I think that surely the bug is by this reason]_)** using now `--manual-apk` but it shows this error:

![image](https://user-images.githubusercontent.com/14153649/177041118-53b38bb6-794a-4c37-8c7a-49227a82f5f8.png)

And now when try to install without  `--manual-apk` also show the same bug.

EDIT PART 2: I've found a temporal solution for the bug, basically I understand that the error "null reading 1" occurs because the algorithm try to check the YouTube.apk from ADB in my phone (the which should be not happened, because I've specified `--manual-apk`), I don't know how works your algorithm neither understand about of NodeJS, but I supposed that is it.

![image](https://user-images.githubusercontent.com/14153649/177041588-110ab6b1-4afd-4ccb-a7c3-fd79f197aaec.png)

Thank u very much for your project !!!

**Comment by reisxd** [comment]
If revanced-builder cannot find YouTube, it cannot get the version that it needs to download. You need YouTube installed for rooted installs.

**Comment by shrihanDev** [comment]
@reisxd Yes, the YouTube APK should be installed with the SAME version as on the device, however, the error should be a bit more useful, i.e. this error should be handled.

**Comment by reisxd** [comment]
> @reisxd Yes, the YouTube APK should be installed with the SAME version as on the device, however, the error should be a bit more useful, i.e. this error should be handled.

Sure, ill try handling it!

**Comment by reisxd** [comment]
Added in a9c94599d2f26ec5af1ca02df79d9a036751e6f4.
