### ISSUE TITLE
An explanation about the program items to be selected (this is important).

### ISSUE THREAD

**Issue by DrimTim2020** [reisxd/revanced-builder#150]
All points of the program should bear the general character of only the choice of a point for its further application.
And not as in the program (each time the program changes, the randomness of the items and their choice changes).
And I don't know what will happen if I skip this item or select it.
To do this, I need to sit all day and understand the program, how it works and what to choose and what not to!
Please do it first!!!

**Comment by baiorett** [comment]
ok and? cope ratio skill issue malding balding contribute and make a pull request

**Comment by DrimTim2020** [comment]
> ok and? cope ratio skill issue malding balding contribute and make a pull request
What did you write  ?

**Comment by baiorett** [comment]
> What did you write ?

that you not gotta brag and appreciate what people do or contribute to the project yourself

**Comment by shrihanDev** [comment]
Don't care
\+ didn't ask
\+ L
\+ Ratio

**Comment by baiorett** [comment]
> Don't care + didn't ask + L + Ratio

male detected, opinion tolerated
![tolerated](https://c.tenor.com/dzoYWrZ74ygAAAAd/mgrr-metal-gear-rising-revengeance-armstrong-raiden-handshake.gif)
