### ISSUE TITLE
Root build failed

### ISSUE THREAD

**Issue by Esme-Southers** [reisxd/revanced-builder#151]
**Describe the bug**
The meta-data tag value is wrong, expected 222812000 but found 222980000

**Screenshots**
![FireShot Capture 003 - Patching - localhost](https://user-images.githubusercontent.com/49909340/183044590-ab0494be-c04f-4370-a5ba-09711581e124.png)

**revanced-builder Version:** 
3.0.3 latest

**Desktop (please complete the following information):**
Winodws 11

**Comment by reisxd** [comment]
Try the latest release.

**Comment by Esme-Southers** [comment]
> Try the latest release.

Just tried, same error

**Comment by shrihanDev** [comment]
Check if YouTube ReVanced opened on your phone? And, try rebuilding?

**Comment by Esme-Southers** [comment]
> Check if YouTube ReVanced opened on your phone? And, try rebuilding?

Already tried, not working.

**Comment by ifelixculpa** [comment]
i am also facing same error with latest 

![image](https://user-images.githubusercontent.com/13099434/183074752-4e342910-7b12-41a5-ac66-208307f64356.png)

**Comment by reisxd** [comment]
> i am also facing same error with latest 
> 
> ![image](https://user-images.githubusercontent.com/13099434/183074752-4e342910-7b12-41a5-ac66-208307f64356.png)
> 

Uninstall the current ReVanced you have on your device and rebuild.

**Comment by ifelixculpa** [comment]
> > i am also facing same error with latest
> > ![image](https://user-images.githubusercontent.com/13099434/183074752-4e342910-7b12-41a5-ac66-208307f64356.png)
> 
> Uninstall the current ReVanced you have on your device and rebuild.

do keeping device attached is mandatory ? worked now

**Comment by reisxd** [comment]
> > > i am also facing same error with latest
> > > ![image](https://user-images.githubusercontent.com/13099434/183074752-4e342910-7b12-41a5-ac66-208307f64356.png)
> > 
> > Uninstall the current ReVanced you have on your device and rebuild.
> 
> do keeping device attached is mandatory ? worked now

Nope

**Comment by ifelixculpa** [comment]
> > > > i am also facing same error with latest
> > > > ![image](https://user-images.githubusercontent.com/13099434/183074752-4e342910-7b12-41a5-ac66-208307f64356.png)
> > > 
> > > 
> > > Uninstall the current ReVanced you have on your device and rebuild.
> > 
> > 
> > do keeping device attached is mandatory ? worked now
> 
> Nope

thanks sir :)

**Comment by Esme-Southers** [comment]
![图片](https://user-images.githubusercontent.com/49909340/183092189-9c004171-4524-4866-9b21-2c1cc107bada.png)
Try deselect enable debugging, now this error comes out.

**Comment by reisxd** [comment]
> ![图片](https://user-images.githubusercontent.com/49909340/183092189-9c004171-4524-4866-9b21-2c1cc107bada.png)
> Try deselect enable debugging, now this error comes out.

It should be mounted. If not, try restarting your device.

**Comment by Esme-Southers** [comment]
A simple reboot will do, issue closed.
