### ISSUE TITLE
[Suggestion]: App versioning with patches

### ISSUE THREAD

**Issue by PalmDevs** [reisxd/revanced-builder#154]
Builder should have something telling the user that a specific patch is available only in certain versions of the package. But it should also have support for building beta/unsupported versions of apps.

By adding `--experimental` in the patch command, this will make patches available to unsupported versions of the app. Patches may work or not work in this case.

There should be a checkbox to enable unsupported versions but it should be disabled by default.

About the package version selector, this should also include beta versions of a specific app instead of just stable versions. This again, should have a checkbox to show and hide these entries.

**Comment by reisxd** [comment]
This might be a good idea but I've never seen a patch being broken yet and also even if the actual patch works, ReVanced Team/Contributors has to update the supported version list for the patch. This suggestion might also confuse most of the users.

**Comment by PalmDevs** [comment]
Patch being broken will result in the CLI printing `SERVERE: ...`, but sometimes even if the patches succeeded, it would just be unusable on unsupported versions. So a just a warning modal should be fine for me.
