### ISSUE TITLE
Revanced builder 3 cant detect adb

### ISSUE THREAD

**Issue by keatit71** [reisxd/revanced-builder#155]
**Describe the bug**
i added it to path and even restarted my pc even though it was working in windows terminal and its still not working in revanced builder 3 even though without path being added for adb revanced builder 2 was working fine.

**To Reproduce**
1. Open revanced builder 3
2. Patch youtube app
3. Click cpntinue until it gives adb missing error

**revanced-builder Version:** 
3

**Desktop (please complete the following information):**
Windows  #11

**Comment by reisxd** [comment]
Do you have your device plugged in? If so, can you send the log of `adb devices`?

**Comment by keatit71** [comment]
What do i need my device plugged in for im just trying to build the app.

**Comment by reisxd** [comment]
> What do i need my device plugged in for im just trying to build the app.

Excluding the MicroG Support patch requires root, and if you are trying to build for non root, include the patch.

**Comment by keatit71** [comment]
I realised the problem was that before it was select patches to exclude and now its include so i just didnt read it.

**Comment by reisxd** [comment]
Closing the issue then.
