### ISSUE TITLE
Builder installs microg.apk but doesn't do anything with it

### ISSUE THREAD

**Issue by SafariKnight** [reisxd/revanced-builder#157]
I was using this to install youtube revanced on my device, I had just recently formatted it so I didn't have microg installed, The builder downloaded the apk but it didn't really do anything with it, It didn't install it or remove it after, So when I tried to open youtube revanced it just instantly kicked me out, the solution was going into the install files and running `adb install microg.apk`

**Comment by reisxd** [comment]
Will add back the functionality back in v3.1.0.
