### ISSUE TITLE
Improve UX for selecting patches

### ISSUE THREAD

**Issue by rabilrbl** [reisxd/revanced-builder#159]
The UI seems a bit confusing with those drop-down icon. 
![image](https://user-images.githubusercontent.com/63334479/183237565-0dc76971-cb4a-4500-9ae9-5702d3928b4d.png)

Make a checkbox to select patches.

**Comment by Elijah629** [comment]
I see, the dropdowns were originally meant to store more information when you clicked on them ( The entire option would expand to store extra information, ( ex. a paragraph description ) )

**Comment by rabilrbl** [comment]
Oh.

**Comment by Elijah629** [comment]
I figured out a way to do it though. It should be pretty simple for the user to understand

**Comment by rabilrbl** [comment]
I see.

Even after having a description of patches, I believe UX is still poor
The only way to identify whether a patch Is selected is only through color.

**Comment by Elijah629** [comment]
Ok, thanks for the feedback. I will try to redesign the entire UI to be more user-friendly.

**Comment by rabilrbl** [comment]
How about placing the checkbox on the left and the dropdown icon on the right?

**Comment by Elijah629** [comment]
The way I have the CSS set up, you can't actually... It relies on an invisible checkbox that is nowhere near alignment with the label ( Visual item you are selecting for the patch ) And I removed the dropdown icon as the only way for it to work is for it to be on the left and for the title of the patch to be inside of it, no other way

**Comment by Elijah629** [comment]
So what I'm doing is removing those entirely, and as `select` normally means click or interact with the user would just click anywhere on the patch to select it, the dropdown would've been removed

**Comment by rabilrbl** [comment]
Plain CSS is often very hard to maintain. 
How about introducing component library like `Material UI` or `Mantine UI` ?
This will ease the UI process for the future as this project evolves, with built in components.

**Comment by Elijah629** [comment]
My 2nd goal for the UI is for it to be as small as possible, and as fast and slick as possible, If you look at the fontawesome.css I have literally stripped it down to 3% of its original size

**Comment by Elijah629** [comment]
Ok, I updated the patches, its fixed now
