### ISSUE TITLE
Error - TypeError: assets is not iterable 

### ISSUE THREAD

**Issue by Milor123** [reisxd/revanced-builder#16]
It error occurs after of reinstall youtube.apk (original apk) on my phone and try build and install ReVanced (after of **`EDIT PART2`** in my post #15 )

![image](https://user-images.githubusercontent.com/14153649/177042114-840c78f5-ad38-48a2-9eec-5f710ab77ab4.png)

**Comment by reisxd** [comment]
> It error occurs after of reinstall youtube.apk (original apk) on my phone and try build and install ReVanced (after of **`EDIT PART2`** in my post #15 )
> 
> ![image](https://user-images.githubusercontent.com/14153649/177042114-840c78f5-ad38-48a2-9eec-5f710ab77ab4.png)

You got ratelimited.
