### ISSUE TITLE
[Feature Request] Select architecture type (armeabi-v7a, arm64-v8a, x86, x86_64)

### ISSUE THREAD

**Issue by vasile-coste** [reisxd/revanced-builder#162]
This is not a bug, but a feature request.

It would be nice to have a screen after the version selector to choose between which type of architecture you want to patch: 
- armeabi-v7a
- arm64-v8a
- x86
- x86_64

I didn't know this at first and just patched a random one that was downloaded for me. The patched app was installed successfully on 2 of 3.

Thank you!

**Comment by reisxd** [comment]
Split APKs aren't supported yet, meaning that It's currently impossible for me to add this feature and Builder already downloads the universal APK from APKMirror.

**Comment by reisxd** [comment]
This feature was added for YTM but only the options are armv7 and arm64 (Emulators won't be supported).

**Comment by vasile-coste** [comment]
Sounds great, thank you for adding this feature!😁
