### ISSUE TITLE
aapt2.zip download and extract failed on OnePlus 8T

### ISSUE THREAD

**Issue by flightifyy** [reisxd/revanced-builder#165]
**Describe the bug**
Can't get over downloading aapt2.zip

**To Reproduce**
Follow all commands
Open webbrowser
Select app (YouTube) (on OnePlus 8T)
Everything is downloaded except aapt2.zip

**Screenshots**
Browser:
![Screenshot_20220806-110755__01__01](https://user-images.githubusercontent.com/79730692/183242734-c5e60364-cabf-44a5-98e8-4df4a505ebbd.jpg)
Console:
![Screenshot_20220806-110812__01](https://user-images.githubusercontent.com/79730692/183242753-dbbfe10e-1bb3-4d52-893f-adff22f93f89.jpg)

**revanced-builder Version:** [e.g. v1.2.10]
main.zip (3.0.4)

**Comment by reisxd** [comment]
@shrihanDev :moyai:

**Comment by shrihanDev** [comment]
FUUUUUUUUUUUUUUUUUUU-

```bash
$ unzip --help
Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
..........
-d extract files into exdir
```
---
```patch
diff --git a/utils/checkJDKandAapt2.js b/utils/checkJDKandAapt2.js
index c5ee8ac..5e2024c 100644
--- a/utils/checkJDKandAapt2.js
+++ b/utils/checkJDKandAapt2.js
@@ -26,7 +26,7 @@ module.exports = async function (ws) {
       'revanced/aapt2.zip',
       ws
     );
-    await actualExec('unzip revanced/aapt2.zip');
+    await actualExec('unzip revanced/aapt2.zip -d revanced');
     switch (os.arch()) {
       case 'arm64': {
         await actualExec('cp revanced/arm64-v8a/aapt2 revanced/aapt2');
```

**Comment by reisxd** [comment]
> FUUUUUUUUUUUUUUUUUUU-
> 
> ```bash
> $ unzip --help
> Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
> ..........
> -d extract files into exdir
> ```
> ---
> ```patch
> diff --git a/utils/checkJDKandAapt2.js b/utils/checkJDKandAapt2.js
> index c5ee8ac..5e2024c 100644
> --- a/utils/checkJDKandAapt2.js
> +++ b/utils/checkJDKandAapt2.js
> @@ -26,7 +26,7 @@ module.exports = async function (ws) {
>        'revanced/aapt2.zip',
>        ws
>      );
> -    await actualExec('unzip revanced/aapt2.zip');
> +    await actualExec('unzip revanced/aapt2.zip -d revanced');
>      switch (os.arch()) {
>        case 'arm64': {
>          await actualExec('cp revanced/arm64-v8a/aapt2 revanced/aapt2');
> ```

I already made a "fix" :troll:

**Comment by shrihanDev** [comment]
:trollface: Indeed

**Comment by flightifyy** [comment]
All fine! Did it on windows without problems. :)
