### ISSUE TITLE
OpenJDK compatibility

### ISSUE THREAD

**Issue by d-l-n** [reisxd/revanced-builder#166]
Please make it compatible with more jdk builds. I've tried with microsoft, oracle, red hat and other ones and it's still not working. Previous revanced-builder version works fine with them
![image](https://user-images.githubusercontent.com/56566724/183250859-55e37bb5-027f-4453-aa73-0a34083801b7.png)

**Comment by shrihanDev** [comment]
It depends on the upstream CLI itself. OpenJDK and Zulu is considered to have the best support for patching; others? Maybe, maybe not.

**Comment by reisxd** [comment]
It checks if there's `openjdk` inside the `java -version` command, which what distro you're using doesn't have. The code for that remains nearly unchanged from v1.x.x (basically when it got added).
