### ISSUE TITLE
An error occured.Error: Command failed: su -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'mount: bad /etc/fstab: No such file or directory    at ChildProcess.exithandler (node:child_process:398:12)    at ChildProcess.emit (node:events:527:28)    at maybeClose (node:internal/child_process:1092:16)    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

### ISSUE THREAD

**Issue by hacker2285629** [reisxd/revanced-builder#169]
**Describe the bug**

An error occured.
Error: Command failed: su -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'
mount: bad /etc/fstab: No such file or directory

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Please help

**Comment by reisxd** [comment]
Give root access to Termux.

**Comment by hacker2285629** [comment]
Root was provided for termux

**Comment by hacker2285629** [comment]
> Предоставьте root-доступ к Termux.
Root was provided for termux

**Comment by hacker2285629** [comment]
> Предоставьте root-доступ к Termux.

So what to do?

**Comment by hacker2285629** [comment]
![Uploading Screenshot_20220806-190210_Edge.png…]()

**Comment by hacker2285629** [comment]
![Screenshot_20220806-190218_Edge](https://user-images.githubusercontent.com/72620519/183256842-0b861867-da1b-4dca-b261-e8daa7a84a3f.png)
![Screenshot_20220806-190222_Edge](https://user-images.githubusercontent.com/72620519/183256846-973d7814-4477-4dea-b0ef-18adb53ecad3.png)

**Comment by hacker2285629** [comment]
![Uploading Screenshot_20220806-190210_Edge.png…]()

**Comment by hacker2285629** [comment]
![Screenshot_20220806-190210_Edge](https://user-images.githubusercontent.com/72620519/183256886-bfccb388-b897-4918-8f42-f56b223bab0e.png)

**Comment by hacker2285629** [comment]
![Screenshot_20220806-190222_Edge](https://user-images.githubusercontent.com/72620519/183256906-49480f78-0ca1-40ce-82c8-890f25174d36.png)

**Comment by hacker2285629** [comment]
![Screenshot_20220806-190218_Edge](https://user-images.githubusercontent.com/72620519/183256913-5e232d0c-6d72-4f81-aa36-0dc5c6998c89.png)

**Comment by hacker2285629** [comment]
Well shit...

**Comment by reisxd** [comment]
Those aren't errors. And the actual issue happens when you don't give root access to Termux properly.
