### ISSUE TITLE
[Suggestion] Deploy the app as a Website

### ISSUE THREAD

**Issue by shrihanDev** [reisxd/revanced-builder#177]
**Describe the suggestion**
Since #161, it's possible to download the app from the UI itself; there's no need to manually get `<builder>/revanced/revanced.apk`. Thus, it might sound feasible to deploy the app to some server that supports node and `java`. I'm thinking Vercel would be a good place to do it.

**Comment by reisxd** [comment]
This would require a kinda powerful server and who says that Google won't take down the instance?
