### ISSUE TITLE
cant download the file after building

### ISSUE THREAD

**Issue by saiganesh665544** [reisxd/revanced-builder#181]
![image](https://user-images.githubusercontent.com/29879952/183286607-39d24ea7-0ea8-4402-80f0-2dc5032d0dc8.png)

error for downloading built file :)

**Comment by reisxd** [comment]
If you already had your device connected, that's normal. If you didn't, transfer over revanced/revanced.apk and if you built YT/YTM, revanced/microg.apk.

**Comment by saiganesh665544** [comment]
I didn't understand that , should I connect the device i.e mobile before starting the build?

**Comment by reisxd** [comment]
> I didn't understand that , should I connect the device i.e mobile before starting the build?

You'll need ADB and if you don't, then do what I said, transfer files to your device.

**Comment by saiganesh665544** [comment]
ok got it thanks :)
