### ISSUE TITLE
Cannot GET /revanced.apk

### ISSUE THREAD

**Issue by Ossiam** [reisxd/revanced-builder#183]
After the compiling has finished, the download button redirects to a page that only states "Cannot GET /revanced.apk"

**Comment by r0ckarong** [comment]
+1

Don't think the webserver knows where the files are. The actual path would at least have to be `GET revanced/revanced.apk`

**Comment by ifelixculpa** [comment]
same here 

![image](https://user-images.githubusercontent.com/13099434/183312406-e9709d83-c769-4b5b-8f03-196ea8ca77c0.png)

**Comment by durianbusuk** [comment]
Does anyone know where the file is saved?

The file might be saved somewhere despite the error.

**Comment by MidnightOverlord** [comment]
Not sure if this is important, but I'm also getting the error as well. Must be a mistake when they last updated the builder. That, or they're configuring something on their own end and the problem will resolve itself?

**Comment by durianbusuk** [comment]
> Does anyone know where the file is saved?
> 
> The file might be saved somewhere despite the error.

Ok I found it - the program creates a 'Revanced' folder in the same directory as the program and the apks are stored in the folder.

**Comment by reisxd** [comment]
If you built with a device, thats normal. Because the APK gets deleted after cleanup. If you didn't, this is a bug. I'll try to find if something is going wrong in the backend.

**Comment by ifelixculpa** [comment]
> If you built with a device, thats normal. Because the APK gets deleted after cleanup. If you didn't, this is a bug. I'll try to find if something is going wrong in the backend.

Not with device but somehow it creates the folder in appdata/idm/revanced folder and stores there

**Comment by reisxd** [comment]
The download button won't be shown if you are running on localhost to solve the confusion.
