### ISSUE TITLE
Feature request: Auto advance

### ISSUE THREAD

**Issue by r0ckarong** [reisxd/revanced-builder#184]
Currently the builder requires you to do stuff. I like to do this stuff but I think it would be cool to have to only to do it once and then once a version changes.

For this I propose:

Do the apk version checks at the start after the user has selected the app.  On top of remembering the patches the user selects, store which version they chose the last time. Then you can understand if new patches or versions would be relevant/interesting to that user.
Perform the check and give the user a prompt "there are new patches / new app version would you like to adjust your settings?".

Yes -> Normal mode, Click continue each screen
No -> Auto mode, Runs through the build with all patches and the latest version available

**Comment by reisxd** [comment]
IMO, Builder shouldn't be this automatic. Also

> Do the apk version checks at the start after the user selected the app.

This'd be only useful when the user tries to build for rooted ReVanced.
