### ISSUE TITLE
It does not allow me to select the patches I get that error

### ISSUE THREAD

**Issue by StrikerOnLine** [reisxd/revanced-builder#187]
The webserver is now running!
Opening the app in the default browser...
Done. Check if a browser window has opened
GET / 304 4.314 ms - -
GET /styles/fontawesome.css 304 4.588 ms - -
GET /styles/core.css 304 4.631 ms - -
GET /styles/apps.css 304 4.041 ms - -
GET /index.js 304 4.207 ms - -
GET /webfonts/fa-brands-400.woff2 304 1.913 ms - -
GET /webfonts/fa-solid-900.woff2 304 1.967 ms - -
GET /dependencies/ 304 0.900 ms - -
GET /styles/fontawesome.css 304 1.695 ms - -
GET /styles/core.css 304 2.610 ms - -
GET /styles/dependencies.css 304 2.933 ms - -
GET /index.js 304 2.771 ms - -
GET /patches/ 304 3.036 ms - -
GET /styles/fontawesome.css 304 1.198 ms - -
GET /styles/core.css 304 1.588 ms - -
GET /styles/patches.css 304 1.596 ms - -
GET /index.js 304 1.761 ms - -
An error occured.
Error: Command failed: java -jar ./revanced/revanced-cli-2.9.2-all.jar -a ./revanced/app-release-unsigned.apk -b ./revanced/revanced-patches-2.33.2.jar -l --with-packages

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues

**Comment by reisxd** [comment]
Delete the `revanced` folder.
