### ISSUE TITLE
[BUG] Revanced Builder

### ISSUE THREAD

**Issue by Gam3rrXD** [reisxd/revanced-builder#189]
I just installed the Builder and do the steps but see this ![Screenshot_20220808-024104_Termux.jpg](https://user-images.githubusercontent.com/84348006/183389918-04ab600f-023b-40e4-a43e-b0aa8360f6a4.jpg)

**Comment by reisxd** [comment]
Send the patch output too.

**Comment by Gam3rrXD** [comment]
Where do I find this? The UI?

**Comment by reisxd** [comment]
Yes.

**Comment by Gam3rrXD** [comment]
![Screenshot_20220808-025136_Brave.jpg](https://user-images.githubusercontent.com/84348006/183390944-31b18c8d-52aa-44ff-be00-527e3e9eea51.jpg)

**Comment by reisxd** [comment]
Can you try reinstalling?

**Comment by Gam3rrXD** [comment]
Sure

**Comment by Gam3rrXD** [comment]
Works like a charm must have been a download issue or sum
