### ISSUE TITLE
WELL shit

### ISSUE THREAD

**Issue by hacker2285629** [reisxd/revanced-builder#190]
![Kali-Linux-2022 2-vmware-amd64 - VMware Workstation 08 08 2022 16_11_08 (2)](https://user-images.githubusercontent.com/72620519/183427403-4a9d424e-a9cf-4aa1-b4dc-b0568bfc5d92.png)

**Comment by reisxd** [comment]
Unplug and replug your device, give access to debugging, check if its working with `adb devices` (should say device) and rebuild.
