### ISSUE TITLE
Node giving error on Android

### ISSUE THREAD

**Issue by GameGuyOnYT** [reisxd/revanced-builder#193]
**Describe the bug**
I made a python script to run the builder for me and when I used the python script, Node gave me the error shown in the photo.

**To Reproduce**
1. Enter termux with revanced-builder already ran once
2. Run this python script
3. See error after a few seconds

**Screenshots**
![IMG_20220808_174954](https://user-images.githubusercontent.com/81768350/183446614-6e3b7df0-97a8-464d-95c3-69c30518cfac.jpg)

**revanced-builder Version:** 3.1.3 (probably)

**Desktop (please complete the following information):**

- OS: Android
- Version: 11

**Additional context**
My phone is not rooted, and yes, I have the F-Droid version.

**Comment by reisxd** [comment]
> Run this python script

...? Please see the wiki for actual installation.

**Comment by GameGuyOnYT** [comment]
Sorry, forgot to link [the actual script](https://cdn.discordapp.com/attachments/966007674519027755/1006224881429516318/revanced.py)

**Comment by reisxd** [comment]
> Sorry, forgot to link [the actual script](https://cdn.discordapp.com/attachments/966007674519027755/1006224881429516318/revanced.py)

Use the official installation script.

**Comment by GameGuyOnYT** [comment]
Ok, I misunderstood. Sorry.
