### ISSUE TITLE
Fails at downloading YouTube apk

### ISSUE THREAD

**Issue by Amby713** [reisxd/revanced-builder#194]
at Module._compile (node:internal/modules/cjs/loader:1105:14)
~/revanced-builder-main $ node .
The webserver is now running!
Opening the app in the default browser...
Done. Check if a browser window has opened
GET / 200 20.985 ms - 2343
GET /styles/core.css 200 5.072 ms - 3447
GET /styles/apps.css 200 2.554 ms - 661
GET /index.js 200 2.256 ms - 10419
GET /styles/fontawesome.css 200 2.454 ms - 1007
GET /webfonts/fa-brands-400.woff2 200 4.994 ms - 105068
GET /webfonts/fa-solid-900.woff2 200 4.838 ms - 330908
GET /dependencies/ 200 3.174 ms - 1552
GET /styles/fontawesome.css 304 4.216 ms - -
GET /styles/core.css 304 2.336 ms - -
GET /index.js 304 4.284 ms - -
GET /styles/dependencies.css 200 6.912 ms - 732
GET /webfonts/fa-brands-400.woff2 304 2.423 ms - -
GET /webfonts/fa-solid-900.woff2 304 3.487 ms - -
GET /patches/ 200 6.830 ms - 1510
GET /styles/fontawesome.css 304 1.660 ms - -
GET /styles/core.css 304 0.690 ms - -
GET /index.js 304 0.672 ms - -
GET /styles/patches.css 200 11.278 ms - 573
GET /webfonts/fa-brands-400.woff2 304 1.156 ms - -
GET /webfonts/fa-solid-900.woff2 304 1.365 ms - -
GET /versions/ 200 3.118 ms - 1420
GET /styles/fontawesome.css 304 0.990 ms - -
GET /styles/core.css 304 1.410 ms - -
GET /styles/apps.css 304 0.721 ms - -
GET /index.js 304 1.331 ms - -
GET /styles/dependencies.css 304 1.269 ms - -
An error occured.
TypeError: Cannot set properties of undefined (setting 'version')
    at module.exports (/data/data/com.termux/files/home/revanced-builder-main/wsEvents/SelectAppVersion.js:23:26)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder-main/index.js:100:9)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues
GET /versions/ 304 8.164 ms - -
GET /styles/fontawesome.css 304 0.983 ms - -
GET /styles/core.css 304 2.825 ms - -
GET /styles/apps.css 304 2.855 ms - -
GET /styles/dependencies.css 304 2.915 ms - -
GET /index.js 304 3.251 ms - -
An error occured.
TypeError: Cannot set properties of undefined (setting 'version')
    at module.exports (/data/data/com.termux/files/home/revanced-builder-main/wsEvents/SelectAppVersion.js:23:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder-main/index.js:100:9)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues

**Comment by reisxd** [comment]
@shrihanDev :moyai:

**Comment by Amby713** [comment]
Works now, thanks
