### ISSUE TITLE
an error while build root vesion

### ISSUE THREAD

**Issue by opakholis** [reisxd/revanced-builder#2]
holla @reisxd , it seems to get an error while building for the root version

here is command I use `node . --patch --exclude disable-shorts-button,microg-support --manual-apk`

```
Downloading latest patches, integrations and cli...
Building ReVanced, please be patient!
07-02 07:00:59.278   815   815 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-02 07:00:59.281   815   815 I AndroidRuntime: Using default boot image
07-02 07:00:59.281   815   815 I AndroidRuntime: Leaving lock profiling enabled
07-02 07:00:59.425   815   815 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-02 07:00:59.440   815   815 D AndroidRuntime: Shutting down VM
```

thank you for your hard work on this awesome project, i really appreciate it! 🍺

**Comment by reisxd** [comment]
Hi, you need the exact same YouTube version you installed on your phone, you can download the APK on APKMirror (download the nodpi one and not the bundle) and copy it to your revanced folder and rename it to `youtube.apk`. When the tool asks if you want use it, say yes(`y`).

**Comment by reisxd** [comment]
Hey, I made a new update that'll download the APK automatically thats the same with the installed one on your phone, update to v1.1.0

**Comment by opakholis** [comment]
> Hi, you need the exact same YouTube version you installed on your phone, you can download the APK on APKMirror (download the nodpi one and not the bundle) and copy it to your revanced folder and rename it to `youtube.apk`. When the tool asks if you want use it, say yes(`y`).

lol. i missed the most important step. it's working perfectly now

**Comment by reisxd** [comment]
Alright, closing the issue then!
