### ISSUE TITLE
[docs] but what is ReVanced?

### ISSUE THREAD

**Issue by gregfenton** [reisxd/revanced-builder#20]
From the README:

> This project will allow you to download the YouTube APK and build ReVanced easily!

But there is no link or description as to what ReVanced actually is?

**Comment by reisxd** [comment]
ReVanced is... ReVanced.

**Comment by hyoretsu** [comment]
If you found this repo, chances are you know what Youtube ReVanced is.

**Comment by gregfenton** [comment]
I came to this repo because someone was struggling to use it and posted on a developer forum.

In an effort to help them, I came to review the project they mentioned.

If this repo is meant to be Fight Club, consider making it private  😜
