### ISSUE TITLE
Root build stuck at mounting

### ISSUE THREAD

**Issue by Amby713** [reisxd/revanced-builder#200]
ET /index.js 304 0.639 ms - -
GET /patch/ 304 1.820 ms - -
GET /styles/fontawesome.css 304 1.066 ms - -
GET /styles/core.css 304 1.278 ms - -
GET /styles/dependencies.css 304 1.441 ms - -
GET /index.js 304 0.599 ms - -
An error occured.
Error: Command failed: su -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'
mount: '/data/adb/revanced/com.google.android.youtube.apk'->'/data/app/~~fWLf8RT-yMkBNCVeTQFrvQ==/com.google.android.youtube-euor9HLfJLA5t3oTFTUTJQ==/base.apk': No such file or directory

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues

**Comment by reisxd** [comment]
Reinstall YouTube.
