### ISSUE TITLE
Video Settings

### ISSUE THREAD

**Issue by DrimTim2020** [reisxd/revanced-builder#207]
Look and do not tell me that everything is in order, I tried different versions, and different options, the result is always the same.
This was not until recently, I do not remember exactly, but this is most likely due to new plugins that are loaded to process the file.
![revanced](https://user-images.githubusercontent.com/65110869/183600061-126db994-70f8-4252-a29e-f7f45d8586bf.jpg)

Here's a video showing what's going on!

https://user-images.githubusercontent.com/65110869/183600179-1f1665c1-7f17-4dc3-bee1-12cee5ac105d.mp4

**Comment by reisxd** [comment]
Again, not an issue with Builder. Looks like a you issue too, my client doesn't crash pressing that.

**Comment by DrimTim2020** [comment]
> Again, not an issue with Builder. Looks like a you issue too, my client doesn't crash pressing that.

It's not just me that this happens to many.
Along with this, advertising began to slip.

**Comment by reisxd** [comment]
> > Again, not an issue with Builder. Looks like a you issue too, my client doesn't crash pressing that.
> 
> It's not just me that this happens to many. 

No?

> Along with this, advertising began to slip.

Again, not an issue with Builder.
