### ISSUE TITLE
Cant open executable on macos

### ISSUE THREAD

**Issue by WouterStulp** [reisxd/revanced-builder#208]
**Describe the bug**
When I download the MacOs version of the builder, i cant seem to open it.

**revanced-builder Version:** 
3.1.5

- OS: MacOs
- Version: 12.1

**Comment by shrihanDev** [comment]
Are you using the new M1 Macs?

**Comment by binoysankar** [comment]
> Are you using the new M1/2 Macs?

I have the same issue. Yes I am using M1 Macbook Pro

**Comment by shrihanDev** [comment]
The binaries built and released for MacOS are only for `x86_64`, while Apple's M1/2 Chips are `ARM64`.

Use revanced-builder from source.
