### ISSUE TITLE
Version Selecter gives an Error saying you didn't select an app version, but there is no option. (This is on PC)

### ISSUE THREAD

**Issue by MajorTimberWolf** [reisxd/revanced-builder#209]
![image](https://user-images.githubusercontent.com/110900686/183623436-1adbe40e-9bda-40cc-96fe-aa1d4f0e864d.png)
![image](https://user-images.githubusercontent.com/110900686/183623593-93a1ecf1-a378-43ef-a375-6bfe5cc8b403.png)

I have downloaded Youtube from playstore and also tried it with the 17.29.35 apk, same error comes up

**Comment by reisxd** [comment]
@shrihanDev you didn't set the apkinfo variables in getappversion :moyai:

**Comment by MajorTimberWolf** [comment]
> @shrihanDev you didn't set the apkinfo variables in getappversion 🗿

ah damn, how do i do that? (sorry i'm a bit noob at this)

**Comment by reisxd** [comment]
Fixed in the latest release.

**Comment by MajorTimberWolf** [comment]
> Fixed in the latest release.

ah awesome! Thanks man, good job on this project! :)

**Comment by shrihanDev** [comment]
@reisxd :moyai: ...
