### ISSUE TITLE
The official Subreddit for Builder

### ISSUE THREAD

**Issue by reisxd** [reisxd/revanced-builder#211]
Hi everyone, because of the new rule 5 in [r/revancedapp](https://reddit.com/r/revancedapp), I have created an new subreddit! Please join [r/revanced_builder](https://reddit.com/r/revanced_builder). Also, please note that I'm going to remove posts about 3rd party tools (unless it's only linking their own subreddit and the tool owner made it) in r/revancedapp. Yes, I do moderate there.

**Comment by shrihanDev** [comment]
Close this one? (Let it be pinned)

**Comment by PalmDevs** [comment]
Smh, subreddits suck. Should've made a Discord server.
