### ISSUE TITLE
Add a way to configure Port Number

### ISSUE THREAD

**Issue by DrPleaseRespect** [reisxd/revanced-builder#217]
**Describe the bug**
Revanced Builder crashes due to hardcoded 8080 Port Value

While it's possible to temporarily disable the server that uses the 8080 port, I think it's better to have an option to change the port number instead.

**To Reproduce**

1. Have a server that's already running on Port Number 8080 (i.e qBittorrent Web User Interface)
2. Try to start ReVanced-Builder

**Screenshots**
<details close>
<summary>Open Screenshot</summary>
<img src="https://i.imgur.com/0plkxVB.png">
</details>

**revanced-builder Version:** v3.1.7

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 22H2 (OS Build 22621.232)

**Comment by shrihanDev** [comment]
I think, instead of asking the user to do it, I could make it intuitively choose which port it can bind to.

**Comment by DrPleaseRespect** [comment]
As long as it's possible to resolve conflicts that's fine with me.
