### ISSUE TITLE
How do i install OpenJDK?

### ISSUE THREAD

**Issue by SodaMazing** [reisxd/revanced-builder#219]
I downloaded the zip, but i'm not sure where it goes. The builder won't work without it.

How do i use it?

**Comment by Amby713** [comment]
What platform are you using?

**Comment by SodaMazing** [comment]
> What platform are you using?

Windows

**Comment by Amby713** [comment]
https://jdk.java.net/archive/

**Comment by SodaMazing** [comment]
> https://jdk.java.net/archive/
> 
> Select the windows version

I already downloaded it, i just don't know what to do with the zip after it, i don't see a program or installer inside, or somewhere to put it so the builder recognizes it.

**Comment by Amby713** [comment]
You have to set the path to that folder,  might be easier to try ms version of open jdk
https://aka.ms/download-jdk/microsoft-jdk-17.0.4-windows-x64.msi

If you know how to use Chocolaty,,  it's a lot easier that way
