### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by efnikolas** [reisxd/revanced-builder#220]
**Describe the bug**
I am getting the following error. I also can't see any patches. Please see screenshots. 

An error occured.
Error: Command failed: java -jar ./revanced/revanced-cli-2.9.2-all.jar -a ./revanced/app-release-unsigned.apk -b ./revanced/revanced-patches-2.33.2.jar -l --with-packages --with-versions

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues

**To Reproduce**
Following the process steps for Youtube.

**Screenshots**
![image](https://user-images.githubusercontent.com/67267880/184244034-2f7d8934-15a8-4cbb-96e5-9082f5dea16f.png)
![image](https://user-images.githubusercontent.com/67267880/184244158-d83eb55b-bebb-4ef1-80d2-7d2d66013f88.png)

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop 

- OS: Windows
- Version: 10

**Comment by reisxd** [comment]
Delete the `revanced` folder and restart the server.
