### ISSUE TITLE
Implement a Revanced-Builder Self-Updater?

### ISSUE THREAD

**Issue by bayazidbh** [reisxd/revanced-builder#223]
I didn't see anything about this in the Issues, but given the rapid pace of updates lately, I think it'll be useful to have some sort of self-updater into the binary? Does the Windows and macOS have them already, because I only know of the Linux version.

If there isn't yet, then, since the app is currently WebUI/browser based, maybe the simplest solution would be to first do a check if current binary version = current latest version. If not the same, then prompt the user to either download or continue using current version. Maybe could also list the changelog since their currently used release, or just changelog of the latest release?

If the user choose to download, then it'll just open a new tab directly at the latest version of revanced-builder for their OS; so Linux version would just go to [here](https://github.com/reisxd/revanced-builder/releases/latest/download/revanced-builder-nodejs-linux) for example. If not, they can still use the current version, so no one would complain about forced updates.

Sorry if this is already a thing by the way! Just noticed a lot of releases lately and thought it'd be nice to have if it isn't already a thing.

**Comment by reisxd** [comment]
This isn't a "self updater" but a update notifier. I'll implement this. (Shrihan you can make a PR if you want to)
