### ISSUE TITLE
download not working

### ISSUE THREAD

**Issue by ifelixculpa** [reisxd/revanced-builder#224]
on latest revanced builder i am getting this error

![image](https://user-images.githubusercontent.com/13099434/184423765-7d63b07b-a2f9-4fe1-a4e0-5317fd16bf03.png)

**Comment by ifelixculpa** [comment]
@reisxd is this issue fixed sir ? i still cant get the apk

**Comment by reisxd** [comment]
> @reisxd is this issue fixed sir ? i still cant get the apk

That download button isn't meant to be used if you are running it locally on your PC. The APKs get saved to /revanced.

**Comment by ifelixculpa** [comment]
> > @reisxd is this issue fixed sir ? i still cant get the apk
> 
> That download button isn't meant to be used if you are running it locally on your PC. The APKs get saved to /revanced.

thanks a million sir :)

**Comment by pushkargogte** [comment]
Could you please specified the correct path? As I cant find youtube, youtube music

**Comment by reisxd** [comment]
> Could you please specified the correct path? As I cant find youtube, youtube music

It's where your Builder executable is.

**Comment by pushkargogte** [comment]
> > Could you please specified the correct path? As I cant find youtube, youtube music
> 
> It's where your Builder executable is.


Thanks, I had to delete the revanced folder and then again run the scripts, now both YT and YT music are present in the revanced folder.
