### ISSUE TITLE
App version list is not in proper order

### ISSUE THREAD

**Issue by Amby713** [reisxd/revanced-builder#226]
When it pulls the list of apks,  they newest version is on top,  however,  the latest is second on the list.  This could have some people choose the top most one thinking is the latest 
![Screenshot_20220812-222435_Bromite](https://user-images.githubusercontent.com/105613369/184466784-418b2078-e033-4480-bd70-fd4fe7ec8914.png)

**Comment by reisxd** [comment]
Builder fetches the version list from APKMirror and thats also how it looks on APKMirror.
