### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by TeaqariaWTF** [reisxd/revanced-builder#227]
[builder] Using port 8000
The webserver is now running!
Opening the app in the default browser...
Done. Check if a browser window has opened
GET / 304 11.776 ms - -
GET /styles/fontawesome.css 304 15.942 ms - -
GET /styles/core.css 304 10.150 ms - -
GET /styles/apps.css 304 9.765 ms - -
GET /index.js 304 9.823 ms - -
GET /webfonts/fa-brands-400.woff2 304 3.806 ms - -
GET /webfonts/fa-solid-900.woff2 304 4.065 ms - -
GET /dependencies 301 4.575 ms - 191
GET /dependencies/ 200 10.201 ms - 1552
GET /styles/fontawesome.css 304 5.189 ms - -
GET /styles/core.css 304 4.358 ms - -
GET /index.js 304 3.215 ms - -
GET /styles/dependencies.css 200 5.125 ms - 732
An error occured.
FetchError: request to https://raw.githubusercontent.com/reisxd/revanced-cli-termux/main/aapt2.zip failed, reason: connect ETIMEDOUT 185.199.111.133:443
    at ClientRequest.<anonymous> (/data/data/com.termux/files/home/revanced-builder-main/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues

**Comment by shrihanDev** [comment]
A temporary network error. Just try again!

**Comment by TeaqariaWTF** [comment]
> Geçici bir ağ hatası. Tekrar deneyin!

I tried 3 times, deleted the termux data and tried again, but I keep getting this error

**Comment by TeaqariaWTF** [comment]
> A temporary network error. Just try again!

![Screenshot_20220813-111125_Termux](https://user-images.githubusercontent.com/90970076/184475256-359663db-881f-4c58-8bbc-c78c138e39d4.png)

**Comment by reisxd** [comment]
Looks like GH is having issues. Try refreshing the page until it finishes downloading everything.
