### ISSUE TITLE
is there any docs about available patches?

### ISSUE THREAD

**Issue by dadyarri** [reisxd/revanced-builder#23]
hi. looked in `revanced/revanced-patches`, but didn't find anything, may be you could help. titles of patches isn't very obvious about what they do.

**Comment by futureproof123** [comment]
Hi, check this:
![image](https://user-images.githubusercontent.com/80035973/177228899-a348b273-b9ea-4dda-8bff-d2a1b6a12aad.png)

**Comment by reisxd** [comment]
> hi. looked in `revanced/revanced-patches`, but didn't find anything, may be you could help. titles of patches isn't very obvious about what they do.

Hey, you can run revanced-builder with the patches flag to see every patches description. You need to open CMD though.

Example: 
```bash
revanced-builder.exe --patches
```

**Comment by dadyarri** [comment]
thanks
