### ISSUE TITLE
stop redownloading microg/intergations

### ISSUE THREAD

**Issue by naftali100** [reisxd/revanced-builder#230]
**Describe the bug**
when microg/integrations apk already exist in revanded folder, they still downloaded.

**To Reproduce**
1. do the dependencies step.
2. go back.
3. it'll redownload microg and integrations apk.

**Desktop (please complete the following information):**

- OS: linux
- Version: latest commit #228

**Comment by reisxd** [comment]
Not a bug, it'll download everytime to keep them updated and the files don't have a version. So, builder can't check it's version and it'll download the latest one.
