### ISSUE TITLE
Virus in the app

### ISSUE THREAD

**Issue by DrimTim2020** [reisxd/revanced-builder#236]
![VirusTotal - File - a82f1e5fef13eb5edc6df3309341436b8a0fb9d4e0c9ac0e87991ab99d6bb01a - Google Chrome](https://user-images.githubusercontent.com/65110869/184618112-bdb4910b-3885-4729-9da4-8ad9eceddf75.jpg)
I checked this after when Google chrome began to swear at the downloaded file for Windows -revanced-builder v3.2.0

**Comment by reisxd** [comment]
> 1/67

**Comment by DrimTim2020** [comment]
> > 1/67

Even one can do a lot of grief with a computer.
Would you like it to be 67/67?

**Comment by reisxd** [comment]
> > > 1/67
> 
> Even one can do a lot of grief with a computer. Would you like it to be 67/67?

Use your brain. False positives exists and if you don't trust the GH Actions built binaries, use it from source (:

**Comment by baiorett** [comment]
sir, you have severe brain damage

**Comment by Aunali321** [comment]
yes, it has virus. don't worry we already have your data.

**Comment by rj10rd** [comment]
Braindead

**Comment by reisxd** [comment]
> yes, it has virus. don't worry we already have your data.

cossale shut before i cancel u in reddit

**Comment by baiorett** [comment]
> > yes, it has virus. don't worry we already have your data.
> 
> cossale shut before i cancel u in reddit

too late, check your mailbox

**Comment by DrimTim2020** [comment]
> > > yes, it has virus. don't worry we already have your data.
> > 
> > 
> > cossale shut before i cancel u in reddit
> 
> too late, check your mailbox
Yeah, I've checked idiots like you see for the first time.
Fucking writer.
Get busy son.

**Comment by afnzmn** [comment]
reis will blow up

**Comment by PalmDevs** [comment]
reis will rewrite revanced builder in react native
