### ISSUE TITLE
TikTok separate

### ISSUE THREAD

**Issue by tigr1234566** [reisxd/revanced-builder#238]
**Additional context**
When I building TikTok it automatically load ugc.trill package name, it's Asia version
Need to make two TikTok
Normal with package name musically and Asia it's ugc.trill

https://m.apkpure.com/tiktok-musically/com.zhiliaoapp.musically
https://m.apkpure.com/tiktok-musically/com.ss.android.ugc.trill

Can u separate options by normal TikTok (musically package name) and TikTok Asia (ugc.trill)?
That's very important, thank you

**Comment by reisxd** [comment]
Theres only patches for the normal one. So, even adding it won't work.

**Comment by oSumAtrIX** [comment]
The patch accepts both packages

**Comment by reisxd** [comment]
> The patch accepts both packages

oh lol never knew that

**Comment by tigr1234566** [comment]
> > The patch accepts both packages
> 
> oh lol never knew that

That's why it's bad, that's completely different code part apps
