### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by jackson177** [reisxd/revanced-builder#24]
Downloading latest patches, integrations and cli...
[app-release-unsigned.apk] ✓
[microg.apk] ✓
No device found! Fallback to only build.
Unhandled Rejection
Reason: Error: Command failed: java -jar ./revanced/revanced-cli-2.3.1-all.jar -b ./revanced/revanced-patches-2.8.0.jar -l
Error: Invalid or corrupt jarfile ./revanced/revanced-cli-2.3.1-all.jar

**Comment by reisxd** [comment]
> Downloading latest patches, integrations and cli... [app-release-unsigned.apk] ✓ [microg.apk] ✓ No device found! Fallback to only build. Unhandled Rejection Reason: Error: Command failed: java -jar ./revanced/revanced-cli-2.3.1-all.jar -b ./revanced/revanced-patches-2.8.0.jar -l Error: Invalid or corrupt jarfile ./revanced/revanced-cli-2.3.1-all.jar

Have you plugged in your device? Also, delete the `revanced` folder.

**Comment by jackson177** [comment]
i deleted revanced folder it fixes the issue, Thanks!

**Comment by rodrigoswz** [comment]
I also have this problem, deleting the revanced folder didn't work for me. Command `adb devices` shows my device normally.

```
C:\revanced-builder\revanced-builder>node . --patch --exclude microg-support,hide-cast-button
Downloading latest patches, integrations and cli...
[app-release-unsigned.apk] ✓
[microg.apk] ✓
Unhandled Rejection
Reason: Error: Couldn't find the device. Please plug in the device.
Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...
```
