### ISSUE TITLE
Doesn't download aapt2.zip file

### ISSUE THREAD

**Issue by Alprnn357** [reisxd/revanced-builder#242]
**Describe the bug**
I'm trying to build YT Music but builder doesn't download aapt2.zip file.

**To Reproduce**
Just do [these steps](https://github.com/reisxd/revanced-builder/wiki/How-to-use-revanced-builder-on-Android) and welcome to the download error in the termux.

**Screenshots**
![Screenshot_20220816-164532_Chrome](https://user-images.githubusercontent.com/37711793/184895274-5d21a6c0-5bdf-49c3-b85b-16411250b349.jpg)
![Screenshot_20220816-163854_Termux](https://user-images.githubusercontent.com/37711793/184895292-0d92a7fe-11e5-41f4-b2ce-46668808552c.jpg)

**revanced-builder Version:** [e.g. v1.2.10]
[latest commit](https://github.com/reisxd/revanced-builder/commit/f4b67d0a3796ac5c54968bc321e290dee90d4712) a.k.a my love

**Comment by reisxd** [comment]
Try again.

**Comment by Alprnn357** [comment]
> Try again.

Still same
![Screenshot_20220816-165538_Termux](https://user-images.githubusercontent.com/37711793/184897982-28f47719-235b-45c1-8cf4-0c71abe2f558.jpg)

**Comment by Alprnn357** [comment]
i can download it directly via chrome.
![20220816_165914](https://user-images.githubusercontent.com/37711793/184898460-40c87ce8-f739-4197-8c67-462ed515086d.jpg)

**Comment by Alprnn357** [comment]
Ok it's fixed thank you.
![Screenshot_20220816-170241_Chrome](https://user-images.githubusercontent.com/37711793/184899240-564798f3-d125-4d10-9596-ee0a3b312963.jpg)

**Comment by Alprnn357** [comment]
![Screenshot_20220818-123813_Termux](https://user-images.githubusercontent.com/37711793/185363745-3e0b5653-c087-49db-9195-b0ed2a1e4c1e.jpg)

**Comment by Rikysonic** [comment]
Probably a load balancer problem, try changing the DNS, so that it will hopefully resolve raw.githubusercontent.com to another IP address.

**Comment by Alprnn357** [comment]
> Probably a load balancer problem, try changing the DNS, so that it will hopefully resolve raw.githubusercontent.com to another IP address.

I changed DNS ro Cloudfare, OpenDNS and Google. No one fixed the issue. I tried reinstalling and now this thing happened.
![Screenshot_20220818-132553_Termux](https://user-images.githubusercontent.com/37711793/185373677-2bcd659e-78e6-4442-98b0-a058e413e414.jpg)

**Comment by Rikysonic** [comment]
If you're on WiFi, there could be some sort of ban/rate limit applied from GitHub to your IP, you could try to reboot the modem to change your IP address or test with a VPN on your device.

**Comment by reisxd** [comment]
This also happens to me on my PC for some reason and no, I don't know a fix.

**Comment by Alprnn357** [comment]
> If you're on WiFi, there could be some sort of ban/rate limit applied from GitHub to your IP, you could try to reboot the modem to change your IP address or test with a VPN on your device.

Thank you, i have tested with VPN now my issue is solved.

**Comment by Alprnn357** [comment]
> This also happens to me on my PC for some reason and no, I don't know a fix.

You can test a VPN. I have solved my issue.

**Comment by reisxd** [comment]
> > This also happens to me on my PC for some reason and no, I don't know a fix.
> 
> You can test a VPN. I have solved my issue.

It sometimes works, then stops working for a long time. Eh, not really a big issue for me.
