### ISSUE TITLE
Memory error when patching reddit and tiktok

### ISSUE THREAD

**Issue by GTABossMDS** [reisxd/revanced-builder#244]
I tried patching reddit and tiktok using the builder but it shows a memory error as attached. There is no problems when patching youtube. Can anybody help? I do not know how to compute and thus do not know how to install Re-reddit and re- tiktok.
![Capture](https://user-images.githubusercontent.com/76740656/185019040-7258dc10-8c1b-45ae-b6b2-d9a708162f2d.JPG)

**Comment by reisxd** [comment]
Read the error, your computer rans out of memory and the java process kills itself.

**Comment by GTABossMDS** [comment]
i have 32gb of ram on my pc with only chrome running. I dont see why my computer would run out of memory

**Comment by Nowaaru** [comment]
It's not that he ran out of memory, it's that the heap size is too small for your app to run. This can be changed by changing the process arguments, however with this app it seems that it appears that this is not possible?

**Comment by Nowaaru** [comment]
I hate to make two posts on the same topic in the row - but, @reisxd, I'd appreciate if you were to take another look at this issue.

**Comment by mindstop** [comment]
Had this same issue, this is because you are using 32 bit JDK. Change it to 64 bit JDK and it will work fine. @GTABossMDS
