### ISSUE TITLE
No such file directory

### ISSUE THREAD

**Issue by SpiralTune34** [reisxd/revanced-builder#245]
Its error after finished it said i have to report if theres an issue. 
![Screenshot_20220817_235351_com android chrome](https://user-images.githubusercontent.com/111450066/185190605-7e9ed2dc-c27f-40dc-ae21-3ca98ad5fc65.jpg)
![Screenshot_20220817_235237_com termux](https://user-images.githubusercontent.com/111450066/185190633-40b24f44-f7fe-4045-9fad-fcad4f3063b3.jpg)

**Comment by reisxd** [comment]
Reinstall Builder.
