### ISSUE TITLE
Revanced crashing on start 

### ISSUE THREAD

**Issue by Sleff1** [reisxd/revanced-builder#246]
When opening revanced it just crashes I tried without custom branding and it opens but only ads are removed and there is no rest of the patches that i applied 

Android:11 
Redmi note 8 pro 
No root

**Comment by reisxd** [comment]
Which patches did you include?

**Comment by Sleff1** [comment]
![IMG_20220817_193137.jpg](https://user-images.githubusercontent.com/105948899/185204673-b60fffa0-68da-411b-9d15-c7e2aa0d783b.jpg)

Also i have that warning

**Comment by Sleff1** [comment]
Only ad removing patches are working and rest isn't and custom branding crashes

**Comment by reisxd** [comment]
Did you install MicroG?

**Comment by Sleff1** [comment]
~~INSERT HUGE FACEPALM HERE~~


THANK YOU IM JUST DUMB I really forgot about that app 🙃 Now it's working fine 

Also should i worry about that warning?

**Comment by Sleff1** [comment]
Alright I'm closing it

**Comment by reisxd** [comment]
> ~~INSERT HUGE FACEPALM HERE~~
> 
> 
> THANK YOU IM JUST DUMB I really forgot about that app 🙃 Now it's working fine 
> 
> Also should i worry about that warning?

Nope, that's okay. Closing.
