### ISSUE TITLE
Outdated java version 

### ISSUE THREAD

**Issue by grandeotos** [reisxd/revanced-builder#247]
**Describe the bug**
Revanced builder doesn't detect new versions of OpenJDK
**To Reproduce**

1. Execute the app 
2. Select 'YouTube' on the app selector
3. Click continue
```
[builder] You have an outdated version of JDK.
Please get it from here: https://jdk.java.net/archive
Download the zip/tar.gz for your OS under "17.0.2 (build 17.0.2 8)"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/28305872/185204918-2c175ebc-3e74-482d-ae92-3c4032f2ee63.png)
![image](https://user-images.githubusercontent.com/28305872/185204933-5f8d0f14-90a6-4e1d-b7cb-b3e80e3fb953.png)

**revanced-builder Version:** [e.g. v1.2.10]
revanced-builder v3.2.1

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 21H2

**Additional context**
I have installed OpenJDK from [Adoptium](https://adoptium.net/)

**Comment by FadeMind** [comment]
You have to set enable `JAVA_HOME` in OpenJDK setup also. 
![20220817-1660760277](https://user-images.githubusercontent.com/9846948/185214067-dccd6131-f34a-477f-94f5-82558778941f.png)

**Comment by grandeotos** [comment]
> You have to set enable `JAVA_HOME` in OpenJDK setup also. ![20220817-1660760277](https://user-images.githubusercontent.com/9846948/185214067-dccd6131-f34a-477f-94f5-82558778941f.png)

I already did in my setup
It's weird, but now it's not happening  
![image](https://user-images.githubusercontent.com/28305872/185250642-31734dc6-659b-489b-9e94-c8e2df0918d0.png)

But magically it's working, so... I'll close the issue
Thx for the reply tho
![image](https://user-images.githubusercontent.com/28305872/185250969-7c3ed4ae-7cb7-4347-906e-3b33ccc9af2d.png)
