### ISSUE TITLE
ReTwitter ads still showing on main timeline on Android 13

### ISSUE THREAD

**Issue by midgelfc** [reisxd/revanced-builder#249]
**Describe the bug**
Installed ReTwitter using revanced builder on Android and installed ReVanced-Twitter-v9.54.1-release.0-ar m64-v8a-cli 2.9.3-all-v2.9.3.jarpatche s_2.38.0-v2.38.0.apk.

Ads are being shown on the main timeline on latest version

**To Reproduce**

1. Open Twitter
2. login
3. main timeline loads with ads

**Screenshots**
Timeline with Ads
![image](https://user-images.githubusercontent.com/78561981/185260677-e855c116-6a33-4248-a9aa-cb840275b630.png)

App details
![image](https://user-images.githubusercontent.com/78561981/185260805-4a76797e-7ff0-4f0b-bab0-4d338385e6f5.png)

**revanced-builder Version:**  v3.2.1

**Desktop (please complete the following information):**
- Phone: Pixel 6 Pro
- OS: Android 13
- Build Number: TP1A.220624.021

**Additional context**
Running the latest public release of Android 13

**Comment by reisxd** [comment]
Not an issue with Builder. Please make an issue in revanced/revanced-patches.
