### ISSUE TITLE
When excluding any feature revanced.apk disappears from revanced folder.

### ISSUE THREAD

**Issue by wiredroid** [reisxd/revanced-builder#25]
When excluding any features revanced.apk appears and then disappears from revanced folder, then the following AndroidRuntime log is shown. My device is rooted.

Downloading latest patches, integrations and cli...
[app-release-unsigned.apk] ✓
[microg.apk] ✓
? Select the patches you want to exclude. custom-branding, old-quality-layout, hide-autoplay-button,
disable-create-button, hide-shorts-button, hide-cast-button (Root required), microg-support (Root required)
Downloading the YouTube APK, this'll take some time!
[youtube.apk] ✓
Download complete!
Building ReVanced, please be patient!
07-05 22:29:25.408 15422 15422 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-05 22:29:25.410 15422 15422 I AndroidRuntime: Using default boot image
07-05 22:29:25.410 15422 15422 I AndroidRuntime: Leaving lock profiling enabled
07-05 22:29:25.410 15422 15422 D AndroidRuntime: addProductProperty: pBrand1 is not null
07-05 22:29:25.410 15422 15422 D AndroidRuntime: addProductProperty: not brand or 7
07-05 22:29:25.474 15422 15422 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-05 22:29:25.489 15422 15422 D AndroidRuntime: Shutting down VM

You now can install ReVanced and MicroG by transferring revanced/revanced.apk and revaned/microg.apk!
Press any key to exit...

![image](https://user-images.githubusercontent.com/86910506/177328395-837b2aee-b966-4d2e-ad78-9ae9d7c39a13.png)

**Comment by reisxd** [comment]
Because it clears the files once you build. Don't build for root and unplug your device to get the APK.

**Comment by reisxd** [comment]
> How can I exclude options? If I exclude any option with the device unplugged it won't work it won't let me build.

Any errors?

**Comment by wiredroid** [comment]
![image](https://user-images.githubusercontent.com/86910506/177335383-5cd6d77b-38ab-495c-9552-fbd0d3a95176.png)

**Comment by reisxd** [comment]
> ![image](https://user-images.githubusercontent.com/86910506/177335383-5cd6d77b-38ab-495c-9552-fbd0d3a95176.png)
> 

You are excluding features that requires root to be excluded.

**Comment by wiredroid** [comment]
> > ![image](https://user-images.githubusercontent.com/86910506/177335383-5cd6d77b-38ab-495c-9552-fbd0d3a95176.png)
> 
> You are excluding features that requires root to be excluded.

My device is rooted but when I plug it in and ADB is granted root access the apk disappears.

**Comment by reisxd** [comment]
> > > ![image](https://user-images.githubusercontent.com/86910506/177335383-5cd6d77b-38ab-495c-9552-fbd0d3a95176.png)
> > 
> > You are excluding features that requires root to be excluded.
> 
> My device is rooted but when I plug it in and ADB is granted root access the apk disappears.

You can't install rooted apk manually, and when you don't have a device plugged in, you can't exclude patches that requires root to get excluded.

**Comment by wiredroid** [comment]
> > > > ![image](https://user-images.githubusercontent.com/86910506/177335383-5cd6d77b-38ab-495c-9552-fbd0d3a95176.png)
> > > 
> > > 
> > > You are excluding features that requires root to be excluded.
> > 
> > 
> > My device is rooted but when I plug it in and ADB is granted root access the apk disappears.
> 
> You can't install rooted apk manually, and when you don't have a device plugged in, you can't exclude patches that requires root to get excluded.

So how can I get the custom build using your tool? It cant be done then?

**Comment by reisxd** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/86910506/177335383-5cd6d77b-38ab-495c-9552-fbd0d3a95176.png)
> > > > 
> > > > 
> > > > You are excluding features that requires root to be excluded.
> > > 
> > > 
> > > My device is rooted but when I plug it in and ADB is granted root access the apk disappears.
> > 
> > You can't install rooted apk manually, and when you don't have a device plugged in, you can't exclude patches that requires root to get excluded.
> 
> So how can I get the custom build using your tool? It cant be done then?

Don't exclude microg-support and hide-cast-button and unplug your device.

**Comment by wiredroid** [comment]
No point to having it the lift in the first place then. The whole point is to remove microG for rooted devices. That's what root and non root Vanes does in it's logic.

**Comment by reisxd** [comment]
> > So how can I get the custom build using your tool? It cant be done then?
> 
> Install Youtube in your device, connect your device and do `node . --patch --exclude microg-support` However there's a bug currently and requires #36 pull request to be merged to work.

Yes, using the patch flag will cause an issue but not related with this one. They went with the "noob way" and didn't work. I can't test rooted builds so /shrug
