### ISSUE TITLE
Getting error while patching Reddit or Twitter on Android

### ISSUE THREAD

**Issue by th3g0dfather** [reisxd/revanced-builder#250]
**Describe the bug**
[builder] An error occured.
Error: Command failed: cp revanced/ReVanced-Twitter-v9.54.0-release.0-arm64-v8a-cli_2.9.3-all-v2.9.3.jar-patches_2.38.0-v2.38.0.apk /storage/emulated/0/ReVanced-Twitter-v9.54.0-release.0-arm64-v8a-cli_2.9.3-all-v2.9.3.jar-patches_2.38.0-v2.38.0.apk
cp: cannot create regular file '/storage/emulated/0/ReVanced-Twitter-v9.54.0-release.0-arm64-v8a-cli_2.9.3-all-v2.9.3.jar-patches_2.38.0-v2.38.0.apk': Operation not permitted

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**To Reproduce**

1. Follow browser prompts to patch Reddit or Twitter.

- OS:  Android
- Version: 12

**Comment by reisxd** [comment]
You didn't give access to the storage, give it by using the `termux-setup-storage`.

**Comment by th3g0dfather** [comment]
Thank you very much.
And I'm really sorry for reporting this bug, I assumed I had run `termux-setup-storage`
