### ISSUE TITLE
Rooted app downgrading after reboot

### ISSUE THREAD

**Issue by Sy1er** [reisxd/revanced-builder#254]
Downloaded latest version of builder on windows PC. Have been using builder from sometime now. Installed latest version of YouTube (17.32.35) that revanced support. Flashed all the patches that I had on previous version. After reboot the app downgraded to 17.29.34 and force closes.

![Screenshot_20220818-172111.jpg](https://user-images.githubusercontent.com/17670557/185390203-c2c359e1-7228-4b2c-bb24-53f392f84a2f.jpg)

![Screenshot_20220818-172116.jpg](https://user-images.githubusercontent.com/17670557/185390227-51ee6789-24b8-4129-900f-9fc9ad16ad31.jpg)

![Screenshot_20220818-172929.jpg](https://user-images.githubusercontent.com/17670557/185390241-21801ff1-ba01-4938-9102-a47ca72d82e2.jpg)

**Comment by Rikysonic** [comment]
Check in /data/adb/service.d and /data/adb/post-fs-data.d, with a root file explorer, that you don't have any old .sh files related to Vanced/ReVanced.

If you want to start from scratch, you can:
- delete the /data/adb/revanced folder
- delete the mount_revanced_xxx.sh files in /data/adb/service.d
Then try to patch YouTube again.

**Comment by Sy1er** [comment]
> Check in `/data/adb/service.d` and `/data/adb/post-fs-data.d`, with a root file explorer, that you don't have any old .sh files related to Vanced/ReVanced. In particular, unless you have other mods, `/data/adb/post-fs-data.d` should be empty or not exist.
> 
> If you want to start from scratch, you can:
> - delete the `/data/adb/revanced` folder
> - delete the `mount_revanced_xxx.sh` files in `/data/adb/service.d`
> 
> Then try to patch YouTube again.

Thanks, it worked. No idea what was the issue but I had updated and downgraded YouTube versions before and then used builder for patching. Thanks again
