### ISSUE TITLE
Tried to patch tiktok and i Cant login in tiktok using gmail

### ISSUE THREAD

**Issue by SpiralTune34** [reisxd/revanced-builder#255]
**Describe the bug**

**To Reproduce**

1. Go to 'tiktok'
2. Click on 'continue with gmail'
3. Choose an acc
4. Not logging in

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**
Even though i installed microg i still cant login using gmail im not sure if it is working using username but my acc is bind on gmail

**Comment by reisxd** [comment]
Not an issue with Builder and is known by the ReVanced Team.
