### ISSUE TITLE
Is root or no root variant?

### ISSUE THREAD

**Issue by laltroweb** [reisxd/revanced-builder#256]
Build, seems to work, but isn't root variant.
I missed something to build as root variant?
Ty.

**Comment by reisxd** [comment]
You have to exclude MicroG Patch to start an rooted build.

**Comment by Rikysonic** [comment]
> Build, seems to work, but isn't root variant. I missed something to build as root variant? Ty.

Dunno exactly, but, **if you are using the Termux version**, you can try this:
- run Termux
- write `su`, then Enter. It should ask for root access.
- Grant it, then type `exit`, Enter, then again type `exit`, Enter.
- Termux will now close.
- Now reopen it and proceed as normal (no `su` needed this time).

Check if the root mode is now available - to verify it, just check that "Hide Cast Button" patch is visible, with the comment "Needed for Non-Root Building", if so, the tool knows that you have root and it's basically giving you the possibility to build for non-root mode (obv you DON'T WANT to select the patches with the "Needed for Non-Root Building" comment, you just want them to be visible).

**Comment by laltroweb** [comment]
Ty, I'll try again.

**Comment by SenseiSchizo** [comment]
> > Build, seems to work, but isn't root variant. I missed something to build as root variant? Ty.
> 
> Dunno exactly, but, **if you are using the Termux version**, you can try this:
> 
>     * run Termux
> 
>     * write `su`, then Enter. It should ask for root access.
> 
>     * Grant it, then type `exit`, Enter, then again type `exit`, Enter.
> 
>     * Termux will now close.
> 
>     * Now reopen it and proceed as normal (no `su` needed this time).
> 
> 
> Check if the root mode is now available - to verify it, just check that "Hide Cast Button" patch is visible, with the comment "Needed for Non-Root Building", if so, the tool knows that you have root and it's basically giving you the possibility to build for non-root mode (obv you DON'T WANT to select the patches with the "Needed for Non-Root Building" comment, you just want them to be visible).

This works perfectly!
