### ISSUE TITLE
No matter how much I build, it keeps bringing up advertisements when opening videos.

### ISSUE THREAD

**Issue by StrikerOnLine** [reisxd/revanced-builder#257]
Since Android 12 with the most current version of youtube and those recommended by the patches, with root access, revanced still does not work. Always built from android or windows 11 always comes up with ads. Is it my problem or is it the way revanced works?

**Comment by StrikerOnLine** [comment]
The solution I found to not have the problem of advertising that appears from time to time in the videos was to look at the final part at the time of mounting the app says that failed to delete the cache, in my android I just went to the applications, youtube and delete the app data ONLY CLEAR THE DATA and with that I did not have advertising in the app revanced with the root method Windows 11 --> Android 12

**Comment by reisxd** [comment]
Not an issue with Builder, make an issue in revanced/revanced-patches.

**Comment by StrikerOnLine** [comment]
Ok boss
