### ISSUE TITLE
Patch menu

### ISSUE THREAD

**Issue by DrimTim2020** [reisxd/revanced-builder#26]
Guys, make a description of the patcher, for example, I have a couple of those that I figured out.
( * ) hide-autoplay-button - Set star - an autoplay button will be displayed on the video.

( * ) disable-create-button - Set star - Enables - create a short film, upload a video, start streaming

( * ) amoled  - Set an asterisk disables the black theme

( * ) hide-shorts-button  -  Set an asterisk, turns on the shorts button.

**Comment by reisxd** [comment]
> Guys, make a description of the patcher, for example, I have a couple of those that I figured out. ( * ) hide-autoplay-button - Set star - an autoplay button will be displayed on the video.
> 
> ( * ) disable-create-button - Set star - Enables - create a short film, upload a video, start streaming
> 
> ( * ) amoled - Set an asterisk disables the black theme
> 
> ( * ) hide-shorts-button - Set an asterisk, turns on the shorts button.

Might add it in v1.2.5!

**Comment by hyoretsu** [comment]
Tbh this issue would be even better in the ReVanced repo. I had to search for each patch's .kt to scrape the descriptions.

**Comment by reisxd** [comment]
> Tbh this issue would be even better in the [ReVanced Patches](https://github.com/revanced/revanced-patches) repo. I had to search for each patch's .kt to scrape the descriptions.

Psst, `-l` or the `--list` flag exists in ReVanced CLI!
