### ISSUE TITLE
Cannot compile new version

### ISSUE THREAD

**Issue by laltroweb** [reisxd/revanced-builder#262]
![Screenshot_20220819-150727_Termux](https://user-images.githubusercontent.com/16841896/185626808-8c2fff78-1f1e-4195-9d1d-d1dbfa21fb23.png)

Tried to update termux to update/reinstall revanced/builder, to remove npm folder... Bit still same error.
Any help?

**Comment by reisxd** [comment]
Do `rm -rf .npm` and run Builder with `./revanced-builder.sh`.

**Comment by laltroweb** [comment]
`┌──(lupastro@localhost)-[~]
└─$ rm -rf .npm                                               ┌──(lupastro@localhost)-[~]                                   └─$ ls
downloads  revanced-builder       revanced-builder.sh
help       revanced-builder-main  storage
┌──(lupastro@localhost)-[~]
└─$ rm -rf revanced-builder/
┌──(lupastro@localhost)-[~]
└─$ rm -rf revanced-builder-main/
┌──(lupastro@localhost)-[~]
└─$ rm -rf help
┌──(lupastro@localhost)-[~]
└─$ ls
downloads  revanced-builder.sh  storage
┌──(lupastro@localhost)-[~]
└─$ ./revanced-builder.sh
[revanced-builder.sh] Installing revanced-builder...
[revanced-builder.sh] Updating Termux and installing dependencies...
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main: ok
Get:1 https://packages-cf.termux.dev/apt/termux-main stable InRelease [14.0 kB]
Get:2 https://packages-cf.termux.dev/apt/termux-main stable/main aarch64 Packages [435 kB]
Fetched 449 kB in 2s (188 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libc++ ndk-sysroot
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1674 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 25866 files and directories currently installed.)
Preparing to unpack .../libc++_25-2_aarch64.deb ...
Unpacking libc++ (25-2) over (25-1) ...
Setting up libc++ (25-2) ...
(Reading database ... 25866 files and directories currently installed.)
Preparing to unpack .../ndk-sysroot_25-1_aarch64.deb ...
Unpacking ndk-sysroot (25-1) over (25) ...
Setting up ndk-sysroot (25-1) ...
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs-lts is already the newest version (16.16.0-1).
openjdk-17 is already the newest version (17.0-22).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[revanced-builder.sh] Downloading revanced-builder...
[revanced-builder.sh] Unzipping...
[revanced-builder.sh] Installing packages...
npm ERR! code EACCES
npm ERR! syscall link
npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/657e8167
npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/89/10/cf24a50f544343edd1cf3bcae46ce9cfa720f281c0c5b568e9796342832f163f6ad77315cbf13b2445e425e8eac1d86efe509ada82cd6ad7916e75cec6eb
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 10441:10441 "/data/data/com.termux/files/home/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-08-19T14_39_21_535Z-debug-0.log
node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module '/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/node_modules/debug/src/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js:14:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/node_modules/debug/package.json',
  requestPath: 'debug'
}
┌──(lupastro@localhost)-[~]
└─$`

Already tried (manually deleted from file browser), but not work.

**Comment by laltroweb** [comment]
![Screenshot_20220819-164213_Termux](https://user-images.githubusercontent.com/16841896/185644233-b0162fc9-5d0f-4b5d-8e75-d96bf73a86ca.png)
![Screenshot_20220819-164224_Termux](https://user-images.githubusercontent.com/16841896/185644238-d6bf0a01-7e2a-4946-9c4d-36a6c79f0043.png)

**Comment by laltroweb** [comment]
Other errors:
`┌──(lupastro@localhost)-[~]
└─$ ./revanced-builder.sh
[revanced-builder] Already gotten storage access.
[revanced-builder] Node.js and JDK already installed!
[revanced-builder] revanced-builder not installed. Installing...
[revanced-builder] Downloading revanced-builder...
[revanced-builder] Unzipping...
mv: cannot move 'revanced-builder-main/.' to './.': Device or resource busy
mv: cannot move 'revanced-builder-main/..' to './..': Device or resource busy
[revanced-builder] Installing packages...
npm ERR! code EACCES
npm ERR! syscall link`

**Comment by laltroweb** [comment]
U have closed, but i lost about 1hr for fix this issues...
Finally full edit your script and now run as expected.

`#!/bin/bash
wget https://github.com/reisxd/revanced-builder/archive/refs/heads/main.zip
mv main.zip revanced-builder-main.zip
unzip revanced-builder-main.zip
cd revanced-builder-main
npm i
node .`

So, sorry bro, but something is wrong in your long code (usually simplest is best) 😅👍
