### ISSUE TITLE
Revanced Builder cannot install vanced microg

### ISSUE THREAD

**Issue by SafariKnight** [reisxd/revanced-builder#263]
**To Reproduce**

1: If you already have it installed, uninstall vanced microg
2: Build anything with the requirement vanced microg support
3: Open up the terminal that opens with the builder
4: See error

**revanced-builder Version: v3.2.2** 

**Desktop**

- OS: Windows 11 Pro
- Version: 10.0.22000 Build 22000

**Additional context**
Changing the name of the microg apk is the issue

**Comment by reisxd** [comment]
> See error

You didn't even show the errror...?

> Changing the name of the microg apk is the issue

You shouldn't change it.
