### ISSUE TITLE
A dark background with black text

### ISSUE THREAD

**Issue by CruxH** [reisxd/revanced-builder#267]
On the version download screen, there is black text on a dark background:

![image](https://user-images.githubusercontent.com/7459949/185643101-80284bc8-675f-45ad-ad90-5f9a39e15d67.png)

**Comment by Alprnn357** [comment]
Which browser are you using?

**Comment by CruxH** [comment]
I am using Vivalidi 5.4.2753.37 (Stable channel) (64-bit). It appears the same on Edge 104.0.1293.54 (Official build) (64-bit). I am also on Win10 that's set to dark mode.

**Comment by Alprnn357** [comment]
> I am using Vivalidi 5.4.2753.37 (Stable channel) (64-bit). It appears the same on Edge 104.0.1293.54 (Official build) (64-bit). I am also on Win10 that's set to dark mode.

try using Chrome. It should be fine on it.

**Comment by CruxH** [comment]
Perhaps it will, but that doesn't solve the issue.
Text on other screen appears fine, e.g.:

![image](https://user-images.githubusercontent.com/7459949/185650993-77e904fe-a811-405d-b84d-164088021121.png)

**Comment by ActuallyTheSun** [comment]
Are you sure there's no "force dark mode" option messing with it? Because its most likely not a builder issue

**Comment by CruxH** [comment]
> Are you sure there's no "force dark mode" option messing with it? Because its most likely not a builder issue

Default settings are in place. Even when force-disabled, it behaves the same.
Once again, the dark text can only be seen on the download screen. It is white on the rest of the screens.
