### ISSUE TITLE
Installing ReVanced alongside Vanced

### ISSUE THREAD

**Issue by gnite** [reisxd/revanced-builder#270]
Sorry, I don't know where else to ask this. Can I install ReVanced Youtube alongside the old Vanced to try if it works properly, without losing Vanced in case it doesn't? And if so, is the old MicroG I already have enough, or do I have to install the one from ReVanced?

**Comment by SafariKnight** [comment]
They are different packages so installing them alongside each other is fine, And Revanced just installs the same microg youtube vanced used so you're fine

**Comment by gnite** [comment]
Awesome, thank you
