### ISSUE TITLE
WarnWetter versions bug

### ISSUE THREAD

**Issue by tobix88** [reisxd/revanced-builder#271]
**Describe the bug**
No versions showing up. [This](https://pastebin.com/cyDTyWTX)  is the error in termux.

**To Reproduce**
Start rev.builder > WarnWetter > Continue > Promo Codes > Continue > No Versions showing up
**revanced-builder Version:** [e.g. v1.2.10]

**Screenshots**
Got non

**Desktop (please complete the following information):**

- OS: [Android OS]
- Version: [12]

**Additional context**
Nothing

**Comment by reisxd** [comment]
@ActuallyTheSun bruh

**Comment by tobix88** [comment]
@ActuallyTheSun thanks for fixing 🙏
