### ISSUE TITLE
Doesn't compile on Android

### ISSUE THREAD

**Issue by dadazord** [reisxd/revanced-builder#275]
Found an interesting problem, ReVancedBuilder does not want to a compilation. Builder automatically installs npm 8.11.0, but on some devices this creates an error, as you can see in my screenshot.  If you update the package manager to 8.18.0+, then it starts working normally.
![Screenshot_20220819-202236_Chrome-1](https://user-images.githubusercontent.com/39309996/185734717-b9ccc404-2cd5-487b-b8b3-f94d94d11fca.jpg)

**Comment by reisxd** [comment]
NPM version can't have something wrong with the building process, which isn't even in JS, it uses ReVanced CLI which is Kotlin/Java. And won't fix this issue, because this issue occurs for no apparent reason.
