### ISSUE TITLE
No installation version appears 

### ISSUE THREAD

**Issue by Fa3l** [reisxd/revanced-builder#277]
**Describe the bug**
When we get to the part where we choose the YouTube version, no version appears, it's just empty and also when we're installing the packages in termux it always gives an error when downloading the open-jdk-17_17 And with that we have to run the installation command again to proceed 

**To Reproduce**

1. Start standard installation
2. It will give an error when trying to download a package, then you have to run the installation command again to proceed.
3. When you open Chrome choose YouTube and proceed 
4. when you get to the version selection screen nothing will happen and this is the error

**Screenshots**
![Screenshot_20220820-130249](https://user-images.githubusercontent.com/109783042/185756809-72a3ba66-e882-40a7-adfc-f20c003aa71f.png)
![Screenshot_20220820-131211](https://user-images.githubusercontent.com/109783042/185756810-bc6d6e6a-9dff-4112-b638-faab63277218.png)

**revanced-builder Version:** [e.g. v3.2.3] latest

**Desktop (please complete the following information):**

- OS: [e.g. Android]
- Version: [e.g. 8.1]

Additional information
I'm not a programmer

**Comment by reisxd** [comment]
No error log when the versions is empty, and install JDK using `pkg install openjdk-17`.
