### ISSUE TITLE
Adding patches to build fails when system locale is Arabic

### ISSUE THREAD

**Issue by adhammagdy** [reisxd/revanced-builder#278]
Describe the bug:
If you set the regional format of the windows system to Arabic(Egypt), the build for revanced youtube produces severe "parser syntax errors", the build finishes but no patches are integrated..

To reproduce:
1- set the regional format for the system to Arabic (Egypt) and reboot
2- download and run the script
3- go through the steps for making youtube with patches
4- start building
5- an apk will be made but it will basically be the original youtube without any patches
6- set the windows regional format to English (US) and reboot
7- repeat steps 3:5 and the build will be successful without issues

revanced-builder Version: 3.2.3
OS: Windows 10 21h2
![Screenshot 2022-08-20 203815](https://user-images.githubusercontent.com/37498515/185761659-93b212db-6508-4a20-aec0-dd49b2a719e4.png)

**Comment by reisxd** [comment]
Run from source and add `console.log('java ' + args.join(' '));` to https://github.com/reisxd/revanced-builder/blob/5ef8ce3e81aa3fd69f811c622726a8d400045cb8/wsEvents/PatchApp.js#L239

And send the output here.

**Comment by ifelixculpa** [comment]
> Run from source and add `console.log('java ' + args.join(' '));` to
> 
> https://github.com/reisxd/revanced-builder/blob/5ef8ce3e81aa3fd69f811c622726a8d400045cb8/wsEvents/PatchApp.js#L239
> 
> And send the output here.

![image](https://user-images.githubusercontent.com/13099434/185896437-9fc0f4c1-ea9c-4ef2-9a53-67352c64394d.png)

**Comment by reisxd** [comment]
> > Run from source and add `console.log('java ' + args.join(' '));` to
> > https://github.com/reisxd/revanced-builder/blob/5ef8ce3e81aa3fd69f811c622726a8d400045cb8/wsEvents/PatchApp.js#L239
> > 
> > And send the output here.
> 
> ![image](https://user-images.githubusercontent.com/13099434/185896437-9fc0f4c1-ea9c-4ef2-9a53-67352c64394d.png)

That's not something related to this issue. You have to downgrade and therefore, not an issue with Builder.

**Comment by ifelixculpa** [comment]
> > > Run from source and add `console.log('java ' + args.join(' '));` to
> > > https://github.com/reisxd/revanced-builder/blob/5ef8ce3e81aa3fd69f811c622726a8d400045cb8/wsEvents/PatchApp.js#L239
> > > 
> > > And send the output here.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/13099434/185896437-9fc0f4c1-ea9c-4ef2-9a53-67352c64394d.png)
> 
> That's not something related to this issue. You have to downgrade and therefore, not an issue with Builder.

downgrade yt version sir ?

**Comment by adhammagdy** [comment]
> Run from source and add `console.log('java ' + args.join(' '));` to
> 
> https://github.com/reisxd/revanced-builder/blob/5ef8ce3e81aa3fd69f811c622726a8d400045cb8/wsEvents/PatchApp.js#L239
> 
> And send the output here.

I'm sorry don't know how to do this.. I'm not a programmer

**Comment by shrihanDev** [comment]
At the moment, Arabic and other RTL languages aren't supported. No plans to do it either (unless an Arabic does a PR)
