### ISSUE TITLE
Does not install three patches in version 17.33.35

### ISSUE THREAD

**Issue by DrimTim2020** [reisxd/revanced-builder#279]
After downloading the youtube_17.33.35 file in the program 
I clicked continue selecting the appropriate patches again clicked continue and the build followed.
During the assembly process, red lines with errors of some patches began to run.
![1](https://user-images.githubusercontent.com/65110869/185762422-896d8995-dd92-47a0-8ecc-b586089bb8f3.jpg)
![2](https://user-images.githubusercontent.com/65110869/185762429-5ec5d8a9-8cae-4514-94c2-effe6d9ce43e.jpg)
![3](https://user-images.githubusercontent.com/65110869/185762430-44f2cf92-4410-4136-9be5-c2fb3fe5949f.jpg)

I tried to build the package several times, the same errors!

**Comment by reisxd** [comment]
The tool warns you that these are betas and aren't stable, and you still choosed them. Not an issue with Builder anyway.
