### ISSUE TITLE
root variant doesn't work

### ISSUE THREAD

**Issue by Scarpy19** [reisxd/revanced-builder#28]
I'm using the noob way.
It keeps "Building ReVanced, please be patient!" and never end.

On the phone, Youtube opens and it keeps saying "Root permisions allowed to Shell"

![image](https://user-images.githubusercontent.com/63962989/177428992-ae92d134-4e02-41fa-bc94-15f5f7c75587.png)

![Imagen de WhatsApp 2022-07-06 a las 00 38 51](https://user-images.githubusercontent.com/63962989/177428891-0fd5af71-735b-4870-9a58-65605b5b7453.jpg)

**Comment by CnC-Robert** [comment]
The reason the installer doesnt continue is because it logs the application until you close the application, which is why you see the root granted message. You also propably have excluded every patch which is why you still see ads.

**Comment by Scarpy19** [comment]
i only excluded microg-support and hide-cast-button

**Comment by TgSeed** [comment]
I don't have this issue but here are some steps that might fix your problem:

1. Download [SDK Platform Tools](https://dl.google.com/android/repository/platform-tools_r33.0.2-windows.zip).
2. Create a folder in C:\ named adb.
3. Extract the downloaded zip content in C:\adb
4. [Add the folder to your windows path variable](https://stackoverflow.com/a/44272417)
5. Close all shells/revanced-builder and try to run revanced-builder again.
