### ISSUE TITLE
Error relating to node binary

### ISSUE THREAD

**Issue by dmccue** [reisxd/revanced-builder#280]
CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node" ...

Android 12 - Termux

**Comment by reisxd** [comment]
Reinstall NodeJS using `pkg uninstall nodejs && pkg install nodejs`

**Comment by katherinehackworth** [comment]
I resolved this by installing the version of termux off of droid and not the play store because the play store version is over two years out of date

**Comment by dmccue** [comment]
> I resolved this by installing the version of termux off of fdroid and not the play store because the play store version is over two years out of date. I was getting errors even just trying to uninstall node before I did that

Tried the F-Droid version with no luck, had to get the apk from github releases and it works flawlessly after a `pkg upgrade`:
https://github.com/termux/termux-app/releases
