### ISSUE TITLE
Crash on the Warnwetter version selecting screen

### ISSUE THREAD

**Issue by Frosty-Nr1** [reisxd/revanced-builder#285]
**Describe the bug**
Builder gets an error when i am supposed to select the version of warnwetter i want to patch.

1. Start Builder
2. Click on 'Warnwetter'
3. Select all Patches

**Screenshots**
![image](https://user-images.githubusercontent.com/102326850/185847445-85a25f07-cea6-43e5-a676-b0c8308c9360.png)

**revanced-builder Version: 3.2.3

- OS: Windows
- Version: 10 Pro

**Additional context**

**Comment by reisxd** [comment]
This is already fixed but a release hasn't been released yet. Will close when I create a new release.
