### ISSUE TITLE
Amoled dark mode can't be disabled

### ISSUE THREAD

**Issue by Jangsoodlor** [reisxd/revanced-builder#288]
**Describe the bug**
Amoled dark mode cannot be disabled even though you deselected it

**To Reproduce**
1. deselect amoled
![img1](https://i.imgur.com/rrNtHRk.png)
![img2](https://i.imgur.com/uv3USJT.png)

2. somehow the builder still builds amoled patch
![img3](https://i.imgur.com/R0srgKm.png)

3. the result
![img4](https://i.imgur.com/hjToToD.png)

**revanced-builder Version:** 3.2.4 (latest)

**Device Information**

- OS: Android 11
- Non-rooted
- YouTube version: 17.32.39

**Additional context**
This also happens with older version of the builder (last release) and with different web browser.

**Comment by reisxd** [comment]
Cannot reproduce.

![Screenshot_2022-08-22-16-59-11-932_com.android.chrome.jpg](https://user-images.githubusercontent.com/29177546/185939559-01111129-8396-41ab-88e2-1b07d9a33261.jpg)
