### ISSUE TITLE
Videos don't load/video stops randomly (sound continues to play)

### ISSUE THREAD

**Issue by TgZ39** [reisxd/revanced-builder#290]
**Describe the bug**
Sometimes when clicking on a video it doesn't load (it isn't am Internet issue,I have a 100mb connection), also sometimes when the video plays the video just stops but the audio still continues.

**To Reproduce**

**Screenshots**
![Screenshot_20220822-201023.jpg](https://user-images.githubusercontent.com/71944761/185990609-68954185-70f3-41b0-8a74-25b2bf920c1f.jpg)

**revanced-builder Version:** [latest]

**Desktop (please complete the following information):**

- OS: [Windows]
- Version: [11]

**Comment by TgZ39** [comment]
Version 3.4.2

**Comment by reisxd** [comment]
Not an issue with Builder, make an issue in revanced/revanced-patches.
