### ISSUE TITLE
Old code in function.

### ISSUE THREAD

**Issue by laltroweb** [reisxd/revanced-builder#292]
```
[revanced-builder] Downloading revanced-builder...

[revanced-builder] Unzipping...

mv: cannot move 'revanced-builder-main/.' to './.': Device or resource busy

mv: cannot move 'revanced-builder-main/..' to './..': Device or resource busy

[revanced-builder] Installing packages...
```

This is caused by this:
https://github.com/reisxd/revanced-builder/blob/main/android-interface.sh#L47
++
https://github.com/reisxd/revanced-builder/blob/main/android-interface.sh#L50

**Comment by reisxd** [comment]
@shrihanDev Can you fix this whenever you're free? No pressure, take your time.

**Comment by TgZ39** [comment]
> @shrihanDev Can you fix this whenever you're free? No pressure, take your time.

Why tf are you deleting my posts
