### ISSUE TITLE
Termux error

### ISSUE THREAD

**Issue by HavaliRumuz** [reisxd/revanced-builder#293]
![Screenshot_2022-08-22-22-21-19-200_com termux](https://user-images.githubusercontent.com/68316278/186001926-9675794a-55f9-4c51-9b37-00cfa869ae06.jpg)

**Comment by reisxd** [comment]
I only get this error when I'm using data and most of the time, it magically fixes itself. Use a VPN or change your DNS or even simpler, refresh the page until it works.

**Comment by HavaliRumuz** [comment]
İ don't use Vpn or DNS.

**Comment by HavaliRumuz** [comment]
İ used Vpn and solved. Thanks
