### ISSUE TITLE
[Wiki] How to use revanced builder on Android

### ISSUE THREAD

**Issue by iam0day** [reisxd/revanced-builder#295]
In my opinion, it is not necessary to install FDroid to get Termux, just refer directly to [this link](https://f-droid.org/repo/com.termux_118.apk) or to [GitHub releases](https://github.com/termux/termux-app/releases/tag/v0.118.0) 😆

**Comment by reisxd** [comment]
What if Termux gets updated and that link gets useless? And for the GH solution, users might get confused because they might not know which APK to install.

**Comment by iam0day** [comment]
> What if Termux gets updated and that link gets useless?

If it is a user who already uses Termux, I don't think we have to consider whether he keeps the application up-to-date, but if the user installs Termux just because he needs it for ReVanced, it is the same, because he will still see that an update of the application is available regardless.

> And for the GH solution, users might get confused because they might not know which APK to install.

In reality, the "latest" version is not very confusing.
