### ISSUE TITLE
Error when building ReVanced ROOT

### ISSUE THREAD

**Issue by 1RandomDev** [reisxd/revanced-builder#297]
**Describe the bug**
When trying to install ReVanced ROOT I get the following error:
```
[builder] An error occured.
Error: Command failed: su -c 'base_path="/data/adb/revanced/com.google.android.youtube.apk" && mv "/data/local/tmp/revanced.delete" "$base_path" && chmod 644 "$base_path" && chown system:system "$base_path" && chcon u:object_r:apk_data_file:s0  "$base_path"'
mv: bad '/data/local/tmp/revanced.delete': Device or resource busy
    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**To Reproduce**
- Start service in Termux
- Go to webinterface
- Build and install ReVanced

**Screenshots**
Error message should be enough.

**revanced-builder Version:** Latest commit I guess (842d3a02a84a9b436c8cd6c2de0a4eee1f6b7239)

**Desktop (please complete the following information):**

- OS: Android
- Version: 12

**Additional context**
-

**Comment by reisxd** [comment]
Try again.

**Comment by 1RandomDev** [comment]
Nope same problem :C
