### ISSUE TITLE
revanced-builder doesn't like downloading newer APKs.

### ISSUE THREAD

**Issue by reisxd** [reisxd/revanced-builder#30]
I have no idea why does this happen, but I need help. This happened to me before, trying to download an beta apk would cut at 119MB and wouldn't download completely. I made it only download stable APKs until today, a new update to YouTube and APKMirror releasing it. Now this time, it cuts at 123MB. I really have no idea and any help would be appreciated.

**Comment by DrimTim2020** [comment]
> Now this time, it cuts at 123MB.

Yes, it really loads 123 mb for some reason. 
And on the APKMirror website, the file is 131 mb in size.

**Comment by DrimTim2020** [comment]
For a long time I did not have to look for the reason why a file with a size of 123 mb is being loaded. ))).
The file that downloads revanced-builder v1.2.4 from the site ( APKM ) , it simply renames it to ( APK ) .

**Comment by reisxd** [comment]
So, I found the issue.
APKMirror links have changed after 17.25.34 (or 17.26.34 Beta). The link its scraping redirects to the normal APK in version 17.25.34 and before but after it, it changed links. 
The difference: 
17.25.35, the bundle one:
![image](https://user-images.githubusercontent.com/29177546/177526090-0ed743c2-8a9a-45be-884b-393fa6e7d2b1.png)
the normal one:
![image](https://user-images.githubusercontent.com/29177546/177526135-1ffa6d4d-6791-4c36-9c01-29bec7148998.png)
17.25.34, the bundle one:
![image](https://user-images.githubusercontent.com/29177546/177526239-190984ec-b17f-4013-ade8-dcf4ae948e63.png)
the normal one:
![image](https://user-images.githubusercontent.com/29177546/177526311-92d774de-dffd-4606-af8b-fdbdd2736c0e.png)

**Comment by sebastianjena** [comment]
@reisxd I have the same issue on latest version
![image](https://user-images.githubusercontent.com/9075924/185484715-4bac63d7-21eb-48a2-b5ac-ea724d6a3d3f.png)
