### ISSUE TITLE
Detailed instructions please 

### ISSUE THREAD

**Issue by AmirulAndalib** [reisxd/revanced-builder#31]
Can you please add detailed instructions and develope a workflow for this

**Comment by DrimTim2020** [comment]
Instructions for what?

**Comment by reisxd** [comment]
> Can you please add detailed instructions and develope a workflow for this

Run the executable file, do what it says, select the patches, the youtube version and wait.

**Comment by AmirulAndalib** [comment]
Can you develope a workflow for this With instructions

Thank you
