### ISSUE TITLE
android doesn't work

### ISSUE THREAD

**Issue by ffoxD** [reisxd/revanced-builder#310]
**Describe the bug**
Any time I attempt to compile on Android, it eventually ends with an error leaving behind only the raw APK.
I've tried reinstalling everything and using pkg upgrade, didn't help.
Also, for some reason, using the cli version with the old tutorial will successfully compile an apk, so it might be a problem with the web UI? (Also tbh having a web UI is just stupid and also android keeps killing termux because it runs in the background and it's just so frustrating and sluggish and much harder to use than just pressing enter on the cli)

**To Reproduce**
Follow the guide for compiling on Android, it always ends with this error

**Screenshots**
![Screenshot_2022-08-24-21-39-15-685_org mozilla firefox](https://user-images.githubusercontent.com/67541651/186539099-90011aaa-339f-40b2-b39f-507188b66043.jpg)
![Screenshot_2022-08-24-21-39-36-445_org mozilla firefox](https://user-images.githubusercontent.com/67541651/186539142-1b0dcb4b-2da8-41d6-9d55-08a776d6385d.jpg)
![Screenshot_2022-08-24-21-39-27-696_org mozilla firefox](https://user-images.githubusercontent.com/67541651/186539176-dde36519-19d9-4935-94b5-26800a79d6bd.jpg)

**Comment by reisxd** [comment]
Won't fix, because the actual is unknown.
