### ISSUE TITLE
Error Cannot read properties of undefined in C:\Snapshot

### ISSUE THREAD

**Issue by OlDelCacho** [reisxd/revanced-builder#315]
Hello,

I've a problem with Revanced 3.3.0, I was just using the version before while you uploaded the update.
I was relaunching the compilation of YT and had this error while downloading the dependencies

Am on Win 10 x64 latest
Here's the log below

[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done. Check if a browser window has opened
GET / 304 3.557 ms - -
GET /styles/fontawesome.css 304 6.248 ms - -
GET /styles/core.css 304 7.141 ms - -
GET /styles/apps.css 304 7.055 ms - -
GET /index.js 304 6.661 ms - -
GET /colors.js 304 0.902 ms - -
GET /webfonts/fa-brands-400.woff2 304 1.151 ms - -
GET /webfonts/fa-solid-900.woff2 304 1.284 ms - -
GET /dependencies/ 304 1.804 ms - -
GET /styles/fontawesome.css 304 5.915 ms - -
GET /styles/core.css 304 5.347 ms - -
GET /styles/dependencies.css 304 5.504 ms - -
GET /index.js 304 6.047 ms - -
GET /colors.js 304 1.940 ms - -
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'includes')
    at C:\snapshot\revanced-builder\utils\checkJDKAndADB.js:44:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UpdateFiles (C:\snapshot\revanced-builder\wsEvents\UpdateFiles.js:49:5)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:119:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by reisxd** [comment]
Fixed in the latest release.
