### ISSUE TITLE
hide-cast-button

### ISSUE THREAD

**Issue by DrimTim2020** [reisxd/revanced-builder#32]
Should the Cast button be displayed at all on a device without Root?
I tried two options to collect in none of them it is displayed.
Device - Poco X3 Pro  Android 12  MIUI13
Root - No
Although in the original YouTube, the Cast button is displayed!

**Comment by reisxd** [comment]
The cast button depends on the microg-support patch, you'll need to exclude the microg-support and build the rooted version.
