### ISSUE TITLE
Script runs out of memory

### ISSUE THREAD

**Issue by mik111111** [reisxd/revanced-builder#320]
**Describe the bug**
The script runs out of memory 

**To Reproduce**

1. Run the script
2. Select Reddit
3. Select the general ads patch

**revanced-builder Version:**
v3.3.1

**Desktop:**

- OS:Windows 10 Pro
- Version: 21H2
- Ram: 16GB

**Additional context**
The computer it self dosent run out of memory but the script reaches the memory limit.

![Screenshot 2022-08-25 160113](https://user-images.githubusercontent.com/109052896/186685446-2e649cab-f957-49c0-b2e1-6d4aa249f589.png)

**Comment by GTABossMDS** [comment]
Yes I have the same problem as well. I have 32GB RAM and total RAM used was only 8GB when using the builder.
