### ISSUE TITLE
error while patching youtube 

### ISSUE THREAD

**Issue by vo1d-7bin** [reisxd/revanced-builder#322]
![image](https://user-images.githubusercontent.com/100482403/186732136-dd010514-a441-4196-b048-e03f48140b03.png)

**Comment by reisxd** [comment]
Made a new release to see what's actually happening in the back and to fix the issue.

**Comment by reisxd** [comment]
Closing because this issue occurs randomly and when I tried to reproduce, it would work and not display that message.
