### ISSUE TITLE
YT Music crashing right after launching

### ISSUE THREAD

**Issue by StoneyTBoI** [reisxd/revanced-builder#324]
**Describe the bug**
Music ReVanced Crashing on Startup (both Arm64 and Arm32)

**To Reproduce**

1. Build using the ReVanced Builder on PC (in my case Windows 10)
2. Build YouTube Music ReVanced (I am using every Patch, YTM Version 5.21.51)
3. Launch the App after installing it and MicroG
4. Crash on Startup, everytime

**Screenshots**
I don't have Screenshots but I have Stacktraces that my ROM made after the App crashed multiple times:

https://paste.evolution-x.org/rRXZX9 (Arm64)
https://paste.evolution-x.org/rBN72I (Arm32)

**revanced-builder Version:** [e.g. v3.3.2]

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10 Pro

**Additional context**
YouTube ReVanced itself works without any issues whatsoever

**Comment by reisxd** [comment]
Use an older version, like 5.16.64
