### ISSUE TITLE
client spoof patch is listed twice

### ISSUE THREAD

**Issue by masterflitzer** [reisxd/revanced-builder#326]
**Describe the bug**
the client spoof patch is listed twice in http://localhost:8000/patches

**To Reproduce**
start the builder, wait for website to open, navigate until you see list of patches 

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/60170948/187019093-560ee4bf-eee1-4e99-abd1-a59814c75a6f.png)

**revanced-builder Version:**
latest main.zip at time of writing (I think v3.3.2)

**Desktop (please complete the following information):**

- OS: Android
- Version: 12 (One UI 4.1)

**Additional context**

**Comment by TgZ39** [comment]
Also happends in Windows version

**Comment by masterflitzer** [comment]
thx for the quick fix, but wouldn't it be a better solution to make a distinct list of patches and then iterating over it rather than hard coding "client spoof"? so similar bugs won't happen in the future (if another patch happens to show multiple times)?

**Comment by reisxd** [comment]
> thx for the quick fix, but wouldn't it be a better solution to make a distinct list of patches and then iterating over it rather than hard coding "client spoof"? so similar bugs won't happen in the future (if another patch happens to show multiple times)?

This isn't really an Builder issue, because the `client-spoof` is also compatible with Vanced, this occurs. The patch in CLI gets duplicated and because of both of them having a package name that ends with `youtube`, again, this occurs.

**Comment by masterflitzer** [comment]
thx for clarifying, but wouldn't it be possible for other patches to also get duplicated in the future (if they're also compatible with vanced or some other reason)? if so it would maybe still be a good idea to make a general solution

**Comment by reisxd** [comment]
> thx for clarifying, but wouldn't it be possible for other patches to also get duplicated in the future (if they're also compatible with vanced or some other reason)? if so it would maybe still be a good idea to make a general solution

It is, but currently that's the only package to get duplicated (other than the T*kTok patch, which isn't an problem because the package name ends differently) so, I'm kinda too lazy lol.

**Comment by masterflitzer** [comment]
fair enough, if you're open to PRs I'll make one later when I have time

quick question, does TT need to be censored?

**Comment by reisxd** [comment]
> fair enough, if you're open to PRs I'll make one later when I have time
> 
> quick question, does TT need to be censored?

Nah lol, I just hate TikTok.

**Comment by masterflitzer** [comment]
sorry for opening a non-working PR before, i didn't test it enough (and i had no experience with the return type of matchAll)

this should work 100% now
