### ISSUE TITLE
Twitter build error

### ISSUE THREAD

**Issue by Myouboku** [reisxd/revanced-builder#329]
I get an error when I try to build the patched Twitter, this one is different since the last update but I don't remember what is was before.

This problem occurred simply when I select Twitter from the app list, select the patch and at the end there is an error at the initialization of the build.

Screenshot :
![image](https://user-images.githubusercontent.com/71690611/187034298-a06116a8-1f19-4c86-8dd1-b8391e893621.png)

Version : 3.3.3
OS: Windows 10 21H2

**Comment by reisxd** [comment]
You need at least 2GBs of ram empty.

**Comment by Myouboku** [comment]
I saw that, but I got 11GB of free ram at this moment

**Comment by reisxd** [comment]
![image](https://user-images.githubusercontent.com/29177546/187035499-7d4a0d3e-fd2d-4bf0-ab84-6f9e99dd7481.png)
I can only guess you don't have any free space then.

**Comment by Myouboku** [comment]
Space currently available on my system : 
![image](https://user-images.githubusercontent.com/71690611/187035589-67c7e1f2-ffed-4be6-b258-b94516659b89.png)

Also, I think I remember the previous problem I encountered, that was about a Java argument not set properly, something like "-Xmx=4G", this is the Java version I use : 
![image](https://user-images.githubusercontent.com/71690611/187035673-12a6dceb-af32-4ed0-b4d9-46414528e3c5.png)
Maybe that's part of the issue, I don't know.

I don't encounter any error with other builds, that's why I opened this github issue.

**Comment by Myouboku** [comment]
Update : other patches doesn't build anymore, problem must come from myself, sorry to have opened this issue.
