### ISSUE TITLE
Revanced Builder is not mounting YouTube Music 

### ISSUE THREAD

**Issue by Foxlass** [reisxd/revanced-builder#332]
**Describe the bug**

**To Reproduce**

1. Attempt to build ReVanced Music as normal
2. Select any version 
3. While building, ReVanced Builder fails to mount.
4. Read the error in Termux.

**Screenshots**
![Screenshot_20220828-140647](https://user-images.githubusercontent.com/53279832/187089837-e079203f-77a8-4a6b-9fd2-aa108108696b.png)

**revanced-builder Version:** ReVanced Builder v3.3.3

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**

I am using Android, not desktop. Termux is fully updated along with the builder. I have already tried the solution listed previously (install the stock app first) and it does not work for me, even if the versions match perfectly. I update the app to v5.17.51, select that version in the builder, and then the issue still persists.

**Comment by Rikysonic** [comment]
I had a similar problem some time ago, try to delete the `revanced.delete` file in `/data/local/tmp` using a root file explorer or running these commands in Termux:
```su
rm /data/local/tmp/revanced.delete```
Then reboot the device and finally try again with the patching process

**Comment by erenmete** [comment]
reboot your phone, update or install the stock yt music then rerun the revanced builder
