### ISSUE TITLE
reVanced Builder: remember reviously used patches

### ISSUE THREAD

**Issue by SubZero5** [reisxd/revanced-builder#335]
I think the patches page should remember and have a select the last used patches button next to the select all/none buttons and choose to be included patches via a `.revanced_builder` file or via browser cookies.

**Comment by reisxd** [comment]
Builder already does this.

**Comment by masterflitzer** [comment]
> patches page should remember

@SubZero5 like reisxd said it's already implemented

idk about your workflow but if you are like me and redownload the whole thing each time, you might want to do backup the file `includedPatchesList.json`

you can take a look at my simple script which backs up keystore and selected patches: https://gist.github.com/masterflitzer/bd25006d3e0a35a5090987c954bc586a
