### ISSUE TITLE
Problems downloading resources behind a proxy

### ISSUE THREAD

**Issue by xmun2k** [reisxd/revanced-builder#336]
**Description**
On Windows, the application is unable to download resources when the Internet connection is behind a proxy.

Follow the steps to build Youtube Revanced.
In the console the following error appears:

FetchError: request to https://api.github.com/repos/revanced/revanced-cli/releases/latest failed, reason: connect ETIMEDOUT 140.82.121.6:443

**revanced-builder Version:** 3.3.3

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Additional context**
The system is configured to use a proxy server to connect to the internet.
Also, environment variables "HTTP_PROXY=" and "HTTPS_PROXY=" are configured and assigned to the correct URL.

**Comment by masterflitzer** [comment]
maybe [this](https://stackoverflow.com/a/2966629)  helps, but i didn't try it out

according to this, java needs _JAVA_OPTIONS and doesn't honor HTTP_PROXY
