### ISSUE TITLE
Stuck on building YTmusic revanced

### ISSUE THREAD

**Issue by androidghosh** [reisxd/revanced-builder#340]
**Describe the bug**
Stuck on apk selection page

**To Reproduce**
1. Started from the normal process, changed the colour to red and selected these options,
![image](https://user-images.githubusercontent.com/17355109/187418558-aa68c494-8efa-46b3-91a7-f000c498d5a8.png)
![image](https://user-images.githubusercontent.com/17355109/187418576-4d295af0-8f40-4028-917c-08e460f73bfc.png)

2. Selected the 5.17.51 version and armv8 arc.
3. Clicked continue, but no response. The page is stuck there.

**Screenshots**
### Its stuck here
![image](https://user-images.githubusercontent.com/17355109/187418480-2ac37b70-0c1d-4c96-aa7c-611bef96e831.png)

**revanced-builder Version:** [e.g. v3.3.6]

**Desktop (please complete the following information):**

- OS:  Windows 10 

**Additional context**
I never faced any problem in the past building revanced-youtube in my same pc.

**Comment by ComGreed** [comment]
Error in JS check if version is beta or not recommended.
I had to edit the JS in Edge to get past that check.
To find the relevant line check debug console in your browser.
