### ISSUE TITLE
Do you have hobbies?

### ISSUE THREAD

**Issue by TgZ39** [reisxd/revanced-builder#345]
Like what, how do you pump out release after release like in a 2 hour schedule. I don't get, don't you touch grass sometimes or do human interaction? Or have hobbies? Very respectful work that you do here btw, have my honor...

**Comment by KiGamji** [comment]
> don't you touch grass sometimes

Sadly, no. But he will, I swear.

**Comment by PandoraHayami** [comment]
> > don't you touch grass sometimes
> 
> Sadly, no. But he will, I swear.

Probably, let's hope

**Comment by reisxd** [comment]
bruh yall 💀

**Comment by reisxd** [comment]
Basically, I'm just a 14 y.o coder who just wants to get rid of his boredom.
