### ISSUE TITLE
Can't build any APKs

### ISSUE THREAD

**Issue by Emerald-Fox** [reisxd/revanced-builder#346]
**Describe the bug**
Can't build any APKs with the following error in the log:
[builder] Exception in thread "main"
[builder] java.lang.OutOfMemoryError: Java heap space
[builder] at java.base/java.util.Arrays.copyOf(Arrays.java:3537) at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61) at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9) at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49) at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
[builder] at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354) at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301) at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148) at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92) at lanchon.multidexlib2.DexIO$$Lambda$82/0x179089d0.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[builder] at java.base/java.lang.Thread.run(Thread.java:833)

**To Reproduce**
Simply try to build any patched APK

**Screenshots**
![image](https://user-images.githubusercontent.com/54197891/187614957-316f80d9-38ef-496e-badb-4d0b75e4edbc.png)

**revanced-builder Version:**
v3.3.7

**Desktop**

- OS: Windows
- Version: 11 Home

**Additional context**
I'm using the latest version of revanced-builder, Zudo JDK 17, and Chrome browser

**Comment by masterflitzer** [comment]
> OutOfMemoryError: Java heap space

i guess you're out of memory (maybe check how much RAM you have available)

**Comment by git-Hmmm** [comment]
working fine for me!
![image](https://user-images.githubusercontent.com/102938585/187746145-ffe4f87f-f240-42b2-be9a-111f447677ca.png)

**Comment by Emerald-Fox** [comment]
Hmm, I'll try changing my default browser to Firefox and see if that helps? I'd imagine 16GB of RAM is enough for using revanced-builder ~~unless for whatever reason I need an ultra high end PC with like 128GB of RAM lol~~

**Comment by masterflitzer** [comment]
I don't think the browser will change anything, the cli is what's running on java

**Comment by Fooftilly** [comment]
Are you using azul zulu 17 java? if not, You need to install it and add it to the path before running the builder. I've had simular error and that fixed it for me.

**Comment by Fooftilly** [comment]
If you have two java jdks installed you would need to run 
`export PATH=/usr/lib/jvm/zulu-17/bin:$PATH`
if you are on linux or something from this if you are on Windows https://stackoverflow.com/questions/14224756/window-add-java-to-path
You can check which java you are running by typing in ` which java ` in console.

**Comment by Emerald-Fox** [comment]
I'll try figure out the path thing for Windows, it's probably because I just woke up but it's a bit confusing to read.

**Comment by Fooftilly** [comment]
You could probably use path/to/zulu/java.exe revanced-cli.jar instead of just typing java revanced-cli.jar and continuing the steps in documentation. I think that works in Windows.

If found this suggestion on discord: "C:\Program Files\Zulu\zulu-17\bin\java.exe" -jar revanced-cli.jar ..."

**Comment by masterflitzer** [comment]
> "C:\Program Files\Zulu\zulu-17\bin\java.exe" -jar revanced-cli.jar ..."

when using powershell this would not work as a string needs to be executed with the call operator (&)

powershell: `& "C:\Program Files\Zulu\zulu-17\bin\java.exe" -jar revanced-cli.jar` ...
