### ISSUE TITLE
ABD not detected

### ISSUE THREAD

**Issue by MrMayo101** [reisxd/revanced-builder#350]
**Describe the bug**
my phone have magisk in it but this happens when i try to do root build

**Screenshots**
![image](https://user-images.githubusercontent.com/88887227/187805459-be98ccfd-bb16-4815-9f1d-ae85146578a1.png)

**revanced-builder Version: 3.3.7

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Comment by reisxd** [comment]
You have to give root access to ADB shell on your device.

**Comment by eEQK** [comment]
I get the same error despite exporting adb path correctly:
```shell
export PATH=$PATH:~/dev/Android/platform-tools; ~/Downloads/revanced-builder-nodejs-macos
```

```
❯ adb --version
Android Debug Bridge version 1.0.41
Version 33.0.2-8557947
Installed as /Users/redacted/dev/Android/platform-tools/adb
```
