### ISSUE TITLE
Suggestion: Exit page after tapping 'Quit'

### ISSUE THREAD

**Issue by arshit09** [reisxd/revanced-builder#351]
ReVanced v3.3.7

It would be good if there's an exit page after tapping on 'Quit' button after building instead of showing this process,
![Screenshot_20220831-202131](https://user-images.githubusercontent.com/31356599/187807530-9bf41164-ee3d-434d-9b65-5e0d790e872e.png)

**Comment by masterflitzer** [comment]
i also thought about opening this issue, i'd like this feature
