### ISSUE TITLE
Suggestion: Minor Improvement on guiding naive users

### ISSUE THREAD

**Issue by arshit09** [reisxd/revanced-builder#352]
ReVanced v3.3.7

It would be a great to add like guiding path to add one line like "Press 'Continue' to proceed" or something after downloading finishes.
![Screenshot_20220831-201939](https://user-images.githubusercontent.com/31356599/187807805-c3cf70c5-c120-446f-b358-f16734eb8dc9.png)

**Comment by masterflitzer** [comment]
or maybe hide continue button until download completes (it's hard to see when it becomes enabled), when the button is suddenly there you know it is finished

**Comment by arshit09** [comment]
> or maybe hide continue button until download completes (it's hard to see when it becomes enabled), when the button is suddenly there you know it is finished

Oh yes! this is actually a good solution!
