### ISSUE TITLE
Can't pick YT version on Windows ver.

### ISSUE THREAD

**Issue by gemerfoxy** [reisxd/revanced-builder#353]
**Describe the bug**
Can't pick YT version on Windows version, while on Android ones, we can pick any version.

**To Reproduce**

1. Run the app
2. Pick "Youtube" then click Continue
3. Wait for patches to download then click Continue
4. Pick any patches then click Continue

**Screenshots**
![image](https://user-images.githubusercontent.com/25972975/187819472-62a077fc-f8a7-4d42-b0b5-c6b7d45c7df6.png)

**revanced-builder Version: 3.3.7** 

**Desktop:**

- OS: Windows 11 build 25188

**Expected result:**
I can pick version like on android ones

**Comment by reisxd** [comment]
Not a bug but intended behaviour on rooted builds.
