### ISSUE TITLE
Need Offline Mode

### ISSUE THREAD

**Issue by nity19981222** [reisxd/revanced-builder#363]
I'm from mainland China,in my region apkmirror  is blocked while github is sometimes disconnected.However,using proxy to acess bring lots of certificate problem（pic1),or stuck in apkmirror youtube version selected or downloading depenedcies（pic2).
Usually，i download github files by using mirrors of github ;Latest Android application like youtube in some our own network disk service shared by users,
So i'm wondering that if you can add a "offline mode":allow us to put right needy depenedcies and youtube application in "revanced" file folder and patch the application offline rather than downloading and select it online all the time .Or may be we can edit the source to add the mirror of github and the website of Android application downloading.
Thank for your excellent development to  make "revanced" easier
![pic1](https://user-images.githubusercontent.com/34953624/188065549-a9fc7f21-8491-4fec-a30e-b0cefd520ad6.png)
![pic2](https://user-images.githubusercontent.com/34953624/188065566-2b610c62-9b91-4b63-8d29-33b4ff08d32c.png)

**Comment by git-Hmmm** [comment]
as a workaround you can put a file named youtube.apk in builder-folder/revanced/youtube.apk

**Comment by TgZ39** [comment]
what does bagmeningong mean?
