### ISSUE TITLE
Auto- f***ing Update

### ISSUE THREAD

**Issue by TgZ39** [reisxd/revanced-builder#367]
Would be a great feature. An update button

**Comment by ActuallyTheSun** [comment]
Depends on what you mean by "update button".
- For revanced or any other patched app, where an update via button would still require a rebuild, would require manually picking a new youtube version, picking some of the new patches, which at that point just go through the build process again
- For the builder itself, which should already have a new update notice, where on desktop you just agree and on mobile you run `./revanced-builder.sh update`
