### ISSUE TITLE
Android Tools failed for revanced root

### ISSUE THREAD

**Issue by likkai** [reisxd/revanced-builder#368]
**Describe the bug**
Follow by the latest update of the builder, building revanced root (on Android) can no longer select YouTube version manually. The tool also failed to identify the correct version of YouTube and installed the incorrect version of revanced patch, causing YouTube app to crash every time. 

**To Reproduce**
Nothing special, just go through normal process. The patching process will complete but after restarting device (required for root build), YouTube crash every time. 

**Screenshots**
No screenshot. 

**revanced-builder Version:** 
v3.3.7

**Android (please complete the following information):**
- MIUI 13 (Android 12)

**Additional context**
Unable to fallback to previous version of builder from the command line, it automatically fetch the latest version. Please implement the feature that will allow root built revanced to select YouTube version manually.

**Comment by reisxd** [comment]
Downgrade to 17.33.XX and 

> Follow by the latest update of the builder, building revanced root (on Android) can no longer select YouTube version manually

This is a normal behaviour. Builder automatically gets the version you have on your device to avoid some issues in the future.

**Comment by likkai** [comment]
When will YouTube 17.34.X be compatible? Is it a builder issue or YouTube revanced issue?

**Comment by reisxd** [comment]
> When will YouTube 17.34.X be compatible? Is it a builder issue or YouTube revanced issue?

Not an builder but the patches aren't incompatible. IIRC 17.34.XX is also beta, and ReVanced will never support beta versions.

**Comment by likkai** [comment]
It's weird that Google play store sends me the update even though I didn't opt in for beta. 
Thanks for the help

**Comment by jagjordi** [comment]
I am getting the same problem with youtube version 17.33.42. Any ideas?
