### ISSUE TITLE
The Videos from playlist on yt revanced doesn't open 

### ISSUE THREAD

**Issue by Alexandrus01** [reisxd/revanced-builder#371]
The videos on YouTube revanced from the playlist do not open, and have unlimited buffering only when clicking on the thumbnail Video. When opening from the playlist name, the video starts normally. Also after opening from the playlists name, all other playlists open normally. When opening the app again, the bug occurs again.
Os: Android 12, OneUi 4.1 Samsung A52S
Yt Revanced version: 17.33.42

**Comment by reisxd** [comment]
Not an issue with Builder.
