### ISSUE TITLE
If the path to the executable file contains non-ASCII characters in Windows, an error "Required file not found" will occur when applying the patch.

### ISSUE THREAD

**Issue by Vivilet** [reisxd/revanced-builder#374]
**Describe the bug**
If the path to the executable file contains non-ASCII characters in Windows, an error "Required file not found" will occur when applying the patch.

**To Reproduce**

1. Copy the executable file to a folder whose name contains non-ascii characters (😊, フォルダ, etc.)
2. Run the copied file
3. Select patches and other items to proceed
4. Errors occur when trying to process a path, such as reading a file

**revanced-builder Version: 3.3.7**

**Desktop:**

- OS: Windows
- Version: 10

**Additional context**
This is my first time to set up an issue and I used a machine translation, so something might be wrong.

Thanks for reading.

**Comment by shrihanDev** [comment]
File name entries with non-ASCII characters in them are usually a hit-and-miss for numerous programs. The upstream ReVanced CLI doesn't quite support it either, so no chance of doing it here.
