### ISSUE TITLE
Fetch error on start of builder

### ISSUE THREAD

**Issue by misikovich** [reisxd/revanced-builder#375]
**Describe the bug**
When program starts, java throws an TypeError

**To Reproduce**

2. Click on 'revanced-builder-nodejs-win.exe'

**Screenshots**
Screenshot:
https://prnt.sc/8N3vcyuWrG2v
https://pastebin.com/ky3s91Fw

**revanced-builder Version:** 
revanced-builder Version: 3.4.0

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Additional context**
openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment Zulu17.36+19-CA (build 17.0.4.1+1-LTS)
OpenJDK Client VM Zulu17.36+19-CA (build 17.0.4.1+1-LTS, mixed mode, emulated-client)

**Comment by AnilRana675** [comment]
Same problem 😕

**Comment by thelocs** [comment]
> Same problem 😕

me too

**Comment by muralivijay** [comment]
Same problem in linux too
