### ISSUE TITLE
Trojan detected in exe file

### ISSUE THREAD

**Issue by SamsungUser2k22** [reisxd/revanced-builder#377]
Page virus total was detected ReVanced Builder at Trojan.Agent.Win32.2853154
![20220904_152750](https://user-images.githubusercontent.com/110987053/188316493-c26235dd-be56-43ab-8b68-a3d5edd526cf.jpg)

Exe file have 38 Mb well i choose good file to scan

**Comment by reisxd** [comment]
> 1/67

AKA false positive.

**Comment by SamsungUser2k22** [comment]
Hey developers, I would like to say something. The subject is my report
that NIBY your tool has a Trojan ... Well then, after a long search, I
found that the "Zillya" Antivirus used by Virus Total is not very precise
when it comes to detecting threats, because it turns out that one user
wrote on the forum that Zillya has detected that Avast's exe file has
supposedly a Trojan. And so to the point ... As I saw this and your Linux
or MacOS version does not contain Virus Total threats. Even after scanning
with the best Defender, it detected nothing in ReVanced Builder.exe. And I
would like to add that I checked for Virus Total results and even the most
popular antiviruses did not detect the Trojan. Also, I'm sorry for this
fake report, because when I saw the results on Virus Total I panicked that
"Niee Trojan!" ... Besides, looking at the number of people working on this
project and people who react and report bugs, I trusted even more that not
this is not a Trojan ...

niedz., 4 wrz 2022, 15:47 użytkownik reis ***@***.***>
napisał:

**Comment by SamsungUser2k22** [comment]
And so generally. Could you please make ReVanced Builder not to detect
your tool as a possible threat the first time you start Windows
Defender Smart Screen? I mean, don't get more cases like this. So a
threat, but not ...

Regards! :-)


pon., 5 wrz 2022, 00:44 użytkownik Samsung ***@***.***> napisał:
