### ISSUE TITLE
Won't update(with screenshot)

### ISSUE THREAD

**Issue by maxs99674** [reisxd/revanced-builder#385]
To Reproduce

Go to termux
Type ./revanced-builder.sh update
press enter
See error
Screenshots:                                             https://user-images.githubusercontent.com/83088696/188484074-a67fb055-8b0e-4d74-b2b8-432ad618e8f9.jpg

I

OS: Android
Version: 12

**Comment by reisxd** [comment]
Send full screenshot.

**Comment by maxs99674** [comment]
> Send full screenshot.

This is the full screenshot
