### ISSUE TITLE
Does it support version older than 17.33.42

### ISSUE THREAD

**Issue by likkai** [reisxd/revanced-builder#394]
As the title says, because the select patches menu only shows 17.33.42 as the target version.

**Comment by reisxd** [comment]
Yes.

**Comment by likkai** [comment]
But it keeps crashing on YouTube 17.34.35 (not beta) and I'm using the latest builder (Android build)

**Comment by Toby222** [comment]
are you using incompatible patches?

**Comment by likkai** [comment]
Here's a recording of my enabled patches. the owner said that further versions are supported even though it shows 17.33.42

https://user-images.githubusercontent.com/76016664/189243388-2c45664b-41a8-4482-be92-69a1dbe239ca.mp4

**Comment by Toby222** [comment]
revanced-builder supports different versions.
Those patches only support that one version.
There's patches hat list `ALL` as their target version, which should work on any version

**Comment by likkai** [comment]
> Yes.

That's why I asked the owner of this tool. Guys I'll have to wait the revanced to update these patches

**Comment by reisxd** [comment]
> > Yes.
> 
> That's why I asked the owner of this tool. Guys I'll have to wait the revanced to update these patches

In your issue, you asked if the older versions worked. I said yes, but you used an unsupported version.

**Comment by likkai** [comment]
Just misunderstanding probably. Anyway, thank you both of you
