### ISSUE TITLE
[builder] SEVERE: theme failed

### ISSUE THREAD

**Issue by ElissonRodrigues** [reisxd/revanced-builder#397]
**To Reproduce**
Activate the "theme" patch and compile 

**Screenshots**
![Screenshot_20220908-093140_Chrome](https://user-images.githubusercontent.com/25101186/189122944-e46f3920-66d4-4fa8-a0af-cba9ad5cbdb9.jpg)

**revanced-builder Version:** 
V3.4.3

**Comment by reisxd** [comment]
Dupe of #396
