### ISSUE TITLE
Idk what that means

### ISSUE THREAD

**Issue by UnkreativerNutzername** [reisxd/revanced-builder#4]
Downloading latest patches, integrations and cli...
Unhandled Rejection
Reason: TypeError: patchesArray is not iterable
Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...

**Comment by Lolen10** [comment]
I have the same issue

**Comment by reisxd** [comment]
Hey, can you post the full console output?

**Comment by UnkreativerNutzername** [comment]
This is the full output as you can see here
![ReVanced](https://user-images.githubusercontent.com/103318149/177001256-6afeddb0-39e7-4996-8380-fa3d0158d0b8.PNG)

**Comment by reisxd** [comment]
> This is the full output as you can see here ![ReVanced](https://user-images.githubusercontent.com/103318149/177001256-6afeddb0-39e7-4996-8380-fa3d0158d0b8.PNG)

Can you manually run `java -jar revanced-cli-2.0.5-all.jar -b revanced-patches-2.5.0.jar -l` inside CMD?

**Comment by UnkreativerNutzername** [comment]
> > This is the full output as you can see here ![ReVanced](https://user-images.githubusercontent.com/103318149/177001256-6afeddb0-39e7-4996-8380-fa3d0158d0b8.PNG)
> 
> Can you manually run `java -jar revanced-cli-2.0.5-all.jar -b revanced-patches-2.5.0.jar -l` in the revanced folder, inside CMD?

Yes I can

**Comment by reisxd** [comment]
> > > This is the full output as you can see here ![ReVanced](https://user-images.githubusercontent.com/103318149/177001256-6afeddb0-39e7-4996-8380-fa3d0158d0b8.PNG)
> > 
> > 
> > Can you manually run `java -jar revanced-cli-2.0.5-all.jar -b revanced-patches-2.5.0.jar -l` in the revanced folder, inside CMD?
> 
> Yes I can

Please show the output of that command here.

**Comment by UnkreativerNutzername** [comment]
C:\Users\Max Mustermann\Downloads\revanced>java -jar revanced-cli-2.0.5-all.jar -b revanced-patches-2.5.0.jar -l
INFORMATION: seekbar-tapping: Enable tapping on the seekbar of the YouTube player.
INFORMATION: general-ads: Patch to remove general ads in bytecode.
INFORMATION: video-ads: Patch to remove ads in the YouTube video player.
INFORMATION: custom-branding: Change the branding of YouTube.
INFORMATION: premium-heading: Show the premium branding on the the YouTube home screen.
INFORMATION: minimized-playback: Enable minimized and background playback.
INFORMATION: disable-fullscreen-panels: Disable comments panel in fullscreen view.
INFORMATION: old-quality-layout: Enable the original quality flyout menu.
INFORMATION: hide-autoplay-button: Disable the autoplay button.
INFORMATION: disable-create-button: Disable the create button.
INFORMATION: amoled: Enables pure black theme.
INFORMATION: hide-shorts-button: Hide the shorts button.
INFORMATION: hide-cast-button: Patch to hide the cast button.
INFORMATION: hide-watermark: Hide Watermark on the page.
INFORMATION: microg-support: Patch to allow YouTube ReVanced to run without root and under a different package name.
INFORMATION: custom-playback-speed: Allows to change the default playback speed options.
INFORMATION: background-play: Enable playing music in the background.
INFORMATION: exclusive-audio-playback: Add the option to play music without video.
INFORMATION: codecs-unlock: Enables more audio codecs. Usually results in better audio quality but may depend on song and device.
INFORMATION: upgrade-button-remover: Remove the upgrade tab from the pivot bar in YouTube music.
INFORMATION: tasteBuilder-remover: Removes the "Tell us which artists you like" card from the Home screen. The same functionality can be triggered from the settings anyway.

**Comment by reisxd** [comment]
> C:\Users\Max Mustermann\Downloads\revanced>java -jar revanced-cli-2.0.5-all.jar -b revanced-patches-2.5.0.jar -l INFORMATION: seekbar-tapping: Enable tapping on the seekbar of the YouTube player. INFORMATION: general-ads: Patch to remove general ads in bytecode. INFORMATION: video-ads: Patch to remove ads in the YouTube video player. INFORMATION: custom-branding: Change the branding of YouTube. INFORMATION: premium-heading: Show the premium branding on the the YouTube home screen. INFORMATION: minimized-playback: Enable minimized and background playback. INFORMATION: disable-fullscreen-panels: Disable comments panel in fullscreen view. INFORMATION: old-quality-layout: Enable the original quality flyout menu. INFORMATION: hide-autoplay-button: Disable the autoplay button. INFORMATION: disable-create-button: Disable the create button. INFORMATION: amoled: Enables pure black theme. INFORMATION: hide-shorts-button: Hide the shorts button. INFORMATION: hide-cast-button: Patch to hide the cast button. INFORMATION: hide-watermark: Hide Watermark on the page. INFORMATION: microg-support: Patch to allow YouTube ReVanced to run without root and under a different package name. INFORMATION: custom-playback-speed: Allows to change the default playback speed options. INFORMATION: background-play: Enable playing music in the background. INFORMATION: exclusive-audio-playback: Add the option to play music without video. INFORMATION: codecs-unlock: Enables more audio codecs. Usually results in better audio quality but may depend on song and device. INFORMATION: upgrade-button-remover: Remove the upgrade tab from the pivot bar in YouTube music. INFORMATION: tasteBuilder-remover: Removes the "Tell us which artists you like" card from the Home screen. The same functionality can be triggered from the settings anyway.

So, thats why...
![image](https://user-images.githubusercontent.com/29177546/177001555-0da4a8bb-07b5-4915-bcfe-9582a611b9ff.png)
I'll try fixing that.

**Comment by UnkreativerNutzername** [comment]
> > C:\Users\Max Mustermann\Downloads\revanced>java -jar revanced-cli-2.0.5-all.jar -b revanced-patches-2.5.0.jar -l INFORMATION: seekbar-tapping: Enable tapping on the seekbar of the YouTube player. INFORMATION: general-ads: Patch to remove general ads in bytecode. INFORMATION: video-ads: Patch to remove ads in the YouTube video player. INFORMATION: custom-branding: Change the branding of YouTube. INFORMATION: premium-heading: Show the premium branding on the the YouTube home screen. INFORMATION: minimized-playback: Enable minimized and background playback. INFORMATION: disable-fullscreen-panels: Disable comments panel in fullscreen view. INFORMATION: old-quality-layout: Enable the original quality flyout menu. INFORMATION: hide-autoplay-button: Disable the autoplay button. INFORMATION: disable-create-button: Disable the create button. INFORMATION: amoled: Enables pure black theme. INFORMATION: hide-shorts-button: Hide the shorts button. INFORMATION: hide-cast-button: Patch to hide the cast button. INFORMATION: hide-watermark: Hide Watermark on the page. INFORMATION: microg-support: Patch to allow YouTube ReVanced to run without root and under a different package name. INFORMATION: custom-playback-speed: Allows to change the default playback speed options. INFORMATION: background-play: Enable playing music in the background. INFORMATION: exclusive-audio-playback: Add the option to play music without video. INFORMATION: codecs-unlock: Enables more audio codecs. Usually results in better audio quality but may depend on song and device. INFORMATION: upgrade-button-remover: Remove the upgrade tab from the pivot bar in YouTube music. INFORMATION: tasteBuilder-remover: Removes the "Tell us which artists you like" card from the Home screen. The same functionality can be triggered from the settings anyway.
> 
> So, thats why... ![image](https://user-images.githubusercontent.com/29177546/177001555-0da4a8bb-07b5-4915-bcfe-9582a611b9ff.png) I'll try fixing that.

Okay Thanks dude.

**Comment by reisxd** [comment]
I fixed it, I'm gonna make a new release.
