### ISSUE TITLE
Builder update issue

### ISSUE THREAD

**Issue by Indranil012** [reisxd/revanced-builder#402]
**Describe the bug**
Getting error while trying to update or reinstall the builder on termux

**To Reproduce**
./revanced-builder.sh update

**Traceback**
```
~  ./revanced-builder.sh update
[revanced-builder] Backing up some stuff...
[revanced-builder] Deleting revanced-builder...
[revanced-builder] Restoring the backup...
[revanced-builder] Updating revanced-builder...
[revanced-builder] Downloading revanced-builder...
[revanced-builder] Unzipping...
[revanced-builder] Installing packages...
[#########.........] | reify:accepts: sill audit bulk request {
npm ERR! code EACCES
npm ERR! syscall link
npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/a0957b5e
npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/c7/45/67f2ca48fb0b89d4ee92ee09db69083c3f187834d1dbeca4883661162a23c4e1128ea65be28e7f8d92662699180febc99cef48f611b793151b2bb306907a
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 10366:10366 "/data/data/com.termux/files/home/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-09-09T13_49_33_778Z-debug-0.log
[revanced-builder] Done. Execute `/data/data/com.termux/files/home/revanced-builder.sh run` to launch the builder.
```

**revanced-builder Version:**
What is the command to get version?

- OS: Android, termux
- Version: 12.1

**Comment by reisxd** [comment]
Try reinstalling Termux.

**Comment by Indranil012** [comment]
> Try reinstalling Termux.

Please i do other things on termux. Is there any other way?
See the latest traceback:

```
./revanced-builder.sh update
[revanced-builder] Backing up some stuff...
[revanced-builder] Deleting revanced-builder...
[revanced-builder] Restoring the backup...
[revanced-builder] Updating revanced-builder...
[revanced-builder] Downloading revanced-builder...
[revanced-builder] Unzipping...
[revanced-builder] Installing packages...
npm ERR! code EACCES
npm ERR! syscall link
npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/9eb883bb
npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/6c/2e/c496b7496899cf6c03fed44a2d62fa99b1bdde725e708ba05f8ba0494d470da30a7a72fb298348d7ce74532838e6fc4ec076014155e00f54c35c286b0730
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 10366:10366 "/data/data/com.termux/files/home/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-09-09T15_42_17_412Z-debug-0.log
[revanced-builder] Performing self-update...
[revanced-builder] Downloading latest version...
[revanced-builder] Done.
[revanced-builder] Inserting update process...
[revanced-builder] Done. Execute '/data/data/com.termux/files/home/revanced-builder.sh run' to launch the builder.

./revanced-builder.sh
[revanced-builder] Already gotten storage access.
[revanced-builder] Node.js and JDK already installed.
[revanced-builder] revanced-builder found.
[revanced-builder] All checks done.

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'debug'
Require stack:
- /data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js
- /data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/application.js
- /data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/express.js
- /data/data/com.termux/files/home/revanced-builder/node_modules/express/index.js
- /data/data/com.termux/files/home/revanced-builder/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js:14:13)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js',
    '/data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/application.js',
    '/data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/express.js',
    '/data/data/com.termux/files/home/revanced-builder/node_modules/express/index.js',
    '/data/data/com.termux/files/home/revanced-builder/index.js'
  ]
}

Node.js v18.7.0
```

**Comment by reisxd** [comment]
> > Try reinstalling Termux.
> 
> Please i do other things on termux. Is there any other way?
> See the latest traceback:
> 
> ```
> ./revanced-builder.sh update
> [revanced-builder] Backing up some stuff...
> [revanced-builder] Deleting revanced-builder...
> [revanced-builder] Restoring the backup...
> [revanced-builder] Updating revanced-builder...
> [revanced-builder] Downloading revanced-builder...
> [revanced-builder] Unzipping...
> [revanced-builder] Installing packages...
> npm ERR! code EACCES
> npm ERR! syscall link
> npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/9eb883bb
> npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/6c/2e/c496b7496899cf6c03fed44a2d62fa99b1bdde725e708ba05f8ba0494d470da30a7a72fb298348d7ce74532838e6fc4ec076014155e00f54c35c286b0730
> npm ERR! errno -13
> npm ERR!
> npm ERR! Your cache folder contains root-owned files, due to a bug in
> npm ERR! previous versions of npm which has since been addressed.
> npm ERR!
> npm ERR! To permanently fix this problem, please run:
> npm ERR!   sudo chown -R 10366:10366 "/data/data/com.termux/files/home/.npm"
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-09-09T15_42_17_412Z-debug-0.log
> [revanced-builder] Performing self-update...
> [revanced-builder] Downloading latest version...
> [revanced-builder] Done.
> [revanced-builder] Inserting update process...
> [revanced-builder] Done. Execute '/data/data/com.termux/files/home/revanced-builder.sh run' to launch the builder.
> 
> ./revanced-builder.sh
> [revanced-builder] Already gotten storage access.
> [revanced-builder] Node.js and JDK already installed.
> [revanced-builder] revanced-builder found.
> [revanced-builder] All checks done.
> 
> node:internal/modules/cjs/loader:959
>   throw err;
>   ^
> 
> Error: Cannot find module 'debug'
> Require stack:
> - /data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js
> - /data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/application.js
> - /data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/express.js
> - /data/data/com.termux/files/home/revanced-builder/node_modules/express/index.js
> - /data/data/com.termux/files/home/revanced-builder/index.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
>     at Module._load (node:internal/modules/cjs/loader:804:27)
>     at Module.require (node:internal/modules/cjs/loader:1022:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js:14:13)
>     at Module._compile (node:internal/modules/cjs/loader:1120:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
>     at Module.load (node:internal/modules/cjs/loader:998:32)
>     at Module._load (node:internal/modules/cjs/loader:839:12)
>     at Module.require (node:internal/modules/cjs/loader:1022:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js',
>     '/data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/application.js',
>     '/data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/express.js',
>     '/data/data/com.termux/files/home/revanced-builder/node_modules/express/index.js',
>     '/data/data/com.termux/files/home/revanced-builder/index.js'
>   ]
> }
> 
> Node.js v18.7.0
> ```

I guess, try reinstalling NodeJs or deleting the .npm folder using `rm -rf .npm`.

**Comment by Indranil012** [comment]
> > > Try reinstalling Termux.
> > 
> > 
> > Please i do other things on termux. Is there any other way?
> > See the latest traceback:
> > ```
> > ./revanced-builder.sh update
> > [revanced-builder] Backing up some stuff...
> > [revanced-builder] Deleting revanced-builder...
> > [revanced-builder] Restoring the backup...
> > [revanced-builder] Updating revanced-builder...
> > [revanced-builder] Downloading revanced-builder...
> > [revanced-builder] Unzipping...
> > [revanced-builder] Installing packages...
> > npm ERR! code EACCES
> > npm ERR! syscall link
> > npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/9eb883bb
> > npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/6c/2e/c496b7496899cf6c03fed44a2d62fa99b1bdde725e708ba05f8ba0494d470da30a7a72fb298348d7ce74532838e6fc4ec076014155e00f54c35c286b0730
> > npm ERR! errno -13
> > npm ERR!
> > npm ERR! Your cache folder contains root-owned files, due to a bug in
> > npm ERR! previous versions of npm which has since been addressed.
> > npm ERR!
> > npm ERR! To permanently fix this problem, please run:
> > npm ERR!   sudo chown -R 10366:10366 "/data/data/com.termux/files/home/.npm"
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-09-09T15_42_17_412Z-debug-0.log
> > [revanced-builder] Performing self-update...
> > [revanced-builder] Downloading latest version...
> > [revanced-builder] Done.
> > [revanced-builder] Inserting update process...
> > [revanced-builder] Done. Execute '/data/data/com.termux/files/home/revanced-builder.sh run' to launch the builder.
> > 
> > ./revanced-builder.sh
> > [revanced-builder] Already gotten storage access.
> > [revanced-builder] Node.js and JDK already installed.
> > [revanced-builder] revanced-builder found.
> > [revanced-builder] All checks done.
> > 
> > node:internal/modules/cjs/loader:959
> >   throw err;
> >   ^
> > 
> > Error: Cannot find module 'debug'
> > Require stack:
> > - /data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js
> > - /data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/application.js
> > - /data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/express.js
> > - /data/data/com.termux/files/home/revanced-builder/node_modules/express/index.js
> > - /data/data/com.termux/files/home/revanced-builder/index.js
> >     at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
> >     at Module._load (node:internal/modules/cjs/loader:804:27)
> >     at Module.require (node:internal/modules/cjs/loader:1022:19)
> >     at require (node:internal/modules/cjs/helpers:102:18)
> >     at Object.<anonymous> (/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js:14:13)
> >     at Module._compile (node:internal/modules/cjs/loader:1120:14)
> >     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
> >     at Module.load (node:internal/modules/cjs/loader:998:32)
> >     at Module._load (node:internal/modules/cjs/loader:839:12)
> >     at Module.require (node:internal/modules/cjs/loader:1022:19) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [
> >     '/data/data/com.termux/files/home/revanced-builder/node_modules/finalhandler/index.js',
> >     '/data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/application.js',
> >     '/data/data/com.termux/files/home/revanced-builder/node_modules/express/lib/express.js',
> >     '/data/data/com.termux/files/home/revanced-builder/node_modules/express/index.js',
> >     '/data/data/com.termux/files/home/revanced-builder/index.js'
> >   ]
> > }
> > 
> > Node.js v18.7.0
> > ```
> 
> I guess, try reinstalling NodeJs or deleting the .npm folder using `rm -rf .npm`.

Reinstalling nodejs fixed the issue
