### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by carls677** [reisxd/revanced-builder#407]
How to repair ?
![IMG_20220910_194449_903](https://user-images.githubusercontent.com/28660956/189508153-a3881bec-c382-43ad-ae7c-f33707039c16.jpg)

**Comment by reisxd** [comment]
You did not give Termux storage access, give it access using `termux-setup-storage`.

**Comment by carls677** [comment]
> No le dio acceso al almacenamiento de Termux, déle acceso usando `termux-setup-storage`.

Good bro

**Comment by carls677** [comment]
> You did not give Termux storage access, give it access using `termux-setup-storage`.

Ok bro good
