### ISSUE TITLE
getting a issue while building 

### ISSUE THREAD

**Issue by vo1d-7bin** [reisxd/revanced-builder#410]
OS: linux
Arguements: -jar, ./revanced/revanced-cli-v2.10.1.jar, -b, ./revanced/revanced-patches-v2.52.3.jar, -t, ./revanced-cache, --experimental, -a, ./revanced/youtube.apk, -o, ./revanced/revanced.apk, -m, ./revanced/revanced-integrations-v0.36.6.apk,
 OS Version#141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022

![image](https://user-images.githubusercontent.com/100482403/189580976-37a4df15-ea3d-4c17-b4f7-df9614f9f094.png)

**Comment by shrihanDev** [comment]
As of ea63c81, the Docker method is removed for good. Please use the prebuilt binaries or from source.
