### ISSUE TITLE
Version mismatch errors aren't exactly clear

### ISSUE THREAD

**Issue by deltaxsingh** [reisxd/revanced-builder#413]
**Describe the bug**
Not sure what exactly this means or what it's doing. Screenshot attached

**To Reproduce**
- Run the Android script in Termux

**Screenshots**
[Added](https://imgur.com/JRT9jV0) 

**revanced-builder Version:** [e.g. v1.2.10]
In screenshot?? Latest as of this date.

**Desktop (please complete the following information):**
Android 12, OneUI 4.1

**Additional context**
N/A

**Comment by shrihanDev** [comment]
The screenshot is blurry. Please upload a better quality.

**Comment by deltaxsingh** [comment]
> The screenshot is blurry. Please upload a better quality.

I remembered something from the PC builder, the stock youtube app needs to be updated to the latest. I did that and it appears to be working. I'm surprised that's not in the instructions since a previous user also raised the issue.

**Comment by shrihanDev** [comment]
Were you trying to build the root version?

**Comment by deltaxsingh** [comment]
> Were you trying to build the root version?

Yes sir

**Comment by shrihanDev** [comment]
Well then, that is the very basic requirement. It should be in the instructions, you're right.

**Comment by deltaxsingh** [comment]
> Well then, that is the very basic requirement. It should be in the instructions, you're right.

It seems like the script was unsuccessful actually, no errors either. The app simply force closes repeatedly.

**Comment by shrihanDev** [comment]
> the script was unsuccessful actually

Weird. What's the error in the screenshot? I can't see it 'cause its heavily blurred.

**Comment by deltaxsingh** [comment]
> > the script was unsuccessful actually
> 
> Weird. What's the error in the screenshot? I can't see it 'cause its heavily blurred.

I'll post tomorrow it's pretty late here. I'll fool around with it and see what happens. I think the version numbers are mismatched or something.

**Comment by deltaxsingh** [comment]
It turns out the version numbers did not match up. It would be helpful if the builder could inform root users what version it's downloading. The updated Play Store version was beyond the one the builder was using. I downgraded and it's working correctly now

**Comment by reisxd** [comment]
> It turns out the version numbers did not match up. It would be helpful if the builder could inform root users what version it's downloading. The updated Play Store version was beyond the one the builder was using. I downgraded and it's working correctly now

Actually, Builder does download the correct version.

> I downgraded and it's working correctly now

Currently, the supported stable version is 17.33.35, and before downgrading, you probably had an higher version than that version.

**Comment by deltaxsingh** [comment]
> Currently, the supported stable version is 17.33.35, and before downgrading, you probably had an higher version than that version.

Yeah that's what I mean, it would be helpful to query which version is supported and inform root users so we can be sure they match up. 

Thanks for your quick responses
