### ISSUE TITLE
TpyeError: global.version.push not a function

### ISSUE THREAD

**Issue by iguanastream** [reisxd/revanced-builder#419]
**Describe the bug**
![Screenshot_20220914-223221_Chrome 1](https://user-images.githubusercontent.com/24863166/190257032-4cd2e6cf-d747-4e46-8aa0-22742ec59fc1.png)

**To Reproduce**
Going through the web installation

**revanced-builder Version:** v3.4.3

**Desktop (please complete the following information):**

- OS: Android
- Version: 9

**Comment by ashiq-hasan** [comment]
I also have this same problem
