### ISSUE TITLE
Builder Error - TypeError (YouTube)

### ISSUE THREAD

**Issue by Syunmk** [reisxd/revanced-builder#420]
I'm currently trying to use the YouTube Builder using the Android method, but after the webserver launches and I click Continue on the "Downloading dependencies" page, I get the following error:
![Screenshot_20220914-163636_Chrome](https://user-images.githubusercontent.com/113555982/190258281-b40274cb-3623-4ddd-b330-596cf51f02d3.jpg)
The only thing I can do from there is to exit.

To add, I had successfully built it previously on my current phone using the same method but mistakenly uninstalled it.

Any help would be greatly appreciated.

**Comment by CivilizedGuide** [comment]
I'm getting the same error, at almost the same time and same version, I'm guessing that this is a developer mistake (he forgot to declare a function or something)

**Comment by Gestrid** [comment]
I had the same issue. I'd just completed the step where it downloads dependencies, same as OP.

**Comment by skiely** [comment]
Same as this
![Screenshot_20220914-235744](https://user-images.githubusercontent.com/1945927/190277445-dd284378-7371-496e-97b5-751cc18f97a5.png)
