### ISSUE TITLE
getting a error while running

### ISSUE THREAD

**Issue by vo1d-7bin** [reisxd/revanced-builder#424]
![image](https://user-images.githubusercontent.com/100482403/190441862-abc80410-e99e-4029-aaf6-20ddf83f15a6.png)

**Comment by shrihanDev** [comment]
Before running, could you please set the `NODE_DEBUG` environment variable?

Windows:
Open `cmd`, go to the directory where ReVanced Builder is stored and run

```
set NODE_DEBUG=child_process
revanced-builder-windows.exe
```

Linux/MacOS:
Open a terminal, go to the ReVanced Builder location and run:
```
NODE_DEBUG=child_process ./revanced-builder-windows.exe
```

**Comment by vo1d-7bin** [comment]
[builder] Listening at port 8001
[builder] The webserver is now running!
[builder] Opening the app in the default browser... CHILD_PROCESS 2398334: spawn {
  stdio: 'ignore',
  detached: true,
  env: {
    _: './revanced-builder-nodejs-linux',
    SSH_TTY: '/dev/pts/0',
    DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/0/bus',
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin',
    XDG_DATA_DIRS: '/usr/local/share:/usr/share:/var/lib/snapd/desktop',
    SSH_CLIENT: '104.28.193.15 47566 1024',
    XDG_RUNTIME_DIR: '/run/user/0',
    XDG_SESSION_ID: '2628',
    LESS_TERMCAP_us: '\x1B[1;32m',
    SHLVL: '1',
    LESS_TERMCAP_ue: '\x1B[0m',
    USER: 'root',
    LESS_TERMCAP_md: '\x1B[1;36m',
    LESS_TERMCAP_me: '\x1B[0m',
    LESS_TERMCAP_mb: '\x1B[1;31m',
    TERM: 'xterm-256color',
    XDG_SESSION_CLASS: 'user',
    SSH_CONNECTION: '104.28.193.15 47566 192.46.214.208 1024',
    LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
    LANG: 'en_US.UTF-8',
    HOME: '/root',
    MOTD_SHOWN: 'pam',
    XDG_SESSION_TYPE: 'tty',
    LOGNAME: 'root',
    PWD: '/root',
    LESS_TERMCAP_so: '\x1B[01;33m',
    LESS_TERMCAP_se: '\x1B[0m',
    SHELL: '/bin/bash',
    NODE_DEBUG: 'child_process',
    PKG_EXECPATH: '/root/revanced-builder-nodejs-linux'
  },
  args: [ 'xdg-open', 'http://localhost:8001' ],
  cwd: undefined,
  envPairs: [
    '_=./revanced-builder-nodejs-linux',
    'SSH_TTY=/dev/pts/0',
    'DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus',
    'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin',
    'XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop',
    'SSH_CLIENT=104.28.193.15 47566 1024',
    'XDG_RUNTIME_DIR=/run/user/0',
    'XDG_SESSION_ID=2628',
    'LESS_TERMCAP_us=\x1B[1;32m',
    'SHLVL=1',
    'LESS_TERMCAP_ue=\x1B[0m',
    'USER=root',
    'LESS_TERMCAP_md=\x1B[1;36m',
    'LESS_TERMCAP_me=\x1B[0m',
    'LESS_TERMCAP_mb=\x1B[1;31m',
    'TERM=xterm-256color',
    'XDG_SESSION_CLASS=user',
    'SSH_CONNECTION=104.28.193.15 47566 192.46.214.208 1024',
    'LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
    'LANG=en_US.UTF-8',
    'HOME=/root',
    'MOTD_SHOWN=pam',
    'XDG_SESSION_TYPE=tty',
    'LOGNAME=root',
    'PWD=/root',
    'LESS_TERMCAP_so=\x1B[01;33m',
    'LESS_TERMCAP_se=\x1B[0m',
    'SHELL=/bin/bash',
    'NODE_DEBUG=child_process',
    'PKG_EXECPATH=/root/revanced-builder-nodejs-linux'
  ],
  file: 'xdg-open',
  windowsHide: false,
  windowsVerbatimArguments: false
}
Done, check if a browser window has opened
[builder] An error occured.
Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by shrihanDev** [comment]
```bash
$ sudo apt-get install xdg-utils --reinstall
```
