### ISSUE TITLE
Resulting YouTube apk crashes on start up

### ISSUE THREAD

**Issue by iestynapmwg** [reisxd/revanced-builder#425]
After running revanced-builder-nodejs-linux, YouTube is installed on my phone over the top of the existing apk and automatically started. However, YouTube then crashes immediately after displaying the splash screen. If i try to open the app manually the same happens. Here is the crash log that was generated:
https://hastebin.com/ajibeqimah

**Comment by shrihanDev** [comment]
Which version did you try to build?

**Comment by reisxd** [comment]
This error only occurs on unsupported versions, please downgrade to 17.33.xx.
