### ISSUE TITLE
Can't get app version from Android

### ISSUE THREAD

**Issue by ViktorVoloshko** [reisxd/revanced-builder#426]
**Describe the bug**
Error while getting version.

**To Reproduce**

1. Exclude all microG patches
2. Procede to point where version must be detected

**Screenshots**
![image](https://user-images.githubusercontent.com/87974065/190497599-0f2924d4-548a-4300-b220-faea3a925c16.png)

**revanced-builder Version:** 3.4.4

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 Pro

**Console output:**
```
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'useVer')
    at downloadApp (C:\snapshot\revanced-builder\wsEvents\getAppVersion.js:31:15)
    at getAppVersion (C:\snapshot\revanced-builder\wsEvents\getAppVersion.js:111:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:187:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'useVer')
    at downloadApp (C:\snapshot\revanced-builder\wsEvents\getAppVersion.js:31:15)
    at getAppVersion (C:\snapshot\revanced-builder\wsEvents\getAppVersion.js:111:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:187:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
```

**Device ROM:** Pixel Experience
**Android version:** 12.1
**Root:** Magisk 25.2
**Root access:** Granted

**Comment by Dart2112** [comment]
Error was introduced in v3.4.3. Using v3.4.2 works as a work around temporally.

**Comment by ViktorVoloshko** [comment]
Okay, thx for info.

Also have same bug with Termux.

**Comment by HKC001** [comment]
> Error was introduced in v3.4.3. Using v3.4.2 works as a work around temporally.

Is it possible to install 3.4.2 via Termux?

**Comment by ViktorVoloshko** [comment]
> > Error was introduced in v3.4.3. Using v3.4.2 works as a work around temporally.
> 
> Is it possible to install 3.4.2 via Termux? The normal install process just pulls the latest version.

Clone or download as zip and unpack in Termux home directory https://github.com/reisxd/revanced-builder/tree/v3.4.2 so it replace 3.4.4 but I'm not sure shell-script doesn't check updates on launch.

**Comment by ViktorVoloshko** [comment]
Also, for those who want to patch on Android: https://github.com/revanced/revanced-manager
It's quite unstable and need you to manually download APK but much easier.

**Comment by Rikysonic** [comment]
I have the fix pending on my smartphone, as soon as I have time I'll open a PR
