### ISSUE TITLE
Error after run ReVanced Youtube

### ISSUE THREAD

**Issue by luki922** [reisxd/revanced-builder#429]
**Describe the bug**
Use [revanced-builder](https://github.com/reisxd/revanced-builder) to build YouTube on Linux

**To Reproduce**
Build ReVanced Youtube. I use YouTube 17.37.34 (beta) and 17.36.37 with this same error.

1. Build Revanced Youtube
2. Install it on Android
3. Run YouTube

**Screenshots**
Added 2 screenshots:
![Screenshot_2022-09-16-07-18-45-264_com miui bugreport](https://user-images.githubusercontent.com/3541269/190565749-72ee8177-b014-4f44-8272-af2f979e1358.jpg)
![Screenshot_2022-09-16-07-18-50-076_com miui bugreport](https://user-images.githubusercontent.com/3541269/190565755-4da1c5ca-dc88-4818-8bab-b71bd5555f53.jpg)

**revanced-builder Version:** [3.4.4]

- OS: [Android 12] Non-Root
- Xiaomi Mi 11i

**Comment by reisxd** [comment]
You did not use the supported version (17.33.xx). Please downgrade.

**Comment by luki922** [comment]
Is it written somewhere what version should use? You could do it like this with collapse feature: :
![1](https://user-images.githubusercontent.com/3541269/190572019-da640486-d0c7-40ef-9d08-80a548fd68bd.png)
![2](https://user-images.githubusercontent.com/3541269/190572024-9ad9f7c5-a25c-48d7-9644-13be964337c7.png)
