### ISSUE TITLE
root version installation error

### ISSUE THREAD

**Issue by Athi07** [reisxd/revanced-builder#43]
An error occured.
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at new NodeError (node:internal/errors:372:5)
    at Socket.onChildStdout (node:child_process:461:14)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER',
  cmd: 'java -jar ./revanced/revanced-cli-2.3.3-all.jar -b ./revanced/revanced-patches-2.11.0.jar --experimental -a ./revanced/youtube.apk -d 8c5c6b54 -c -o ./revanced/revanced.apk -m ./revanced/app-release-unsigned.apk  -e seekbar-tapping -e autorepeat-by-default -e custom-branding -e enable-wide-searchbar -e disable-fullscreen-panels -e hide-autoplay-button -e disable-create-button -e hide-shorts-button -e hide-cast-button --mount -e microg-support',
  stdout: '07-10 02:17:17.279  5104  5104 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +
    '07-10 02:17:17.283  5104  5104 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:17.283  5104  5104 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:17.769  5104  5104 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:17.785  5206  5206 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:17.789  5206  5206 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:17.789  5206  5206 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:17.846  5104  5104 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:18.201  5206  5206 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:18.279  5206  5206 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:18.814  5521  5521 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:18.817  5521  5521 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:18.817  5521  5521 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:19.322  5521  5521 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:19.393  5521  5521 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:19.998  5738  5738 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:20.001  5738  5738 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:20.001  5738  5738 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:20.285  5738  5738 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:20.332  5738  5738 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:21.121  5850  5850 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:21.124  5850  5850 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:21.124  5850  5850 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:21.392  5850  5850 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:21.438  5850  5850 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:22.202  5883  5883 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:22.205  5883  5883 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:22.205  5883  5883 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:22.458  5883  5883 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:22.503  5883  5883 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:23.323  5906  5906 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:23.326  5906  5906 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:23.326  5906  5906 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:23.578  5906  5906 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:23.629  5906  5906 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:24.421  5935  5935 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:24.424  5935  5935 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:24.424  5935  5935 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:24.679  5935  5935 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:24.723  5935  5935 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:25.543  5961  5961 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:25.546  5961  5961 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:25.546  5961  5961 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:25.789  5961  5961 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:25.837  5961  5961 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:26.653  6024  6024 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:26.657  6024  6024 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:26.657  6024  6024 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:26.930  6024  6024 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:26.977  6024  6024 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:27.747  6056  6056 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:27.749  6056  6056 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:27.749  6056  6056 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:28.015  6056  6056 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:28.064  6056  6056 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:28.389  4957  4957 I AndroidRuntime: VM exiting with result code 0.\n' +
    '07-10 02:17:28.832  6112  6112 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:28.834  6112  6112 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:28.834  6112  6112 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:29.093  6112  6112 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:29.308  6112  6112 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:29.351  6174  6174 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:29.353  6174  6174 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:29.353  6174  6174 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:29.630  6174  6174 D AndroidRuntime: Calling main entry com.topjohnwu.superuser.internal.RootServerMain\n' +
    '07-10 02:17:29.927  6243  6243 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:29.930  6243  6243 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:29.930  6243  6243 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:30.227  6243  6243 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:30.283  6243  6243 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:31.006  6365  6365 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:31.009  6365  6365 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:31.009  6365  6365 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:31.279  6365  6365 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:31.331  6365  6365 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:32.096  6391  6391 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:32.098  6391  6391 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:32.098  6391  6391 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:32.382  6391  6391 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:32.429  6391  6391 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:33.192  6417  6417 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:33.195  6417  6417 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:33.195  6417  6417 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:33.458  6417  6417 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:33.509  6417  6417 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:34.295  6437  6437 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:34.298  6437  6437 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:34.298  6437  6437 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:34.568  6437  6437 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:34.619  6437  6437 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:35.371  6465  6465 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:35.373  6465  6465 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:35.373  6465  6465 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:35.644  6465  6465 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:35.700  6465  6465 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:36.452  6488  6488 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:36.454  6488  6488 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:36.454  6488  6488 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:36.730  6488  6488 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:36.792  6488  6488 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:37.528  6515  6515 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:37.531  6515  6515 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:37.531  6515  6515 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:37.803  6515  6515 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:37.851  6515  6515 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:38.602  6535  6535 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:38.604  6535  6535 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:38.604  6535  6535 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:38.868  6535  6535 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:38.920  6535  6535 D AndroidRuntime: Shutting down VM\n' +
    '07-10 02:17:39.677  6555  6555 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<\n' +    '07-10 02:17:39.679  6555  6555 I AndroidRuntime: Using default boot image\n' +
    '07-10 02:17:39.679  6555  6555 I AndroidRuntime: Leaving lock profiling enabled\n' +
    '07-10 02:17:39.966  6555  6555 D AndroidRuntime: Calling main entry com.android.commands.content.Content\n' +
    '07-10 02:17:4'... 1038576 more characters,
  stderr: 'WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music \r\n' +
    'WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music \r\n' +
    'WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music \r\n' +
    'WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music \r\n' +
    'WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music \r\n'
}

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...

**Comment by reisxd** [comment]
It probably installed it, check your phone. Because the console output was too long, it crashed.
