### ISSUE TITLE
Patching YouTube app generates "severe" error

### ISSUE THREAD

**Issue by Gestrid** [reisxd/revanced-builder#437]
**Describe the bug**
On the "Patching" page, the page after selecting the patches that I want, the first lines on the page read

> `[builder] SEVERE: Error while setting option theme for patch theme: No such option: theme`
> `[builder] app.revanced.patcher.patch.NoSuchOptionException: No such option: theme at app.revanced.patcher.patch.PatchOptions.getUntyped(PatchOption.kt:39)`
> `[builder] at app.revanced.utils.OptionsLoader.readAndSet(OptionsLoader.kt:81) at app.revanced.utils.OptionsLoader.init(OptionsLoader.kt:26) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:140) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)`
> `[builder] at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)`

After the error displays, the patching process seems to continue like normal, however.

**To Reproduce**

1. Go through the patching process for the YouTube app like normal. I selected v17.36.37 of the app, the current recommended version.
2. When the process gets to the patching page, the first line will read as it says above in the description. However, the builder continues like normal and is able to generate the APK files in the end.

**Screenshots**

**revanced-builder Version:** v3.4.5

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 21H2 (OS Build: 22000.978)

**Additional context**
I've attached the full log of what appeared on the "Patching" page in a txt file below.
[ReVanced Patching Log.txt](https://github.com/reisxd/revanced-builder/files/9595886/ReVanced.Patching.Log.txt)

**Comment by reisxd** [comment]
Delete the `options.toml` file.
