### ISSUE TITLE
Proper fix for rooted reinstalls (#332)

### ISSUE THREAD

**Issue by Ittai-Dokoni** [reisxd/revanced-builder#443]
Currently installing a newly rebuilt patched apk on rooted device does not actually open the updated apk. This can easily be confirmed by changing what is patched and rebuilding. I believe this is due to the existing bind mount being cached by the system, and is not fixed by patch for #332.

Rooted device also does not seem to offer the option to choose the version to download/patch. Either you already have a patchable version installed, or it causes issues as per #413.

However, I found out that it is possible to use adb install to install an updated stock version of (at least for YouTube) apk. And once the patched apk is pushed, it uses the updated patched apk since the bind mount now points to a different location.

This would seem to fix both the reinstall issue as well as make patching more intuitive on rooted devices. In short, the code should do the following:

1. Check existing install version. 
2. If the latest patchable version is same or higher, offer to download those patchable base apk. If none available, advise to revert to system apk version by uninstalling updates.
3. Use adb install to push the install. If successful, proceed to building patched apk. If not (most likely signature mismatch), they will need to fix it manually.
4. ... Normal patching stuff goes here ...
5. Push the apk via normal root install method.

While this would temporarily install a "stock" version while the patching proceeds, it would make it easier to keep the version current as well as reduce a number of usability obstacles when it comes to rooted device.

**Comment by deltaxsingh** [comment]
Same, this has been annoying as I have no idea what version works when I run the builder. Pretty annoying.

**Comment by shrihanDev** [comment]
A loose attempt to implement the proposed solution has been made and merged in [873fde4](https://github.com/reisxd/revanced-builder/commit/873fde4f74c74d98f05904cebac9bb79b9da69e4).
