### ISSUE TITLE
Error on exit on Linux Fedora 36

### ISSUE THREAD

**Issue by bart3005** [reisxd/revanced-builder#449]
**Describe the bug**
When Exit is clicked in the application:

{builder] Killing any dangling processes... [builder] An error occured.
TypeError: Invalid host defined options
    at cleanExit (/snapshot/revanced-builder/index.js:92:14)
    at process.<anonymous> (/snapshot/revanced-builder/index.js:150:29)
    at process.emit (node:events:527:28)

**To Reproduce**

1. Run app as normal
2. At the end click exit

**revanced-builder Version:** [e.g. v1.2.10]

v3.4.7 also present on older versions

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]
- Linux Fedora 36

**Additional context**

Works fine except for this, which is a minor issue.

**Comment by reisxd** [comment]
This happens because `fkill` is an ES module and pkg (the module we use to build builder as a single executable) hates ES modules. We either replace this module or wait for a shiny new replacement for packing js code into a single executable, by the NodeJS team.
