### ISSUE TITLE
Failed to patch Reddit app

### ISSUE THREAD

**Issue by vasile-coste** [reisxd/revanced-builder#450]
I tried to patch Reddit app and got an error.
Steps to reproduce:
1. select reddit app
2. download dependencies 
3. select both patch
4. choose version 2022.35.1
5. click next and get this error:
![image](https://user-images.githubusercontent.com/17108452/191913028-f678c251-40dd-4a6e-b253-6f73ac6c2cf3.png)

Note: i've tried with 2022.35.0  and it works

**Comment by reisxd** [comment]
> i've tried with 2022.35.0 and it works

Probably theres either no full apk on the version or it just 404s. Because it's only affecting one version, I can't do much.

**Comment by caneleex** [comment]
> > i've tried with 2022.35.0 and it works
> 
> Probably theres either no full apk on the version or it just 404s. Because it's only affecting one version, I can't do much.

you can definitely make this more future proof. it's not about this specific version, it can happen to any app and any version. I'm sure it's possible to make this a more meaningful error.
