### ISSUE TITLE
Getting 'Failure' everytime on Android

### ISSUE THREAD

**Issue by Tasin5541** [reisxd/revanced-builder#458]
![Screenshot_2022-09-24-15-11-17-611-edit_com android chrome](https://user-images.githubusercontent.com/42533823/192090176-18ab5911-330f-4e19-8023-d208c575e556.jpg)

![Screenshot_2022-09-24-15-15-20-771-edit_com android chrome](https://user-images.githubusercontent.com/42533823/192090272-dd71bf24-59e3-485e-9841-7543c8c38cf0.jpg)

**Comment by Tasin5541** [comment]
The 2nd fetcherror seems to be an error with apkmirror with the latest reddit version. The 2nd latest version works fine.

**Comment by reisxd** [comment]
Dupe of #450 and retry about the 1st issue.
