### ISSUE TITLE
How to install OpenJDK 17

### ISSUE THREAD

**Issue by TgZ39** [reisxd/revanced-builder#459]
Im not able install OpenJDK, i used the link it gave me and downloaded one of them
![image](https://user-images.githubusercontent.com/71944761/192099413-5a5756c0-d8a8-4ab8-a2f8-67928b663ddc.png)
(this one)
Is this the right one? If not can anyone provide me with the correct version? Im on Win11 64 bit

**Comment by TgZ39** [comment]
![image](https://user-images.githubusercontent.com/71944761/192099523-05a901c5-8fc7-4a0f-8c04-f6817d7ac947.png)
also gave me this error

**Comment by mu-us61** [comment]
looks like you have java installed already first uninstall old one , then install the new one , use .msi one , which is in the bottom

**Comment by shrihanDev** [comment]
If some other distribution of Java is already installed, Zulu is not detected because it's not in PATH.

Solution: Update JAVA_HOME variable to point to Zulu or simply uninstall that other JDK if you don't really want to have it.

**Comment by TgZ39** [comment]
i have a few questions

**Comment by TgZ39** [comment]
![image](https://user-images.githubusercontent.com/71944761/192115917-b38babae-f54b-410d-bc8d-11f7d4fc4816.png)
1. Do i edit JAVA_HOME to zulu or do i go in Path and do it there?
2. Do i put in the link to this folder
![image](https://user-images.githubusercontent.com/71944761/192115960-b47af79b-2f5a-4c30-97bc-b84cbc3dd792.png)
of this file?
![image](https://user-images.githubusercontent.com/71944761/192115975-12f66f38-a4e2-4dc2-ad1c-836f828c0128.png)
If you have additinal info that could help me, that would be very helpful.

**Comment by shrihanDev** [comment]
@TgZ39 Yes, set JAVA_HOME to Zulu installation directory
