### ISSUE TITLE
Question: Ability to change app icon

### ISSUE THREAD

**Issue by likkai** [reisxd/revanced-builder#46]
The app I built always have the revanced logo as it's app icon. Is there a way to change the icon to default YouTube icon?

**Comment by SebiAi** [comment]
You need to exclude the `custom-branding` patch like this:
```bash
node . --patch --exclude custom-branding
```

With this you should have the default logo and app name

If you want to keep the app name but not the logo you would need to compile it yourself and change the patch or the logo

**Comment by reisxd** [comment]
Exclude the custom-branding patch.

**Comment by likkai** [comment]
Thanks guys

**Comment by likkai** [comment]
I tried using the command from the wiki but the terminal gives me this error, how do I fix it?

![image](https://user-images.githubusercontent.com/76016664/178154713-0e5b502f-0f60-49ec-becb-05402bebbd15.png)

**Comment by likkai** [comment]
Nvm, I solved it
