### ISSUE TITLE
choosing download manager

### ISSUE THREAD

**Issue by ifelixculpa** [reisxd/revanced-builder#462]
how do i select between pipe or powertube as default downloader while building revanced ?

**Comment by shrihanDev** [comment]
Not a question regarding ReVanced **Builder.**

**Comment by ifelixculpa** [comment]
> Not a question regarding ReVanced **Builder.**

sorry but where should i seek help regarding this sir

**Comment by shrihanDev** [comment]
Ask in r/revancedapp subreddit, or ReVanced Discord server.
