### ISSUE TITLE
Impossible to patch TikTok

### ISSUE THREAD

**Issue by uPos3odon08** [reisxd/revanced-builder#466]
When trying to patch tiktok it seems to get stuck on 
`[builder] at brut.androlib.Androlib.getResTable(Androlib.java:74) at app.revanced.patcher.Patcher.decodeResources(Patcher.kt:304) at app.revanced.patcher.Patcher.(Patcher.kt:72) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:139) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)`

The TikTok build i have tried patching is 26.3.3

The patches i have tried patching with are 
"TikTok ads"
"TikTok settings"
"TikTok download all"

![image](https://user-images.githubusercontent.com/82838374/192364168-ee5ecfd6-afcb-4108-b3cb-31d03d582377.png)

revanced-builder Version: v3.4.8

- OS: Windows 10
- System specs:
AMD Ryzen 5600x (6 cores, 12 threads)
Nvidia RTX 3070 (8gb vram)
Corsair Vengeance 16gb x2 3200mhz

I have tried patching YouTube with no problems

**Comment by reisxd** [comment]
You probably have 32bit installation of JDK, please reinstall.
