### ISSUE TITLE
Impossible to patch anything in Linux, even after installing OpenJDK

### ISSUE THREAD

**Issue by Deathstalkr1** [reisxd/revanced-builder#468]
**Describe the bug**
What the title says

**To Reproduce**

1. Have latest build of revanced-builder
2. Install latest OpenJDK after it giving you an error
3. Try to do it again, still gives same error
4. profit

**Screenshots**

**revanced-builder Version:** [3.4.8]

**Desktop (please complete the following information):**

- OS: [Fedora]
- Version: [36]

**Additional context**

**Comment by reisxd** [comment]
Your PATH is using an another distro of java, causing this issue.
