### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by CrypticPoptartz** [reisxd/revanced-builder#469]
Just as a heads up, while I'm a tech guy this stuff is a bit over my head. So apologies if this is a duplicate or user error.

**Describe the bug**
Cannot build Revanced using Windows 11

**To Reproduce**
0. Install zulu17.36.19-ca-jdk17.0.4.1-win_i686.msi
1. Run ReVanced Builder v3.4.8
2. Patching -> YouTube
3. Use all except [Enable Debugging]
4. Use [Recommended] (17.36.37)
5. Continue normally until patching
6. It brings up the [Failure] page with the same text as the CMD

**revanced-builder Version:**
[v3.4.8]

**Desktop**
- OS: Windows
- Version: 11

**Additional context**
I have tried on my 5600G PC and i7-11800H laptop (Both Windows 11), and reinstalling the latest version of Revanced Builder on both. 
I have tried to reboot the desktop
I also tried to just build the "Needed for non-root installs", but got the same error, plus some new ones

P.S
I got this software to work once for myself, but now that I want to give it to my sister and it's being fussy, so I appreciate any help you can spare! 

Error in CMD:
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'replace')
    at outputName (C:\snapshot\revanced-builder\wsEvents\patchApp.js:130:5)
    at afterBuild (C:\snapshot\revanced-builder\wsEvents\patchApp.js:39:3)
    at Socket.<anonymous> (C:\snapshot\revanced-builder\wsEvents\patchApp.js:212:53)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by reisxd** [comment]
This probably happens because of 0849f5b91511e332aca9a804c036afcf4ab95f64, I assume while its trying to get the output name, it fails because it cannot get the file name.

**Comment by reisxd** [comment]
Fixed in 56be9309a98d6a51329370e5128a0c3860a775af
