### ISSUE TITLE
v1.2.7

### ISSUE THREAD

**Issue by ReefBlade** [reisxd/revanced-builder#47]
An error occured.
TypeError: Cannot read properties of null (reading '0')
    at C:\snapshot\revanced-builder\index.js:504:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by reisxd** [comment]
This happens because of the new CLI update, not because of revanced-builder.

**Comment by ReefBlade** [comment]
any solutions?

**Comment by reisxd** [comment]
Until it gets fixed by the developers, no.
