### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by FadeMind** [reisxd/revanced-builder#471]
**Describe the bug**
package build error path

**To Reproduce**

```
  "packages": [
    {
      "name": "youtube",
      "patches": [
        "seekbar-tapping",
        "remember-video-quality",
        "minimized-playback",
        "client-spoof",
        "microg-support",
        "general-ads",
        "video-ads",
        "theme",
        "sponsorblock",
        "hide-cast-button"
      ]
    },
```

Run build

**Screenshots**

![20220927-1664259962](https://user-images.githubusercontent.com/9846948/192449099-40ac9e0d-46ad-4b92-8ebf-96e99f903946.png)

**revanced-builder Version:** 3.4.9

**Desktop (please complete the following information):**

- OS:  Windows 
- Version: 11

**Additional context**

```
D:.
│   includedPatchesList.json
│   options.toml
│   revanced-builder-win.exe
│
├───revanced
│       revanced-cli-v2.12.0.jar
│       revanced-integrations-v0.43.0.apk
│       revanced-patches-v2.69.3.jar
│       revanced-patches-v2.69.3.json
│       revanced.apk
│       revanced.keystore
│       VancedMicroG-v0.2.24.220220-220220001.apk
│       youtube.apk
│
└───revanced-cache
        1.apk
```

**Comment by reisxd** [comment]
@shrihanDev *sigh* time for an another fix :moyai: (this worked locally on codespaces though, weird.)

**Comment by shrihanDev** [comment]
Oh I get it

**Comment by reisxd** [comment]
> Oh I get it

It's because of W*ndows (the `\\`), will fix.

**Comment by shrihanDev** [comment]
> > Oh I get it
> 
> It's because of W*ndows (the `\\`), will fix.

Fixed

**Comment by reisxd** [comment]
> > > Oh I get it
> > 
> > 
> > It's because of W*ndows (the `\\`), will fix.
> 
> Fixed

Oh... I was wondering why I couldn't push 😅
