### ISSUE TITLE
MicroG support for YouTube Music fails

### ISSUE THREAD

**Issue by Pollot** [reisxd/revanced-builder#474]
**Describe the bug:**
MicroG support for YouTube Music doesn't patch properly.

**To Reproduce:**
Try to patch YouTube Music (recommended APK) with the MicroG support patch.

**Screenshots**
![image](https://user-images.githubusercontent.com/79442640/192537553-e9d17205-5070-41aa-aa40-f38fe1726062.png)

**ReVanced-builder Version:**
v.3.4.11

**Desktop:**
- OS: Linux
- Version: Fedora 36
- Java 17 installed (OpenJDK)

**Additional context:**
Youtube patches successfully.

**Comment by reisxd** [comment]
Not an issue with builder. See [this](https://github.com/revanced/revanced-cli/issues/143).
