### ISSUE TITLE
An error at the end of patching

### ISSUE THREAD

**Issue by sameerasw** [reisxd/revanced-builder#475]
```
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: Command failed: adb -s 3c78663d0305 push D:\Sameera\A2 lite Software\Root\revanced\revanced\ReVanced-YouTube-cli_v2.12.0-patches_v2.69.3.apk /data/local/tmp/revanced.delete

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
```

**Comment by dickta** [comment]
I had the same!

**Comment by shrihanDev** [comment]
Set the NODE_DEBUG environment variable to `child_process`, re-run builder and post logs.

**Comment by reisxd** [comment]
> Set the NODE_DEBUG environment variable to `child_process`, re-run builder and post logs.

I have an idea, maybe its because of those spaces?

BTW, I won't be active here for maybe a few days, because I formatted my phone and forgot to save 2FA codes (including Discord and GitHub), you may want to tell in ReVanced too.

**Comment by shrihanDev** [comment]
> I have an idea, maybe its because of those spaces?

Maybe, I'mma inspect this.

> I formatted my phone and forgot to save 2FA codes (including Discord and GitHub)

💀
