### ISSUE TITLE
Youtube  Music MicroG Support Fails

### ISSUE THREAD

**Issue by Joomsy** [reisxd/revanced-builder#476]
**Describe the bug**
Due to a missing AndroidManifest.xml, MicroG support fails to be added to YouTube Music. This bug doesn't exist in the official manager.

**To Reproduce**

1. Attempt to patch YouTube Music
2. See error

**Screenshots**

![screenshot](https://i.imgur.com/Gq1JuT7.png)

**revanced-builder Version:** [e.g. v1.2.10]

Latest master/3.4.11

**Comment by reisxd** [comment]
Dupe of #474.
