### ISSUE TITLE
Youtube builder 32 bit?

### ISSUE THREAD

**Issue by biglisy** [reisxd/revanced-builder#477]
Hello, I'm trying to build a Youtube version that is compatible with my relatively old tablet, 32 bit only.

But I can't seem to find any option to create a non 64 bit version of the app. 

Am I missing something?

**Comment by shrihanDev** [comment]
I'm using YouTube on my `arm-v7a` device, which is of course 32-bit. Just follow the same procedure.

Note that YouTube's newest version has now changed its minimum Android version to 8 (iirc the version was 17.37.35). So if the tablet is using something lower, then it's not possible to even use regular YouTube.
