### ISSUE TITLE
warning: aapt2 unknown cunk

### ISSUE THREAD

**Issue by cyberboh** [reisxd/revanced-builder#479]
**Describe the bug**
while patching, there is warning appear Unknown cunk type '200'

**To Reproduce**

Just patch any app you want

**Screenshots**
![ss](https://user-images.githubusercontent.com/99109969/192667909-3b9917d7-31b5-4d63-aad5-0007eaa9d356.png)

**revanced-builder Version:** [3.4.11 android]

**Desktop (please complete the following information):**

- OS: [Android]
- Version: [13]

**Additional context**

**Comment by shrihanDev** [comment]
It's a warning, which never hampers the build process.
