### ISSUE TITLE
Unable to print CJK letters in log

### ISSUE THREAD

**Issue by TheNoFace** [reisxd/revanced-builder#480]
**Describe the bug**
Browser log can't print CJK letters (maybe utf-8?)

* Log printed in terminal

        정보: exclusive-audio-playback succeeded
        정보: codecs-unlock succeeded
        심각: music-microg-support failed:
        app.revanced.patcher.patch.PatchResultError: 'music-microg-support' depends on 'music-microg-support' but the following error was raised: java.io.FileNotFoundException: revanced-cache\AndroidManifest.xml (지정된 파일을 찾을 수 없습니다)
                at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:259)

* Log printed in browser

        [builder] ����: exclusive-audio-playback succeeded
        [builder] ����: codecs-unlock succeeded
        [builder] �ɰ�: music-microg-support failed:
        [builder] app.revanced.patcher.patch.PatchResultError: 'music-microg-support' depends on 'music-microg-support' but the following error was raised: java.io.FileNotFoundException: .\revanced-cache\AndroidManifest.xml (������ ������ ã�� �� �����ϴ�)
        [builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:259)

**Screenshots**

![term](https://user-images.githubusercontent.com/3072090/192712832-68000528-a58d-4e93-a152-2b08df04c45e.png)

![browser](https://user-images.githubusercontent.com/3072090/192713084-bd4f01fa-74df-4c4c-b505-21c40a1c1e79.png)

**revanced-builder Version:** `v3.4.11`

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 22H2
- OpenJDK built by [Microsoft](https://learn.microsoft.com/en-us/java/openjdk/download) `v17.0.3`

**Comment by shrihanDev** [comment]
Okay so that's because it tries to render the log in 'Fira Code', maybe it doesn't support CJK.

**Comment by TheNoFace** [comment]
If you need fixed width font that supports Korean, then try this font. [D2Coding](https://github.com/naver/d2codingfont)

**Comment by TheNoFace** [comment]
Log still can't display Korean on `v3.4.12`. Also, it seems like Inziu Iosevka SC font does not support Korean. [Source Han Sans HW](https://github.com/chrissimpkins/codeface/blob/master/cjk-fonts/source-han-sans-HW) supports CJK properly

However even when I've built my own version with Source Han Sans HW font instead of Inziu Iosevka SC, log still couldn't display Korean.

**Comment by TheNoFace** [comment]
Log still  can't print Korean on `v3.4.14`

**Comment by shrihanDev** [comment]
Cannot reproduce, unfortunately

![Screenshot_2022-10-02-16-06-53-20.png](https://user-images.githubusercontent.com/54971391/193449822-5adc4abe-336b-4b15-8a14-b6074472367f.png)
