### ISSUE TITLE
Building any version of Twitter or TikTok

### ISSUE THREAD

**Issue by biglisy** [reisxd/revanced-builder#481]
I've been trying to build various different APKs of twitter or tiktok without ads (the only patch), but they keep giving me this java out of memory error. Building Youtubes works just fine however.

[Screenshot](https://i.imgur.com/H0h24jD.jpg)

I tried updating java to the latest version, looked for parameters to increase java memory allocation, still won't get rid of that error, preventing me to build any version of tiktok or twitter.

Is there anything I can do about it? (Not veeery tech savvy to understand where I'd even begin to write command line stuff)

Thanks

**Comment by reisxd** [comment]
You probably have an 32 bit installation of JDK, install the 64 bit version.
