### ISSUE TITLE
Termux unexpectedly closes out in 2nd part process of update code.

### ISSUE THREAD

**Issue by EuroSzymon** [reisxd/revanced-builder#483]
After compiling resources, Termux unexpectedly closes itself which makes that localhost cannot complete process on Android 12 Vivo Y20s. Please, fix.

**Comment by shrihanDev** [comment]
It's somewhat of a known issue since the OoM killer is pretty strict on Vivo, Oppo, etc. So, what you could do is split screen or multi window Termux and Chrome OR make Termux hold wakelock (swipe down the notifications and click "Acquire Wakelock" -> Allow).
