### ISSUE TITLE
Unable to parse YouTube Music in APKMirror

### ISSUE THREAD

**Issue by inotia00** [reisxd/revanced-builder#485]
**Describe the bug**
In the process of selecting the version of YouTube Music in APKMirror, the list could not be loaded and a parsing error occurred.

**To Reproduce**
Choose YouTube Music and proceed with the patch

**Screenshots**
*revanced-builder*
![yt-music-builder](https://user-images.githubusercontent.com/108592928/193409274-11e32d75-ffaf-4e4f-9446-e31eafd7025f.png)

*APKMirror*
![yt-music-apkmirror](https://user-images.githubusercontent.com/108592928/193409283-039d8a12-44f0-4d0f-a8f9-e32ce9002c17.png)

**revanced-builder Version:**
`v3.4.13`

**Desktop (please complete the following information):**
- OS: Windows 10
- Version: 21H2

**Additional context**
I solved it by temporarily applying this commit, but a fundamental solution is needed
https://github.com/inotia00/rvx-builder/commit/fec05e2c3a4c644e51b6ac49142d4ccd3665b339

**Comment by reisxd** [comment]
Why does Google come up with weird stuff?
