### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by deltaxsingh** [reisxd/revanced-builder#489]
Running through Termux on a rooted Android.

Receiving this error:
`Error: Cannot find module '/data/data/com.termux/files/home/revanced-builder'`

When I run both:

`./revanced-builder.sh update`

And 

`./revanced-builder.sh`

Not sure what this even means, hasn't happened before.

**Comment by reisxd** [comment]
Please send full log of `./revanced-builder.sh update`

**Comment by deltaxsingh** [comment]
Fixed it.

Went into the path specified and deleted the revanced-builder folder entirely. 

Worked this time.
