### ISSUE TITLE
You have an outdated version of JDK

### ISSUE THREAD

**Issue by AmirulAndalib** [reisxd/revanced-builder#49]
runner@fv-az196-146:~/work/tmate/tmate/revanced-builder$ node . --patch
You have an outdated version of JDK.
Please get it from here: https://www.azul.com/downloads/?version=java-17-lts&package=jdk
Press any key to exit... 

Having error with Openjdk Zulu

I even installed .Deb package manually but still same error.

Ubuntu:20.04
Azure Github Actions
All packages upgraded

**Comment by reisxd** [comment]
Run `java -version` and send the output

**Comment by AmirulAndalib** [comment]
``` $ java --version                                           openjdk 11.0.15 2022-04-19                                 OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)                                                     OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode) ```

**Comment by reisxd** [comment]
[Try doing what this user said here](https://github.com/reisxd/revanced-builder/issues/35#issuecomment-1179774896)

**Comment by AmirulAndalib** [comment]
> [Try doing what this user said here](https://github.com/reisxd/revanced-builder/issues/35#issuecomment-1179774896)

Can you give me direct snippet it's confusing me

**Comment by reisxd** [comment]
> > [Try doing what this user said here](https://github.com/reisxd/revanced-builder/issues/35#issuecomment-1179774896)
> 
> Can you give me direct snippet it's confusing me

Read the first sentence.

**Comment by AmirulAndalib** [comment]
# New error

---

```

runner@fv-az275-867:~/work/revanced-builder/revanced-builder$ node . --patch                                          node:internal/modules/cjs/loader:361                             throw err;                                                 ^                                                                                                               Error: Cannot find module '/home/runner/work/revanced-builder/revanced-builder/node_modules/whatwg-url/lib/public-api.js'. Please verify that the package.json has a valid "main" entry                                                         at tryPackage (node:internal/modules/cjs/loader:353:19)    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)                                                at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/revanced-builder/revanced-builder/node_modules/node-fetch/lib/index.js:10:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/work/revanced-builder/revanced-builder/node_modules/whatwg-url/package.json',
  requestPath: 'whatwg-url'
}

```

---
