### ISSUE TITLE
CANNOT MOUNT REVANCED ROOT

### ISSUE THREAD

**Issue by hajimAIM** [reisxd/revanced-builder#492]
![Screenshot_20221005-065126](https://user-images.githubusercontent.com/101944290/193945079-442b3a25-27b4-4088-9b9e-b4fcb58db997.jpg)
![Screenshot_20221005-053750](https://user-images.githubusercontent.com/101944290/193945087-c8a658dd-44a4-4daa-b9df-7bbff70415d9.jpg)

**Comment by shrihanDev** [comment]
Duplicate of #443
