### ISSUE TITLE
Error with the executable for windows

### ISSUE THREAD

**Issue by N3F0S** [reisxd/revanced-builder#50]
Downloading latest patches, integrations and cli...
[app-release-unsigned.apk] ✓
[microg.apk] ✓
An error occured.
TypeError: Cannot read properties of null (reading '0')
    at C:\snapshot\revanced-builder\index.js:497:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...

Sorry, i have got this Error with the latest executable for Windows have you got an idea how to solve it?

Thank you very much

**Comment by reisxd** [comment]
[I don't think you are using the latest build...](https://github.com/reisxd/revanced-builder/blob/main/index.js#L497)

**Comment by Stackedstudio** [comment]
Same issue with me

**Comment by reisxd** [comment]
You both probably don't use v1.2.8, please upgrade.

**Comment by N3F0S** [comment]
ah sorry i didnt see you updated 6 hours ago. Thank you
