### ISSUE TITLE
Error occurred after the selection of the patches/features

### ISSUE THREAD

**Issue by ATHARVplayz609** [reisxd/revanced-builder#500]
So I was trying to build the apk and stuff with revanced-builder, it was all going good until I got hit with a error which I have shown in the screenshot below and I don't know what to do to fix it and maybe could be an bug but it occurred after the part which lets me select the patches/features of the revanced app and well that's all if a solution can be provided that'll be great
![image](https://user-images.githubusercontent.com/90406929/194402571-dd0375e1-ec91-4b82-91e9-dac0ced8eeb5.png)

**Comment by reisxd** [comment]
Which version of Builder are you using?

**Comment by ATHARVplayz609** [comment]
The latest version of the builder which is 3.4.15
