### ISSUE TITLE
[builder] SEVERE: Failed to delete existing resource cache directory

### ISSUE THREAD

**Issue by What-Zit-Tooya** [reisxd/revanced-builder#501]
**Describe the bug**
While patching there is error [builder] SEVERE: Failed to delete existing resource cache director

**To Reproduce**
Just patching an app you select

**Screenshots**
![image](https://user-images.githubusercontent.com/9832875/194460640-db2212df-2d89-4cba-a70a-4b76493da82a.png)

**revanced-builder Version:** [3.4.15]

**Desktop (please complete the following information):**

- OS: [Windows]
- Version: [10]

**Additional context**

**Comment by shrihanDev** [comment]
Not exactly a problem I guess. Restart and check.

**Comment by What-Zit-Tooya** [comment]
> Not exactly a problem I guess. Restart and check.

restarted app and windows still same problem appear

**Comment by TinyVanced** [comment]
Even without using revanced-builder and following the recommended method in revanced-documentations, this issue sometimes recurs.

Maybe.. this is a revanced-cli issue
https://github.com/revanced/revanced-cli/issues/134

**Comment by What-Zit-Tooya** [comment]
> Even without using revanced-builder and following the recommended method in revanced-documentations, this issue sometimes recurs.
> 
> Maybe.. this is a revanced-cli issue [revanced/revanced-cli#134](https://github.com/revanced/revanced-cli/issues/134)

but its closed without any fixes

**Comment by Aurumaker72** [comment]
This is still persisting. If it's a non-issue, consider marking the cache invalidation fail as something else than "SEVERE".
