### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by SakethKanchi** [reisxd/revanced-builder#504]
**Describe the bug**
![image](https://user-images.githubusercontent.com/70198692/194749298-fc1f4c8e-bf03-4557-a161-a7e5ecec9522.png)

**To Reproduce**

1. Go to 'Start Patching'
2. Click on 'YouTube'
3. See error

**revanced-builder Version:** v3.4.15

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Comment by reisxd** [comment]
Try deleting the `revanced` folder.
