### ISSUE TITLE
Ho can choose right release during apk download for root release?

### ISSUE THREAD

**Issue by laltroweb** [reisxd/revanced-builder#505]
![Screenshot_20221010-205449_Edge](https://user-images.githubusercontent.com/16841896/194935520-874440a6-313d-400d-9342-b006b7bef1bd.png)
Work as expected, remain my installed release, but i don't understand how and if download right release in this setup page.

Ty.

**Comment by reisxd** [comment]
> **You are building rooted ReVanced**, ReVanced Builder will automatically download the correct version for you.
