### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Wileyap** [reisxd/revanced-builder#507]
I was trying to build the YT apk  with revanced-builder using termux from F-droid, but when it tried to patching, i got error as shown in the screenshot. Any solution?
![photo_2022-10-14_14-49-26](https://user-images.githubusercontent.com/104148227/195793121-4b3f7bf2-a334-4a6f-9eb8-7b01e9f01579.jpg)

**Comment by shrihanDev** [comment]
Try running `rm -rf ~/revanced-builder/revanced` and then `~/revanced-builder.sh`

**Comment by Wileyap** [comment]
it works.

**Comment by Wileyap** [comment]
Thank you
