### ISSUE TITLE
cannot create regular file '/storage/emulated/0/ReVanced-YouTube-v17.40.41-arm64-v8a-cli_v2.14.0-patches_v2.82.0.apk': Operation not permitted

### ISSUE THREAD

**Issue by ThaDurpFaceNL** [reisxd/revanced-builder#509]
I have the latest version and i get this error when everything is patched

![Screenshot_2022-10-15-09-30-03-082_com android chrome](https://user-images.githubusercontent.com/6972475/195974933-ab9c6eda-5ad4-4996-9467-422a294840df.jpg)

How can i fix this?

**Comment by reisxd** [comment]
You did not give storage access to Termux.
