### ISSUE TITLE
 [builder] Error: Invalid or corrupt jarfile C:\Users\Walker\Downloads\Programs\revanced\revanced-cli-v2.14.0.jar

### ISSUE THREAD

**Issue by jorycollins** [reisxd/revanced-builder#511]
**Describe the bug**
 Not sure if it is a bug or its a problem with the patching but I get this error when in the final step of patching after selecting which patches to include for non root variant.

**To Reproduce**

1. Go to select patches
2. Click on select the patches you want 
3. then click on continue to start patching.

**Screenshots**

**revanced-builder Version:v3.4.15

**Desktop (please complete the following information):**

- OS:  Windows
- Version: 10

**Additional context**
![Screenshot (19)](https://user-images.githubusercontent.com/94038012/196142427-2f8bf3c9-5537-4625-b5e4-a88dc5995ef8.png)

**Comment by ElissonRodrigues** [comment]
try running it using "run --dcnk". should work

**Comment by jorycollins** [comment]
where do I apply this command. Also as I'm on windows the rebuilder is just an executable file.
Also there is no such file as revanced.keystore nor a folder or path "revanced-builder/revanced/"
So please enlighten me.

**Comment by ElissonRodrigues** [comment]
> onde aplico este comando. Além disso, como estou no Windows, o reconstrutor é apenas um arquivo executável. Também não existe um arquivo como revanced.keystore nem uma pasta ou caminho "revanced-builder/revanced/" Então, por favor, esclareça-me.


in your case the files are in this folder:
C:\Users\Walker\Downloads\Programs\revanced\

You will delete these files:

revanced-cli-v2.x.x.jar
revanced-integrations-v0.x.x.apk
revanced-patches-v2.x.x.jar
revanced-patches-v2.x.x.json
youtube.apk

**Comment by jorycollins** [comment]
Thank you
