### ISSUE TITLE
Youtube rollback and lagging video

### ISSUE THREAD

**Issue by hibonox705** [reisxd/revanced-builder#513]
**Describe the bug**
Hi, i had this problem for a week now but after saying it on telegram no one responded so i'm saying it here. Recently the youtube app have been rolling back when i play a video. Basically i play a video and every now and then the video rollback a little bit in time. Plus the player as been lagging, the video charge really slowly.

**To Reproduce**

I just installed the youtube app using the termux app for non root using micro g. The version i use is youtube 17.36.37 and the lastest version of rvx builder

**Comment by reisxd** [comment]
Not an issue with ***ReVanced Builder*** and this isn't RVX Builder.
