### ISSUE TITLE
Command failed "su -c ..."

### ISSUE THREAD

**Issue by oguh43** [reisxd/revanced-builder#517]
**Describe the bug**

**To Reproduce**

1.  Build rooted and wait for install

**Screenshots**
![image](https://user-images.githubusercontent.com/13382592/197333366-1f66d56d-3fc1-4344-8804-8bfd21cc04fe.png)

**revanced-builder Version:** 3.4.15

**Desktop (please complete the following information):**

- OS: Android

**Additional context**

**Comment by Amby713** [comment]
su = super user

It means you need root access that termux doesn't have. If you don't have root, make sure you apply the patches that read 'needed for non-root'

**Comment by oguh43** [comment]
Well i know for a fact that termux has su access

**Comment by Amby713** [comment]
Is your device rooted?

**Comment by oguh43** [comment]
Yes and the error clearly states "Device or resource us busy" so i doubt its a su permission issue...

**Comment by shrihanDev** [comment]
Tracked in #443
