### ISSUE TITLE
Error building revanced

### ISSUE THREAD

**Issue by Murilobeluco** [reisxd/revanced-builder#52]
I'm getting this error while bulding revanced using this tool

I'm using Windows
![revanced-builder-nodejs-win_2022-07-11_16-50-43](https://user-images.githubusercontent.com/4254818/178346761-a03c9154-544f-418d-848c-12fa0435345a.png)

**Comment by broli95** [comment]
same here

**Comment by reisxd** [comment]
Fixed in v1.2.10, sorry!
