### ISSUE TITLE
Builder not working 

### ISSUE THREAD

**Issue by harshji888** [reisxd/revanced-builder#521]
![Screenshot_2022-10-22-22-35-10-867_com android chrome](https://user-images.githubusercontent.com/113840297/197353139-bc1fb3b8-747a-4516-a960-02e87a077181.jpg)
![Screenshot_2022-10-22-22-33-45-976_com termux](https://user-images.githubusercontent.com/113840297/197353137-37f53482-70da-4b43-96cb-91c48a377bb0.jpg)
**Describe the bug**

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**
There are bugs screenshot

**Comment by shrihanDev** [comment]
```bash
~/revanced-builder.sh run --dcnk
```
