### ISSUE TITLE
Not working or responding

### ISSUE THREAD

**Issue by Haiju78** [reisxd/revanced-builder#522]
**Describe the bug**
Youtube revanced not working

**To Reproduce**
![Screenshot_2022-10-23-15-29-56-414_app revanced manager flutter](https://user-images.githubusercontent.com/97692498/197380408-bf0595a9-1a8d-4f76-b4cb-7e3fa40731a8.jpg)
![Screenshot_2022-10-23-15-30-41-723_com google android packageinstaller](https://user-images.githubusercontent.com/97692498/197380410-1900e15e-faee-4b68-b073-20342d686cbc.jpg)
![Screenshot_2022-10-23-15-32-19-032_com android vending](https://user-images.githubusercontent.com/97692498/197380414-20710812-85d6-45c3-a734-941ade9b906e.jpg)
![Screenshot_2022-10-23-15-32-33-985_com miui global packageinstaller](https://user-images.githubusercontent.com/97692498/197380416-58c3a130-73ea-4be5-a2ef-dbc03bdb12fb.jpg)
![Screenshot_2022-10-23-15-32-37-054_com android vending](https://user-images.githubusercontent.com/97692498/197380417-3d555194-0ee0-45df-95bc-85ce07a0436c.jpg)
![Screenshot_2022-10-23-15-25-40-120_com miui home](https://user-images.githubusercontent.com/97692498/197380418-bf75c70e-8e41-4b10-b2ce-07bfd863a2e5.jpg)
![Screenshot_2022-10-23-15-22-35-006_com miui home](https://user-images.githubusercontent.com/97692498/197380420-132da1e5-c475-4d29-875e-2217222ac902.jpg)

**revanced-builder Version:** [e.g. v17.41.36]

**Additional context**

**Comment by reisxd** [comment]
bruh

**Comment by ActuallyTheSun** [comment]
smartest revanced user

**Comment by CnC-Robert** [comment]
:trollface:
