### ISSUE TITLE
Video-Ads not installing

### ISSUE THREAD

**Issue by eileooo** [reisxd/revanced-builder#526]
**Describe the bug**
The Video-Ads addon is not installing, it's displaying an error.

**To Reproduce**
Patch Youtube Normally

**Screenshots**
https://prnt.sc/eEQ8d2czG2od

**revanced-builder Version:** 
v3.4.15

**Desktop (please complete the following information):**
Windows 11 - 22H2

**Comment by reisxd** [comment]
Dupe of #515.
