### ISSUE TITLE
please bring back 17.34.36

### ISSUE THREAD

**Issue by mountaincastle47** [reisxd/revanced-builder#531]
it is the last youtube version to support android 6 and i have this android 6 tablet and now i can't update revaned so can you guys please bring back 17.34.36

**Comment by reisxd** [comment]
Download the APK from APKMirror, replace it with `revanced/youtube.apk` and patch. Because the version is old, it doesn't show up in the first page (APKMirror).

**Comment by mountaincastle47** [comment]
> Download the APK from APKMirror, replace it with `revanced/youtube.apk` and patch. Because the version is old, it doesn't show up in the first page (APKMirror).

Thanks
