### ISSUE TITLE
Illegal operation (read)

### ISSUE THREAD

**Issue by oguh43** [reisxd/revanced-builder#532]
**Describe the bug**
List of patches doesnt seem to be downloaded

**To Reproduce**

1. Select yt
2. crash

**Screenshots**
![image](https://user-images.githubusercontent.com/13382592/198702286-8154aa6e-e904-4ab5-8c87-6299971a041c.png)

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: Android

**Comment by oguh43** [comment]
Deleting revanced folder doesnt help. Not reinstalling

**Comment by reisxd** [comment]
> Deleting revanced folder doesnt help. Nor reinstalling. Also maybe publish new version?

Builder does not need a new update. Cannot reproduce.
