### ISSUE TITLE
Non Recommended Version Error

### ISSUE THREAD

**Issue by earmin** [reisxd/revanced-builder#534]
**Describe the bug**
My device is rooted. I installed YouTube Revanced successfully for the first time. Then wanted to create another build, but getting error on localhost:8000/version/ page. Tried to uninstall and reinstall Termux and checked all "com.termux" folder is removed on /data/data. YouTube, Vanced, MicroG are not installed. Also tried to installed stock YouTube from Google Play and uninstall it, but didn't solve.

![2022-10-OxP](https://user-images.githubusercontent.com/3898995/198925096-55b0fbb0-9700-420a-93d8-37c9062946c4.png)

If I cancel it shows a one line error, and if I click OK it shows these errors:
![2022-10-v8x](https://user-images.githubusercontent.com/3898995/198924247-fb45a6a2-76c0-47d8-9b65-a4d181da44dd.png)

Here's the data/data/com.termux path structure:
![2022-10-LwM](https://user-images.githubusercontent.com/3898995/198925305-e5939e4a-8320-4dbd-846f-fec9fc228d79.png)

**revanced-builder Version:** v3.4.15

- OS: Android
- Version: 9

**Comment by shrihanDev** [comment]
So the problem lies in the fact that when YouTube is not installed, it simply throws a misleading error about non-recommended versions. When you click Cancel, it is intended that there's that one-line error: if the user doesn't want to continue, they must downgrade (or upgrade, whichever is applicable) the version to the recommended one.

But when you click OK, it tries to download whatever version is installed on the device but boom, it's not installed, hence it gives that error.

The checking needs to be improved.

**Comment by earmin** [comment]
Version 3.4.16 just released. Let me check that and will update you with all errors on this version.

**Comment by earmin** [comment]
> Version 3.4.16 just released. Let me check that and will update you with all errors on this version.

Removed Termux completely and Installed 3.4.16 from scratch again. The same issue. 
It's the error on clicking Cancel:
![2022-10-Lg5](https://user-images.githubusercontent.com/3898995/199039387-8cf571a9-8d0b-4e79-aeae-26d82162d256.png)
And hitting OK leads to the first post's screenshots.

**Comment by shrihanDev** [comment]
> didnt i made it check if the app existed or not? :(

Whoops, then it doesn't work. `utils/getAppVersion.js` is getting all bamboozled and is thinking the app is installed, otherwise it should've thrown that error.

**Comment by earmin** [comment]
Just noticed when I select MicroG support in the patches list it shows the versions list to download! My device is rooted and the builder has granted root permission. So MicroG shouldn't be needed. 
It started the patching but failed with some errors. Will try with other version and MicroG it may work.

![20221101_215647](https://user-images.githubusercontent.com/3898995/199376809-518fc83b-3493-4afe-8d74-a935b602d1e8.jpg)

**Comment by reisxd** [comment]
Your device has the ArmV7 architecture, which is problematic with AAPT2. There's no fix to this but I'm not gonna close this issue because this is a problem for rooted devices.

**Comment by reisxd** [comment]
> > Your device has the ArmV7 architecture, which is problematic with AAPT2. There's no fix to this but I'm not gonna close this issue because this is a problem for rooted devices.
> 
> It is ArmV7, but I had created Revanced once last week on this device using the Revanced-builder. Then I just wanted to make some other modification but it never worked again. I also read some where that revanced manager doesnt work on ArmV7, but revanced-builder works.

Actually, it works on some devices. Both Builder and Manager uses the same AAPT2 binary, which is problematic on some devices.

**Comment by earmin** [comment]
This time it finished! 🎉 but YouTube fails to open! 😐
I'm not sure which step helped after many trial and errors. Latest steps I did and it worked:

- Uninstalled YouTube again
- Selected patches (also MicroG)
- Selected 17.41.36 from version page I think it was a beta version
- Continued the steps until it failed again (aapt2 failure)
- Copied downloaded YouTube.apk from revanced-builder folder from data/.../com.termux/... folder to emulated/0
- Installed YouTube.apk 17.41.36 (didn't open)
- Removed revanded-builder folder from /data/...
- Downloaded and installed revanced-builder again (the same commands on Wiki page on Termux)
- Selected the same steps (patches and microG)
- Selected the "beta, recommended" version v17.43.36 on version page
- It finished successfully and created MicroG and Youtube renced apks!
- Uninstalled 17.41.36
- Installed revanced-17.43.36
**- YouTube fails to open with no error. (Logo appears for a second and closes)**


![2022-11-EHi](https://user-images.githubusercontent.com/3898995/199499399-f21afaaa-27de-4616-847e-098644f4403e.png)
![2022-11-Rmf](https://user-images.githubusercontent.com/3898995/199497779-ae8cb930-d2a4-4c24-8018-ab13cdea905c.png)

**Comment by earmin** [comment]
Installed MicroG.apk manually and it fixed the issue! 🎉🙂😉

![2022-11-75Q](https://user-images.githubusercontent.com/3898995/199501950-20ef35fd-19ac-4efe-a956-9b47573e2f93.png)

**Comment by reisxd** [comment]
Hey, could you add `console.log(versionMatch);` to line 25?

https://github.com/reisxd/revanced-builder/blob/a32571f329a1b50c6176128df6d96d364cd14855/utils/getAppVersion.js#L23-L25

Use `nano` to edit the file, save it and re-run builder and when you get to the version selector, please send Termuxs screenshot.

**Comment by shrihanDev** [comment]
Closing because it's stale.
