### ISSUE TITLE
Fails to delete existing resource cache directory

### ISSUE THREAD

**Issue by androidghosh** [reisxd/revanced-builder#539]
**Describe the bug**
Everytime when building it fails to delete existing resource cache directory. Although that does not hamper making revanced app.
**To Reproduce**
I've kept the setup in D drive, and run normally, used recommended version to build 

**Screenshots**
![image](https://user-images.githubusercontent.com/17355109/200219512-3f599cef-4237-4b93-8062-9fd33b78ab06.png)

**revanced-builder Version:** [e.g. v3.4.16]

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10 latest]

**Comment by shrihanDev** [comment]
Is the build having issues in any way?

**Comment by reisxd** [comment]
If you installed Builder to the root of your D drive, that might be why. Also, this shouldn't effect anything.
