### ISSUE TITLE
Option to use WIP SponsorBlock patches

### ISSUE THREAD

**Issue by rodrigoswz** [reisxd/revanced-builder#54]
Currently sponsorblock support is in a different tree than main one:
https://github.com/revanced/revanced-patches/tree/sponsorblock

I would like to test this, even though I know it's work in progress and I can find bugs.
Would it be possible to add an option to use these patches?

**Comment by reisxd** [comment]
Sadly, you have to build that branch yourself and change it with the file `revanced-patches-x.x.x.jar` inside the revanced folder.
