### ISSUE TITLE
Outaded version of JDK bug

### ISSUE THREAD

**Issue by kearmau5** [reisxd/revanced-builder#541]
the latest revanced builder claims an outaded version of JDK while i do have the latest installed from AZUL

![error](https://user-images.githubusercontent.com/78478945/200655563-1a571997-9ca7-44af-92c7-cc37c68d3ef0.PNG)

revanced-builder Version: v3.4.16

- OS: windows
- Version: windows 10 21H2

version of JDK installed
![jdk ver](https://user-images.githubusercontent.com/78478945/200655606-922f38b1-997f-4011-b9b0-cf5057f1aa11.PNG)

**Comment by reisxd** [comment]
It's not added to PATH/not hoisted in your PATH.

**Comment by kearmau5** [comment]
![path](https://user-images.githubusercontent.com/78478945/200657963-a8772f52-836d-41ff-a279-932a3f66684a.PNG)
so what now ?

**Comment by shrihanDev** [comment]
Can you open a command prompt and run `java -version`?

**Comment by kearmau5** [comment]
> Can you open a command prompt and run `java -version`?
Don't you see it ?

**Comment by shrihanDev** [comment]
> > Can you open a command prompt and run `java -version`?
> 
> Don't you see it ?

Ah, sorry! My bad.

**Comment by kearmau5** [comment]
> [virtual_paths.zip](https://github.com/reisxd/revanced-builder/files/9993888/virtual_paths.zip)
> 
> This might help. Extract this batch script into the same folder as "revanced-builder-win.exe" that you downloaded from here then launch it.
> 
> It also sets the NODE_SKIP_PLATFORM_CHECK to make Revanced Builder run on Windows versions older than Windows 10.
> 
> **_Don't_ run as administrator.** - It'll most probably start using system directory as it's working dir if you do.

Thank you ! problem solved
