### ISSUE TITLE
YT Music building is failing.

### ISSUE THREAD

**Issue by CookieXD** [reisxd/revanced-builder#545]
**Describe the bug**
building is failing.
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\username\AppData\Local\Temp\brut_util_Jar_61033223218323947574276302304274382963.tmp

**To Reproduce**
just try to build youtube music with the recommended version and all patches.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14136885/201531581-66872023-5d4b-4cb4-b465-85265fa0f32f.png)

**revanced-builder Version:** [e.g. v1.2.10]
3.4.16

**Desktop (please complete the following information):**
Windows 11 22H2 (German)
Eclipse Temurin JDK with Hotspot 19+36 (x64)

**Additional context**

**Comment by shrihanDev** [comment]
> Eclipse Temurin JDK with Hotspot 19+36

As far as I recall, the Azul Zulu JDK 17 is needed for ReVanced to build correctly, for it has certain necessary changes and additions. Could you try with the recommended JDK? Thanks!

**Comment by reisxd** [comment]
> > Eclipse Temurin JDK with Hotspot 19+36
> 
> As far as I recall, the Azul Zulu JDK 17 is needed for ReVanced to build correctly, for it has certain necessary changes and additions. Could you try with the recommended JDK? Thanks!

AAPT2 failed there. It seems like it failed because of a corrupt APK or they just have to delete %localappdata%/APKTool (iirc).

**Comment by CookieXD** [comment]
well i don't know what it was but it was only fixed when I reinstalled Windows...
