### ISSUE TITLE
Apk crash

### ISSUE THREAD

**Issue by ibrahimashraf** [reisxd/revanced-builder#547]
I build apks on windows 11 and when installed them on phone they don't open just close once launched

**Comment by reisxd** [comment]
If you didn't install microg.apk, there's your issue.

**Comment by ibrahimashraf** [comment]
Installed

**Comment by ibrahimashraf** [comment]
![IMG_20221114_115328](https://user-images.githubusercontent.com/16999985/201629838-1cd0921f-53d5-45cd-ba8c-8e7ad15b899b.jpg)
I already installed the one with app build but open button not working either
