### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by skiely** [reisxd/revanced-builder#548]
![Screenshot_20221114-121250](https://user-images.githubusercontent.com/1945927/201657837-62d857eb-0818-4a41-ada7-11f26faa27a8.png)
![Screenshot_20221114-120948](https://user-images.githubusercontent.com/1945927/201657862-16d6ff85-fbf8-4fe2-b038-e03e88cfab77.png)

**Comment by Vretu-Dev** [comment]
Try `apt get update` and `apt get upgrade`

**Comment by Vretu-Dev** [comment]
`apt-get update`
`apt-get upgrade`
I forgot "-" symbol

**Comment by skiely** [comment]
Thanks d00d, fixed 👍🏻
