### ISSUE TITLE
Sorry, just a question about how to keep Revanced up to date

### ISSUE THREAD

**Issue by lulMeow** [reisxd/revanced-builder#552]
I don't build Revanced from the source, just grabbed the MicroG and Revanced APKs from here https://revanced.io/ and installed on my phone.

but I want to know if there is any way to keep the app up to date other than manually keep checking that website for newer versions and downloading the APKs and installing them.

I mean even if there isn't or won't be any mechanism like YouTube Vanced manager to keep apps up to date, i'd still be ok to just be notified whenever a new verion is released so I can do the rest myself.

Thanks 🙂

**Comment by reisxd** [comment]
> After some more digging, I just realized that's not your official website (which I found from reddit!) and this is: https://github.com/revanced
> 
> are the APKs there trusted?
> 


No. Only build it yourself. I closed this because it was an invalid issue (shouldn't even be here). revanced.io is also not affiliated with ReVanced Builder. I did not make that site.
