### ISSUE TITLE
Builder tries to make a folder named "revanced" in "C:\WINDOWS\system32\" and fails

### ISSUE THREAD

**Issue by Gestrid** [reisxd/revanced-builder#553]
**Describe the bug**
After selecting any app  (YouTube, Twitch, Twitter, etc.) to patch, the builder tries to download dependencies and immediately fails on Windows with the block of text shown in Screenshots below. The builder seemingly tried and failed to make a folder in the system32 directory.

**To Reproduce**

1. On version 3.5.0 (earlier versions are untested), select an app to patch and click continue.
2. The builder will show a Failure page.

**Screenshots**
![Screenshot of the error message.](https://user-images.githubusercontent.com/6199046/202364553-f5bb5436-c5c7-453e-919e-4b90bbdfbc1b.png)

**revanced-builder Version:** v3.5.0

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 21H2

**Additional context**
Revanced-builder-win.exe is saved in my Downloads folder. I also have a ReVanced folder that a previous version of the builder created that's sitting in my downloads folder.

**Comment by reisxd** [comment]
Where is Builder located in?

**Comment by Gestrid** [comment]
The EXE file "revanced-builder-win.exe" is located in my downloads folder, "C:\Users\[USERNAME]\Downloads".

**Comment by reisxd** [comment]
> The EXE file "revanced-builder-win.exe" is located in my downloads folder, "C:\Users\[USERNAME]\Downloads".

Could you try moving it to somewhere else?

**Comment by Gestrid** [comment]
I moved it to my desktop instead, and it now seems to be working until after I select patches. But now, it's saying I either don't have a device plugged in or don't have ADB installed.

I actually don't have a device plugged in, but I do have ADB's platform tools downloaded.

**Comment by reisxd** [comment]
> I moved it to my desktop instead, and it now seems to be working until after I select patches. But now, it's saying I either don't have a device plugged in or don't have ADB installed.
> 
> I actually don't have a device plugged in, but I do have ADB's platform tools downloaded.

That's normal if you didn't select MicroG Support and Hide Cast Button. It tries to do a rooted build.


I guess this is just a Windows™ moment? I don't know.

**Comment by Gestrid** [comment]
Ok. I went back and selected the MicroG patch, and it worked.

Anyway, I'm guessing there was just some weird glitch when the new EXE tried to read old files in the "revanced" and "revanced-cache" folders. I haven't actually updated ReVanced Builder on my computer in a couple months (the folders were last modified in September) since I usually just use Termux on my phone instead.

**Comment by Gestrid** [comment]
I forgot to mention that I tried deleting the old "revanced" and "revanced-cache" folders, moving the v3.5.0 EXE back to my downloads folder, and opening it. It recreated the "revanced" folder and seems to be working correctly now.

**Comment by shrihanDev** [comment]
> I forgot to mention that I tried deleting the old "revanced" and "revanced-cache" folders, moving the v3.5.0 EXE back to my downloads folder, and opening it. It recreated the "revanced" folder and seems to be working correctly now.

Thus, this issue will be closed as completed.
