### ISSUE TITLE
Selecting Twitch in builder shows a patch for Warnwetter

### ISSUE THREAD

**Issue by GuyInCanada** [reisxd/revanced-builder#557]
**Describe the bug**
When selecting Twitch, the patch list shows a patch for WarnWetter in addition to the 4 Twitch patches

**To Reproduce**

1. Go to 'Start Patching'
2. Click on 'Twitch'
3. Click on 'Continue'
4. The first patch listed (Promo Code Unlock) is for WarnWetter, not Twitch

**revanced-builder Version:** 3.5.0

**Screenshots**
![Screenshot_20221117-194120_Edge](https://user-images.githubusercontent.com/59619080/202595536-19170c8f-98d1-4b67-a941-03d128e02bb1.jpg)

**Comment by GuyInCanada** [comment]
I was able to fix it by editing the values of the Twitch entry in the following files. I changed it from 'app' to 'tv.twitch.android.app'.

apps\index.html
utils\downloadApp.js
utils\PatchListRememberer.js
wsEvents\getAppVersion.js
wsEvents\patchApp.js

**Comment by reisxd** [comment]
Fixed in the latest commit.
