### ISSUE TITLE
General ads failed 

### ISSUE THREAD

**Issue by B0TRICK** [reisxd/revanced-builder#560]
General ads failed 

**Screenshots**
![Screenshot_20221118-181320_Brave](https://user-images.githubusercontent.com/113281799/202708486-47250416-cb30-43bd-ad5b-3b8ab223bbae.png)

**revanced-builder Version:** [e.g. v1.2.10]

- OS: [Android]
- Version: [12]

**Additional context**
I don't know what happened general ads failed , please solve this :(

**Comment by reisxd** [comment]
Not a Builder issue.
