### ISSUE TITLE
Can't patch becuase of this (You either don't have a device plugged in or don't have ADB installed.)

### ISSUE THREAD

**Issue by Swordsmagus** [reisxd/revanced-builder#561]
I try using patching Youtube using this application but after I pick my patches it give me this: "You either don't have a device plugged in or don't have ADB installed."

Screenshots:
![image](https://user-images.githubusercontent.com/107529267/202780875-56aaadca-0371-416e-9df7-5911479d73ae.png)

revanced-builder Version: v3.5.0

Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Comment by reisxd** [comment]
Select the MicroG Support patch.
