### ISSUE TITLE
 Just help i don't know anything. I have this bug 

### ISSUE THREAD

**Issue by Golukumar00** [reisxd/revanced-builder#565]
![Screenshot_20221125-230737](https://user-images.githubusercontent.com/119071430/204034473-2196a314-2243-437a-b360-eae19c8f3ed9.png)
**Describe the bug**

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v3. 5.0]]

**Desktop (please complete the following information):**

- OS: [e.g.android]
- Version: android 12

**Additional context**

**Comment by shrihanDev** [comment]
Use `~/revanced-builder.sh --dcnk` inside Termux and check.

**Comment by Golukumar00** [comment]
Showing this in Termux 
![Screenshot_20221126-144211~2.png](https://user-images.githubusercontent.com/119071430/204081410-c0144a6d-f0b2-454c-9993-ebf879891ef0.png)

**Comment by Golukumar00** [comment]
If I do like this ![Screenshot_20221126-145645~2.png](https://user-images.githubusercontent.com/119071430/204081880-0cbbaa2f-1447-41d5-b375-4f2ad58fd091.png)

**Comment by Golukumar00** [comment]
Thanks for give me reply  🙏 but I uninstalled all package and reinstalled then problem solved.
