### ISSUE TITLE
Can't figure out how to get it to recognize the freshly downloaded java 17

### ISSUE THREAD

**Issue by JO-R-D-AN** [reisxd/revanced-builder#568]
It says:
[builder] You have an outdated version of JDK.
Please get it from here: https://www.azul.com/downloads/?version=java-17-lts

**Comment by AJolly** [comment]
Having the same issue

**Comment by Lucas559-noob** [comment]
maybe check on java arguments on your pc, if they are made to use that java

**Comment by reisxd** [comment]
> I'm having this issue as well on Windows 10. I'm fairly certain it's because of the Java check on this line: https://github.com/reisxd/revanced-builder/blob/31817ab98e2836e4d5a8ba6ec350f11a7fec6770/utils/checkJDKAndAapt2.js#L14
> 
> I'm not sure why there are two modules doing a check for the JDK, but one of them is doing `java --version` which works on Windows and one is doing `java -v` which doesn't. Doesn't even work on my linux machine.

One is for Android, one is for PC. Also, `java --version` is incorrect, `java -version` is. 


This issue is a dupe and it's because of the PATH enviroment pointing to both old and new but old being higher, so it's selected.

**Comment by Tempystral** [comment]
I see. Interesting, thank you. I'll take a look at my PATH and see if there's some old version of Java in there that I need to remove.
