### ISSUE TITLE
Builder fails to install

### ISSUE THREAD

**Issue by varishtsg** [reisxd/revanced-builder#569]
**Describe the bug**
Once the patching finishes, and application is installed / mounted, it fails with resource busy error

**To Reproduce**

1. Follow the rooted build steps, at the end instead of mounting, this error is thrown

**Screenshots**
![Screenshot_20221129-203538_Firefox](https://user-images.githubusercontent.com/11255535/204565302-cf1bdaf7-c822-4a8d-beba-a4ec7de9fd7d.png)

**revanced-builder Version:** [e.g. v1.2.10] v3.5.0

**Desktop (please complete the following information):**

- OS: [e.g. Windows] Android 12. LOS 19.1 Termux
- Version: [e.g. 10]

**Additional context**

**Comment by shrihanDev** [comment]
Tracked in #443.
