### ISSUE TITLE
error when building youtube

### ISSUE THREAD

**Issue by CyclicPoet44782** [reisxd/revanced-builder#570]
![Screenshot_1](https://user-images.githubusercontent.com/75398436/204877978-039ff930-7232-47ab-b180-2c1a8aad8cf7.png)
im getting this error when building youtube lastest beta
Describe the bug
some patches fail during the patching process

To Reproduce
Choose YouTube lastest beta and proceed with the patch

Screenshots
revanced-builder

**Comment by reisxd** [comment]
Not a Builder issue.
