### ISSUE TITLE
Support for older Android versions with older patches

### ISSUE THREAD

**Issue by Dilbao** [reisxd/revanced-builder#572]
Current Youtube apk works with Android 8, but previously Android 6 was the lowest supported version. That switch happened after v17.34.36 which is the final version for Android 6 and 7. After that, support old versions droped very quickly and it will not coming back.

What I am trying to do is building with an older supported version with older patches. However there is no easy way to do that with revanced builder.

Is is possible to add an option for 17.34.36 and its supported patches as a legacy version? There are still many older devices out there and this way they can use this final version as long as it keeps working.

**Comment by reisxd** [comment]
ReVanced also no longer supports v17
34.xx.
