### ISSUE TITLE
Not mounting YouTube after building YouTube 

### ISSUE THREAD

**Issue by B0TRICK** [reisxd/revanced-builder#573]
**Screenshots**

![Screenshot_20221206-190855_Brave - Nightly](https://user-images.githubusercontent.com/113281799/205935187-72b27334-5029-4a4b-9831-bcdbaf174546.png)

- OS: [Android]
- Version: [12]

**Additional context**
Updating from 17.43.xx to 17.45.36 not working

**Comment by TheGoldenSun** [comment]
Here's an easier way for you, download stock YouTube version 17.45.36 from here: 

https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-45-36-release/ 

And then download revanced manager here to patch every feature you need so you don't have to worry about receiving any type of errors from a hosting website: 

https://github.com/revanced/revanced-manager

You're welcome.

**Comment by shrihanDev** [comment]
Known issue vide #443
