### ISSUE TITLE
Running out of Heap Space when building Tiktok

### ISSUE THREAD

**Issue by manupawickramasinghe** [reisxd/revanced-builder#574]
The builder stops when building the 

**To Reproduce**

Selected the APK version  27.3.2
Selected all the available features to 

![Screenshot from 2022-12-08 11-29-45](https://user-images.githubusercontent.com/73810867/206369294-3aa632d6-0f54-4093-bbc1-6e14fe6640a5.png)

**revanced-builder Version:** [v3.5.0]

**Desktop (please complete the following information):**

- OS: Ubuntu Linux
- Version: 22.10 Kinetic Kudu

**Comment by Legitti** [comment]
Same here, getting errors on windows and it creates APK over 3GB in size. Something is wrong

**Comment by reisxd** [comment]
32 Bit installation of JDK/JRE. Please install the 64 Bit one.
