### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by aDifferentBook** [reisxd/revanced-builder#575]
![Screenshot_20221208-215735_Termux](https://user-images.githubusercontent.com/80353171/206511923-b17023be-060d-4b26-aa6a-c2ebb5597120.png)

Unable to download and execute script after changing ROM (Currently on Android 12.1) everything working fine on termux except this one.
I've removed silent `-s` flag from orignal `curl -sLo` to see the output after trying several times.

**Comment by brainwaster** [comment]
Could this have something to do with the patches repo getting DMCA'd

**Comment by reisxd** [comment]
> Could this have something to do with the patches repo getting DMCA'd

No. This is an issue with OPs internet.
