### ISSUE TITLE
Ratelimited from GitHub

### ISSUE THREAD

**Issue by BertrandTheHealer** [reisxd/revanced-builder#576]
**Describe the bug**
Upon trying to build YouTube, receive the error ```Error: You got ratelimited from GitHub
...Completely? What did you even do?```

**To Reproduce**

1. Launch ReVanced Builder from command line
2. In web interface, click on ```Start Patching```
3. Select ```YouTube```, click ```Continue```
4. See screen titled "Failure" with following text:
```
[builder] An error occured.
Error: You got ratelimited from GitHub
...Completely? What did you even do?
    at getDownloadLink (/data/data/com.termux/files/home/revanced-builder/utils/FileDownloader.js:52:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async downloadFiles (/data/data/com.termux/files/home/revanced-builder/utils/FileDownloader.js:156:26)
    at async updateFiles (/data/data/com.termux/files/home/revanced-builder/wsEvents/updateFiles.js:68:3)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:163:9)
```

**revanced-builder Version:** 3.5.0

**Desktop:**

- OS: Android
- Version: 12

**Comment by BertrandTheHealer** [comment]
The error still occurs after reinstall as well.

**Comment by Dart2112** [comment]
Going out on a limb here

I suspect this has to do with the DMCA on revanced patches

**Comment by admin-elvistrujanovic** [comment]
Yes, the same problem is for me too. @reisxd Is this project EOL now if no one can tell us how can we bypass this?

**Comment by reisxd** [comment]
> Yes, the same problem is for me too. @reisxd Is this project EOL now if no one can tell us how can we bypass this?
> 
> And please, ping this issue because it's important for people to know that they will not be able to build revanced from this tool from now

ReVanced Manager also does not work with default configurations, they'll both work once the patches repository is up once again.

Nothing I can do to fix this.

**Comment by admin-elvistrujanovic** [comment]
It's fixed but in the future, if this happens again for any reason, you can use this link and sublinks in it. This is the repo history that it's saved in Wayback Machine like the time travel platform for the internet so it's slow to load but every file is there in this link. Check out @reisxd https://web.archive.org/web/20221209130520/https://github.com/revanced/revanced-manager
