### ISSUE TITLE
Unknown error 

### ISSUE THREAD

**Issue by kearmau5** [reisxd/revanced-builder#578]
Bug in android version

Just normal android installation method
When i select YouTube 

**revanced-builder Version: latest 

Android 11
![Screenshot_2022-12-09-11-26-22-339_com android chrome](https://user-images.githubusercontent.com/78478945/206682164-ddb694fc-a31b-4280-9f97-c9b7b54c4aef.jpg)

**Comment by Velcorn** [comment]
The ReVanced repo got DMCA'd, so the builder won't work anymore

**Comment by reisxd** [comment]
Dupe of #576.
