### ISSUE TITLE
[featurerequest] add suport for portable java (.\jre - folder)

### ISSUE THREAD

**Issue by zedd-0** [reisxd/revanced-builder#580]
hi,

is it possible, to add a support of a portable java,
with a ".\jre"-subdirectory?

azureus/vuze or jdownloder do this.
even minecraft do this, too.

so i do not have to install java on my system.
just extract to the .\jre directory of the current app.exe and fire & forget.
:D

thx 4 read.

**Comment by shrihanDev** [comment]
I forgot to close this; it's been added!
(e3954f26544a90857eeb7a9ede62e1e545cfc9de)

**Comment by zedd-0** [comment]
hmm...
doesn't seem to work

`[builder] You don't have JDK installed.
Please get it from here: https://www.azul.com/downloads/?version=java-17-lts`

i used your "OpenJDK, Azul Zulu Build", zip file.
renamed the containing folder to "jre"
moved in the directory where "revanced-builder-win.exe" is.

is the new version already out yet?

**Comment by shrihanDev** [comment]
@zedd-0 I forgot to make a release 😅
