### ISSUE TITLE
Reddit Fails to Patch

### ISSUE THREAD

**Issue by ThisNekoGuy** [reisxd/revanced-builder#582]
**Describe the bug**

For many recent versions, as much as at least 6-7 iterations backwards from the latest Reddit apk, attempting to patch fails on both Android via Termux and on Linux; for only some versions, it does build, but throws many questionable errors that dissuade me from actually using the result.

**To Reproduce**

1. Launch the latest `revanced-builder` release
2. Pick Reddit
3. Select only "remove ads"
4. Attempt to patch any (semi-)recent apk

**revanced-builder Version:** 3.5.0

**Desktop:**

- OS: Arch Linux
- Version: N/A (Rolling-release)

**Additional context**
N/A

**Comment by reisxd** [comment]
Not a Builder issue.

**Comment by ThisNekoGuy** [comment]
@reisxd How is this not a builder issue when it presents APKs to patch that don't work? If it fails to build, how is that not a *builder* issue?

**Comment by reisxd** [comment]
> @reisxd How is this not a builder issue when it presents APKs to patch that don't work? If it fails to build, how is that not a *builder* issue?

If the patches/patcher doesn't work, then it's not a Builder issue.

**Comment by reisxd** [comment]
> That still doesn't answer the question; I asked for clarification.

You didn't also send any logs or what version you used.

**Comment by ThisNekoGuy** [comment]
1. I specified _exactly_ how to reproduce the issue and what builder version I used
2. It's easily reproducible on multiple platforms

There's no reason why this couldn't be looked into, as far as I can tell, because you refuse to tell me why this is somehow invalid.

**Comment by reisxd** [comment]
See https://github.com/revanced/revanced-cli/issues/171.
