### ISSUE TITLE
Failed to patch settings

### ISSUE THREAD

**Issue by soreikomori** [reisxd/revanced-builder#583]
When I attempt to patch in settings (and any other patch), it results in this. 
`SEVERE: settings failed:
[builder] app.revanced.patcher.patch.PatchResultError
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:340) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
[builder] at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:356) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.NullPointerException at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:64) at app.revanced.patches.youtube.misc.settings.bytecode.patch.SettingsPatch.execute(SettingsPatch.kt:24)`

To reproduce this issue, simply attempt to patch YouTube, applying any patches along with the settings patch. Happens even with administrator mode.

**revanced-builder Version:** v3.5.0
YT APK Version 17.49.34
Using Azul zulu17.38.21

**Desktop:**

- OS: Windows
- Version: 10 21H2

**Comment by reisxd** [comment]
You were warned that using an incompatible version would have consequences. Not a bug.

**Comment by soreikomori** [comment]
> You were warned that using an incompatible version would have consequences. Not a bug.

There's no warning for any incompatible version- the only warning is to not use beta YouTube apks, and this one isn't one.

As for the builder release, it's the latest one on releases.

Which one of these is incompatible?

**Comment by reisxd** [comment]
> > You were warned that using an incompatible version would have consequences. Not a bug.
> 
> There's no warning for any incompatible version- the only warning is to not use beta YouTube apks, and this one isn't one.
> 
> As for the builder release, it's the latest one on releases.
> 
> Which one of these is incompatible?

Seems like someone removed the recommended attribute, so it didn't warn you. If you were to select an unrecommended version, it'd warn you that it could possibly not work.

**Comment by soreikomori** [comment]
> > > You were warned that using an incompatible version would have consequences. Not a bug.
> > 
> > 
> > There's no warning for any incompatible version- the only warning is to not use beta YouTube apks, and this one isn't one.
> > As for the builder release, it's the latest one on releases.
> > Which one of these is incompatible?
> 
> Seems like someone removed the recommended attribute, so it didn't warn you. If you were to select an unrecommended version, it'd warn you that it could possibly not work.

I see. This is what it looked like to me.
![image](https://user-images.githubusercontent.com/102996287/207408822-aeb0ae30-2438-49b0-86a2-a311d8ab5d2b.png)

But I indeed didn't get any warning for not using a recommended version. If that was the intended action, then it's not working.

Installing with the recommended version works perfectly though, so thank you.
