### ISSUE TITLE
The 17.49.34 version compiled with Termux crashed on the Android13-based ColorOS system.

### ISSUE THREAD

**Issue by xuma-input** [reisxd/revanced-builder#586]

**Comment by reisxd** [comment]
Unrecommended version.

**Comment by xuma-input** [comment]
Is it because the mobile phone version does not support it, or the youtebu version does not support it?

**Comment by reisxd** [comment]
> Is it because the mobile phone version does not support it, or the youtebu version does not support it?

ReVanced doesn't support it.

**Comment by xuma-input** [comment]
> > Is it because the mobile phone version does not support it, or the youtebu version does not support it?
> 
> ReVanced doesn't support it.

OK, thanks for your explanation.
