### ISSUE TITLE
Twitter patching

### ISSUE THREAD

**Issue by Legitti** [reisxd/revanced-builder#592]
When I'm trying to patch any version of Twitter, all I get is this error: "Failed to scrape download link for inc/twitter/twitter.9.65.7.release.0. Please try downgrading."

**Comment by reisxd** [comment]
Seems like their version naming scheme breaks Builder. Will fix.

**Comment by reisxd** [comment]
Fixed in 7687cbf58e19bd985b1dcdf779aacb44ebeeb73a.
