### ISSUE TITLE
ReVanced Builder v2.0.0 

### ISSUE THREAD

**Issue by reisxd** [reisxd/revanced-builder#60]
I said in v1.2.0 that there won't be any major updates anymore, well... that might be a lie. 
The good thing is that I'm now working on v2.0.0, which will now include an GUI!
Currently, I'm stilll working on it, but heres an screenshot:
![image](https://user-images.githubusercontent.com/29177546/179057162-7dafb3bc-f206-4a73-8334-a3f1145e6f19.png)
I hope you guys will like this update.

**Comment by shrihanDev** [comment]
@reisxd If you wouldn't mind, could you just push whatever you're working on to a new branch (say, `gui`), so that people could contribute to it?

**Comment by reisxd** [comment]
> @reisxd If you wouldn't mind, could you just push whatever you're working on to a new branch (say, `gui`), so that people could contribute to it?

[Done!](https://github.com/reisxd/revanced-builder/tree/gui)

**Comment by thuanquangct9098** [comment]
how can i download version 2.0. I build 1.2.10 still advertising

**Comment by reisxd** [comment]
> how can i download version 2.0. I build 1.2.10 still advertising

It's in WIP, its not ready.

**Comment by shrihanDev** [comment]
> > @reisxd If you wouldn't mind, could you just push whatever you're working on to a new branch (say, `gui`), so that people could contribute to it?
> 
> [Done!](https://github.com/reisxd/revanced-builder/tree/gui)

Whoa, you overwrote the entire commit history! This is what I meant: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches#creating-a-branch-from-a-previous-commit

**Comment by reisxd** [comment]
> > > @reisxd If you wouldn't mind, could you just push whatever you're working on to a new branch (say, `gui`), so that people could contribute to it?
> > 
> > 
> > [Done!](https://github.com/reisxd/revanced-builder/tree/gui)
> 
> Whoa, you overwrote the entire commit history! This is what I meant: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches#creating-a-branch-from-a-previous-commit

Is it okay if i make that branch the main branch and the current one an another branch?

**Comment by shrihanDev** [comment]
> Is it okay if i make that branch the main branch and the current one an another branch?

I guess, but let the previous commit history be there.

> Also, I made a branch with no commits, didn't overwrote it.

Right, I meant to say that.

**Comment by shrihanDev** [comment]
Well, I have done a bit of Qt Styling in the past, so... Let me see what I can come up with (_school stuff's so borrring..._)

**Comment by reisxd** [comment]
So, about compiling the executable: 
Now, because we're using QT5 (nodegui), it creates many files, so we have to zip it and upload it from the GH Actions.
Also, the build process should be like this:
Set up NodeJS
Install modules
Run `npx nodegui-packer --init revanced-builder`, this'll initialize NodeGUI Packer.
Run `npx nodegui-packer --pack dist/`, this'll build it and put it to `deploy/platform/build`
Zip it if its Windows
Upload the files

**Comment by reisxd** [comment]
@shrihanDev 
![image](https://user-images.githubusercontent.com/29177546/179354731-0a8f60d4-fc8c-4d67-84e5-2273c8d2ce70.png)
Soo, hows this?

**Comment by shrihanDev** [comment]
@reisxd LGTM. Let this be v2.0.0. It could be improved with later versions!

**Comment by reisxd** [comment]
> @reisxd LGTM. Let this be v2.0.0. It could be improved with later versions!

We (or you) have to rewrite the GH Workflow BTW, because the building system is entirely different and needs to be ran by 3 different servers that runs Windows/Linux/macOS.
And I'll make it the main branch!

**Comment by shrihanDev** [comment]
Cool. I'll do it once I finish my school assignments (there's a crapload of them 😞)

**Comment by shrihanDev** [comment]
Hey, since you merged `gui` into `main`, why not delete `gui`?

**Comment by reisxd** [comment]
> Hey, since you merged `gui` into `main`, why not delete `gui`?

I renamed the `gui` branch to `main` and made it the main branch and for the old main I renamed it to `cli`.

**Comment by reisxd** [comment]
> Cool. I'll do it once I finish my school assignments (there's a crapload of them 😞)

I'll try to do it and make it a PR tomorrow. I'll try to make it with no knowledge (lol) so, can you review it and fix it if theres an problem?

**Comment by shrihanDev** [comment]
> > Cool. I'll do it once I finish my school assignments (there's a crapload of them 😞)
> 
> I'll try to do it and make it a PR tomorrow. I'll try to make it with no knowledge (lol) so, can you review it and fix it if theres an problem?

Sure!

**Comment by reisxd** [comment]
@shrihanDev So, sadly both Linux and MacOS failed (Linux failed because of a missing library(?) and MacOS only gives a .dmg file I guess.). So, when I'll fix both of them (I don't know how I'll fix Linux lol) I'll close this issue.

**Comment by git-Hmmm** [comment]
@reisxd The latest linux build zip contains empty folder:
![image](https://user-images.githubusercontent.com/102938585/179403409-f8803706-e583-4749-bec7-48172f9fb46a.png)

**Comment by reisxd** [comment]
> @reisxd The latest linux build zip contains empty folder. 
> 

Fixed and made a new build!

**Comment by git-Hmmm** [comment]
@reisxd If you don't mind can you please make another repo for cli tool and maintain that too, just because building stuff is mostly done on servers and on servers you know well that we can't open gui tools it's ssh only.

**Comment by reisxd** [comment]
> @reisxd If you don't mind can you please make another repo for cli tool and maintain that too, just because building stuff is mostly done on servers and on servers you know well that we can't open gui tools it's ssh only.

Theres the `cli` branch but sure, I'll maintain it when needed!
