### ISSUE TITLE
Can't install revanced-builder on Termux

### ISSUE THREAD

**Issue by HardcodedCat** [reisxd/revanced-builder#602]
**Describe the bug**
Can't install revanced-builder on Termux

**To Reproduce**

curl -sLo revanced-builder.sh https://raw.githubusercontent.com/reisxd/revanced-builder/main/android-interface.sh
chmod +x revanced-builder.sh
./revanced-builder.sh

**Screenshots**
![Screenshot_20221216-114707_Termux](https://user-images.githubusercontent.com/103902727/208138691-9253f469-a053-4a06-8271-3b1e23600078.png)

**revanced-builder Version:** Latest (v3.6.1)

**Desktop (please complete the following information):**

- OS: Android 13 - crDroid
- Hardware: Xiaomi Poco F1
- Environment: Termux-Monet 1.118.0-25

**Comment by HardcodedCat** [comment]
Almost fixed the error by manually installing the packages using yarn instead of npm

```
yarn add add app-info-parser
yarn add express
yarn add express-fileupload
yarn add ws
yarn add open
yarn add portfinder
yarn add fkill
yarn add es
```

But i've got a new error after doing this:
![Screenshot_20221216-120441_Termux](https://user-images.githubusercontent.com/103902727/208127291-5d8e0b82-057f-48bc-b80a-355111749016.png)

**Comment by HardcodedCat** [comment]
Fixed after erasing revanced-builder folder and running the script again. seems like it cannot install the needed npm packages.

**Comment by HardcodedCat** [comment]
# Temporary Workaround for installing Revanced Builder:
### 1. Completely uninstall nodejs because of latest npm chmod failures. If you try on latest npm, you'll get the following error:
```
npm ERR! errno EACCES
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
```

### Complete uninstallation steps:
```
pkg uninstall nodejs
pkg uninstall nodejs-lts
pkg uninstall yarn
rm -rf $HOME/.npm
rm -rf $HOME/node_modules
rm -rf $PATH/../lib/node_modules
```

### 2. Install nodejs-lts
```
pkg install nodejs-lts
```

### 3. Manually install all needed npm packages. If some package installation fails, install yarn witn `pkg install yarn` and do `yarn add [package name]`
```
npm install app-info-parser
npm install express
npm install express-fileupload
npm install ws
npm install open
npm install portfinder
npm install fkill
npm install es
npm install node-fetch
npm install cheerio
npm install node-fetch-progress
npm install semver
```

### 4. Run ./revanced-builder.sh and enjoy :)

**Comment by shrihanDev** [comment]
Reopening because this warrants a fix in the script. Close if it won't fix.

**Comment by HardcodedCat** [comment]
???

**Comment by SamuelSHrk** [comment]
I've gotten a similar problem, even tried to upgrade all the packages and do the command to "permanently fix" the problem, nothing changed, both with updating and installing revanced builder.

**Comment by doonoo** [comment]
For me it just fixed by installing nodejs lol. Nodejs-lts was already installed and wouldn't uninstall due to folders being present it didn't want to delete so I just installed regular nodejs and everything is smooth now. Thanks brother 👍🏾
