### ISSUE TITLE
Unable to run " ./revanced-builder.sh run "

### ISSUE THREAD

**Issue by selfmusing** [reisxd/revanced-builder#606]
**Describe the bug**

**To Reproduce**

1. Go to 'termux app'
2. Paste 'curl -sLo revanced-builder.sh https://raw.githubusercontent.com/reisxd/revanced-builder/main/android-interface.sh
chmod +x revanced-builder.sh
./revanced-builder.sh'
3. See error

**Screenshots**

**revanced-builder Version: Latest version 

- OS: DerpFest Tango
- Version: Android 13
![Screenshot_20221216-221718_Termux](https://user-images.githubusercontent.com/109387456/208148388-b1636a8f-19c4-4a08-b083-2f110fba9505.png)

**Comment by shrihanDev** [comment]
Try `pkg un nodejs* && ./revanced-builder.sh run`

**Comment by selfmusing** [comment]
💀💀💀 WARNING!!
![Screenshot_20221216-223949](https://user-images.githubusercontent.com/109387456/208151887-4d22e9f0-4465-4c06-9f00-acb0fc8dcb74.png)
![Screenshot_20221216-223955](https://user-images.githubusercontent.com/109387456/208151893-7faeee16-4040-4e37-b1f7-77264d24c826.png)
![Screenshot_20221216-224001](https://user-images.githubusercontent.com/109387456/208151896-c9ec0f6b-c433-453f-9034-be61a7d6835a.png)
![Screenshot_20221216-224005](https://user-images.githubusercontent.com/109387456/208151898-b28d4d45-78c7-4a9c-bcc0-4fab99e7ec2c.png)

**Comment by HardcodedCat** [comment]
Temporary workaround: https://github.com/reisxd/revanced-builder/issues/602#issuecomment-1355136464
