### ISSUE TITLE
🥲🥲 Why is this happening...?

### ISSUE THREAD

**Issue by selfmusing** [reisxd/revanced-builder#610]
**Describe the bug**

**To Reproduce**

1. Go to 'termux app on Android"
2. Configure Revanced builder script 
3. See this error 

**Screenshots** check below 👇👇
![Screenshot_20221218-124150](https://user-images.githubusercontent.com/109387456/208286126-b3c3de94-6715-4cf1-b82c-e94c71d56c7d.png)

**revanced-builder Version: Latest Version**
- OS: DerpFest Tango
- Version: Android 13

**Comment by reisxd** [comment]
Update.
