### ISSUE TITLE
pure black theme is unusable

### ISSUE THREAD

**Issue by KoleckOLP** [reisxd/revanced-builder#618]
**Describe the bug**
I canot select patches, in this theme,
there are just black places
I can't select a patch.

**To Reproduce**
pretty much self explainable with the screenshot provided.

**Screenshots**
![image](https://user-images.githubusercontent.com/22729896/208500211-8664ca0e-445c-4a67-bf4d-13086d94dcc5.png)

expected bahavior (but pure black):
![image](https://user-images.githubusercontent.com/22729896/208500378-3aec9d48-85ae-43e6-90b1-0a7a092b9e44.png)

**revanced-builder Version:** 3.7.0

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 21H2 22000.1335

**Additional context**
Windows 11 Virtual machine, I updated from 3.5.0 to 3.7.0

**Comment by Vucko130** [comment]
yeah. facing the same thing on Windows 11 22H2 22623.1037, ReVanced Builder 3.7.0.

**Comment by Credence473** [comment]
The patches are available when I select "Select All"
But "Predictive Back Gesture" and "Custom Theme" patches are gone from the list.

**Comment by reisxd** [comment]
Should be fixed in the latest build.
