### ISSUE TITLE
Can't find revanced apk

### ISSUE THREAD

**Issue by miloumeeloo** [reisxd/revanced-builder#62]
**Describe the bug**
Tried the noob way on linux for a rooted phone. Seems to run without error but nothing was installed and no revanced apk in the revanced folder.

**revanced-builder Version:** 
v1.2.10

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version: 22.04

**Additional context**
./revanced-builder-nodejs-linux
Downloading latest patches, integrations and cli...
[revanced-cli-2.5.3-all.jar] ✓
[revanced-patches-2.14.1.dex] ✓
[revanced-patches-2.14.1.jar] ✓
[app-release-unsigned.apk] ✓
[microg.apk] ✓
? Select the patches you want to exclude. microg-support| Allows YouTube ReVanced to run without root and under a different package name. 
(Root required), amoled| Enables pure black theme. 
WARNING: Rooted builds might or might not work.
Keep in mind that I (reisxd) cannot test it.
Downloading the YouTube APK, this'll take some time!
[youtube.apk] ✓
Download complete!
Building ReVanced, please be patient!
INFOS: Decoding resources 
INFOS: Reading dex files 
INFOS: Merging ./revanced/app-release-unsigned.apk 
INFOS: Skipping microg-support: Explicitely excluded 
INFOS: Skipping hdr-auto-brightness: Not explicitly included 
INFOS: Skipping autorepeat-by-default: Not explicitly included 
INFOS: Skipping enable-debugging: Not explicitly included 
INFOS: Skipping amoled: Explicitely excluded 
INFOS: Skipping enable-wide-searchbar: Not explicitly included 
INFOS: hide-infocard-suggestions succeeded 
INFOS: video-ads succeeded 
INFOS: general-ads succeeded 
INFOS: seekbar-tapping succeeded 
INFOS: swipe-controls succeeded 
INFOS: custom-playback-speed succeeded 
INFOS: old-quality-layout succeeded 
INFOS: hide-cast-button succeeded 
INFOS: hide-autoplay-button succeeded 
INFOS: minimized-playback succeeded 
INFOS: premium-heading succeeded 
INFOS: custom-branding succeeded 
INFOS: disable-fullscreen-panels succeeded 
INFOS: hide-shorts-button succeeded 
INFOS: disable-create-button succeeded 
INFOS: hide-watermark succeeded 
INFOS: Compiling resources 
INFOS: Writing modified dex files 
INFOS: Writing dex file classes2.dex 
INFOS: Writing dex file classes3.dex 
INFOS: Writing dex file classes.dex 
INFOS: Writing dex file classes4.dex 
INFOS: Writing dex file classes6.dex 
INFOS: Writing dex file classes5.dex 
INFOS: Writing dex file classes7.dex 
INFOS: Writing dex file classes8.dex 
INFOS: Writing resources... 
INFOS: Installing by mounting 

You now can install ReVanced and MicroG by transferring revanced/revanced.apk and revaned/microg.apk!

**Comment by reisxd** [comment]
Hi,  your YouTube should be replaced with ReVanced!

**Comment by shrihanDev** [comment]
@reisxd Apparently the success message at the end for root is a bit misleading since there's no actual APK generated, but the ReVanced base is "mounted" (`--mount`) over the YouTube APK on the system.

Thus, for root, we've to tell the user BEFORE we run the patch command (because the CLI doesn't quit when it mounts) the above.

**Comment by reisxd** [comment]
> @reisxd Apparently the success message at the end for root is a bit misleading since there's no actual APK generated, but the ReVanced base is "mounted" (`--mount`) over the YouTube APK on the system.
> 
> Thus, for root, we've to tell the user BEFORE we run the patch command (because the CLI doesn't quit when it mounts) the above.
> 

I forgot to add a check if its rooted ReVanced or not and thus causing this issue. I'll add a text in the TextEdit when building for non root + no device in v2.0.0.

Also, sorry for accidentally editing your comment!

**Comment by miloumeeloo** [comment]
> Hi, your YouTube should be replaced with ReVanced!

Hi, YT app was previously removed. Installed it again (v17.27.35) and run the patch but doesn't change anything. Still getting ads.

**Comment by reisxd** [comment]
> > Hi, your YouTube should be replaced with ReVanced!
> 
> Hi, YT app was previously removed. Installed it again (v17.27.35) and run the patch but doesn't change anything. Still getting ads.

Console output?

**Comment by miloumeeloo** [comment]
> > > Hi, your YouTube should be replaced with ReVanced!
> > 
> > 
> > Hi, YT app was previously removed. Installed it again (v17.27.35) and run the patch but doesn't change anything. Still getting ads.
> 
> Console output?

Same as first post
