### ISSUE TITLE
Stuck on this, i have reinstalled Termux

### ISSUE THREAD

**Issue by musman555** [reisxd/revanced-builder#624]
![Screenshot_2022-12-21-11-53-40-239_com termux](https://user-images.githubusercontent.com/54684618/208840446-af3c7d15-a4cf-43dc-b615-532dc859c16c.jpg)

I have been trying to install Revanced via Termux, but i get this message/error each time.

**Comment by shrihanDev** [comment]
Run `pkg up` and then use `./revanced-builder.sh`.

**Comment by CyclicPoet44782** [comment]
use termux from fdroid not from play store

**Comment by shrihanDev** [comment]
Closing because stale.
