### ISSUE TITLE
Error patching return youtube dislikes on all platforms on builder v3.7.0

### ISSUE THREAD

**Issue by furopi** [reisxd/revanced-builder#626]
I get this error while trying to patch return youtube dislikes, be it on windows 11, android 13 or ubuntu (via wsl). Hope this can be fixed... Keep up the good work! 👍

[builder] SEVERE: return-youtube-dislike failed:
[builder] app.revanced.patcher.patch.PatchResultError at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:429) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.NullPointerException at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:55) at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:24) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425) ... 16 more

**Comment by devasto98** [comment]
same thing happened to me. trying different YT version but still not working

**Comment by furopi** [comment]
> same thing happened to me. trying different YT version but still not working

So at least I'm not alone, it seems... Ty!

**Comment by reisxd** [comment]
Not a Builder issue.

**Comment by furopi** [comment]
Wait, but what is the issue then?
