### ISSUE TITLE
Can't build ReVanced

### ISSUE THREAD

**Issue by entaytion** [reisxd/revanced-builder#63]
**Why does it say there's no YouTube, even though I have it installed?**
- **revanced-builder Version:** 1.12.10
- **Desktop:** win10 x64

**Issue:**
```
Downloading latest patches, integrations and cli...
[app-release-unsigned.apk] ✓
[microg.apk] ✓
? Select the patches you want to exclude. swipe-controls| Adds volume and brightness swipe controls. , microg-support|
Allows YouTube ReVanced to run without root and under a different package name. (Root required)
WARNING: Rooted builds might or might not work.
Keep in mind that I (reisxd) cannot test it.
An error occured.
Error: YouTube is not installed on your device
It's needed for rooted ReVanced.
    at getYTVersion (C:\snapshot\revanced-builder\index.js:305:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\snapshot\revanced-builder\index.js:556:25

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...
```

I have YouTube installed on my phone, but the problem is that when I connect it, it says it's not available. Could it be a problem if it's not installed as a system one?

**Comment by reisxd** [comment]
> **Why does it say there's no YouTube, even though I have it installed?**
> 
> * **revanced-builder Version:** 1.12.10
> * **Desktop:** win10 x64
> 
> **Issue:**
> 
> ```
> Downloading latest patches, integrations and cli...
> [app-release-unsigned.apk] ✓
> [microg.apk] ✓
> ? Select the patches you want to exclude. swipe-controls| Adds volume and brightness swipe controls. , microg-support|
> Allows YouTube ReVanced to run without root and under a different package name. (Root required)
> WARNING: Rooted builds might or might not work.
> Keep in mind that I (reisxd) cannot test it.
> An error occured.
> Error: YouTube is not installed on your device
> It's needed for rooted ReVanced.
>     at getYTVersion (C:\snapshot\revanced-builder\index.js:305:11)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async C:\snapshot\revanced-builder\index.js:556:25
> 
> Please make an issue at https://github.com/reisxd/revanced-builder/issues.
> Press any key to exit...
> ```
> 
> I have YouTube installed on my phone, but the problem is that when I connect it, it says it's not available. Could it be a problem if it's not installed as a system one?

Try running `adb shell dumpsys package com.google.android.youtube` and try search for `versionName=`.

**Comment by entaytion** [comment]
I tried reinstalling YouTube and it worked. Thanks for the tip!

**Comment by entaytion** [comment]
Although, no, it didn't help. After entering this command, nothing happens.
![image](https://user-images.githubusercontent.com/57830743/179369248-871e5988-37d7-4861-af1a-dd7308bf5d80.png)
