### ISSUE TITLE
no-root return-yt-dislike patcher error

### ISSUE THREAD

**Issue by tomekwwa** [reisxd/revanced-builder#631]
After ReV Builder upgrade to 3.7.0 and when i'm using newest patches for yt 17.49.37 every time i get patcher error when it tries to add return-yt-dislike. Any sugestions?
![Screenshot_2022-12-28-09-49-53-236_com android chrome](https://user-images.githubusercontent.com/80062158/209786275-a79e0cc8-c622-4515-a895-c077f3c14385.jpg)
![Screenshot_2022-12-28-09-49-57-696_com android chrome](https://user-images.githubusercontent.com/80062158/209786283-9bddd763-d877-42bd-bd65-f3e2f369ae11.jpg)

**Comment by reisxd** [comment]
#621
