### ISSUE TITLE
Using Termux Builder fails to patch Return of Youtube Dislike.

### ISSUE THREAD

**Issue by fedonr** [reisxd/revanced-builder#632]
Bug : Return of Youtube Dislike Patch keeps on failing while using the Builder via Termux (Android : FDroid Version)

Brief : Return of Youtube Dislike : Fails (Termux Builder)
                                                             Success ( Revanced Manager)

Somehow the same builder is forked for Revanced Extended, there the Return of Youtube Dislike works.
So it works in forked Builder for Revanced extended but not in the main builder for core Revanced.

OS : Android 12 (Termux : Fdroid)
Revanced Builder : v3.7.1

**Comment by reisxd** [comment]
#626.

**Comment by fedonr** [comment]
Yes, I checked the issue #626, but I still updated this issue to let you know that somehow the same builder is forked for Revanced Extended by inotia00 and there the Return of Youtube Dislike patches successfully with Termux Builder.

**Comment by shrihanDev** [comment]
inotia00's ReVanced Extended works because it probably uses a custom patches bundle (haven't looked into it, so just a guess).

**Comment by fedonr** [comment]
Gotta thanks, but what about Return of Youtube Dislike, as stated in #626 , it fails on all platforms and it's same with v3.7.1 and as reisxd suggested its not a builder issue. Then how to resolve it?

> inotia00's ReVanced Extended works because it probably uses a custom patches bundle (haven't looked into it, so just a guess).
