### ISSUE TITLE
Installation fail. 

### ISSUE THREAD

**Issue by NUCLEARxDYNAMO** [reisxd/revanced-builder#634]
I have very less to no knowledge on openssl and npm as I am just a CSS dev, I don't seem to understand what the problem here is. The reason I am using this is because the official revanced app doesn't seem to work for me. Is this a problem with the dependencies? Would you give me a good set of lines to run after I reinstall termux to reset it, so I can get it work with no hassles? Thank you for revanced-builder btw ♥️. 

![Screenshot_2023-01-05-21-14-08-814_org mozilla firefox](https://user-images.githubusercontent.com/73421617/210822254-db9cf2c9-de34-48d9-8ca6-b13245a43e41.jpg)
![Screenshot_2023-01-05-21-14-17-254_com termux](https://user-images.githubusercontent.com/73421617/210822268-1ec34b6c-15ce-4aee-a378-74465bd105b7.jpg)

**Comment by shrihanDev** [comment]
Are you using a VPN, or a IP-level AdBlocker of some sorts? This shouldn't happen unless there's something really wrong with GitHub.

Try to reinstall some stuff, like so:
```bash
pkg update && pkg upgrade -y
pkg uninstall nodejs* -y
pkg install nodejs-lts
cd ~/revanced-builder
node .
```

**Comment by NUCLEARxDYNAMO** [comment]
Yep instead of doing that, I did a hard reset of termux and updated and did the normal install and works pretty well, thank you.
