### ISSUE TITLE
Getting error on update builder

### ISSUE THREAD

**Issue by Karthikn341** [reisxd/revanced-builder#635]
**Describe the bug**
![Screenshot_2023-01-05-22-48-40-614_com termux](https://user-images.githubusercontent.com/91846131/210841474-5044f1ce-c92c-4517-b63c-5d1e2652e4cc.jpg)

Getting error while updating

**Comment by shrihanDev** [comment]
It seems there is some issues with GitHub or your internet. Try doing it later.
