### ISSUE TITLE
QUESTION: Are there any commands/launch `-arguments` supported to pass into the builder to disable it automatically launching the default browser...?

### ISSUE THREAD

**Issue by Spacellary** [reisxd/revanced-builder#637]
Are there any commands/launch `-arguments` supported to pass into the builder to disable it automatically launching the default browser window upon opening or to select a different browser instead of the default?

That's a possible behavior when using the docker-compose method but I couldn't with the built executable from releases...

I have the habit of opening it from the Terminal/Shortcut and running my own commands after to open set directories and *localhost* in my browser of choice, so that's the motivation behind this.

###### System: Windows 11 | PowerShell 7

**Comment by reisxd** [comment]
The `--no-open` flag.

**Comment by Spacellary** [comment]
Thank you!
