### ISSUE TITLE
"you excluded all patches"

### ISSUE THREAD

**Issue by skhrlx** [reisxd/revanced-builder#64]
The bug is just saying that i excluded all patches, and im not doing it, i already tied to se

I open the exe and them just press "a" to  select all, and then, enter, and it happens

v.1.2.10

- OS: w10
![Untitled](https://user-images.githubusercontent.com/85849948/179372136-604ad4d6-93d4-44af-baf7-21815fbdea45.png)

**Comment by theleanbow** [comment]
The error speaks for itself
You excluded all patches
If you read carefully, it said select the patches you want to exclude
And you selected all of them
To fix, just don't select anything (don't press `a`) and just hit enter
It should work now

**Comment by skhrlx** [comment]
> The error speaks for itself You excluded all patches If you read carefully, it said select the patches you want to exclude And you selected all of them To fix, just don't select anything (don't press `a`) and just hit enter It should work now

Oh, sorry for that, english it's not my primary language and I read it wrong 😓 I noticed my mistake only now
