### ISSUE TITLE
[builder]  An error occured: TypeError: Invalid Version: 271.0.05

### ISSUE THREAD

**Issue by paulpoyyayil** [reisxd/revanced-builder#648]
![Screenshot (25)](https://user-images.githubusercontent.com/65621035/218024733-4d4e8b62-691e-4feb-844e-dd7172e55e96.png)

**Comment by caneleex** [comment]
for context, revanced now has a patch for Instagram ads. this is the versioning system they use.

**Comment by ciaociaoweb** [comment]
Still the same.

**Comment by Zoey2936** [comment]
![grafik](https://github.com/reisxd/revanced-builder/assets/75573284/2fb3b874-bfdd-4992-b2db-8312a20111f1)
still does not work from me (binary built from main branch)

**Comment by Zoey2936** [comment]
works now with main branch
