### ISSUE TITLE
FetchError in Browser interface

### ISSUE THREAD

**Issue by pratikmullick** [reisxd/revanced-builder#650]
Revanced builder does not continue after sending out the following error message:
```
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at /data/data/com.termux/files/home/revanced-builder/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPackages (/data/data/com.termux/files/home/revanced-builder/wsEvents/getApp.js:19:20)
    at async getPatches (/data/data/com.termux/files/home/revanced-builder/wsEvents/getApp.js:40:16)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:175:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
```

System: Android v13.0 Non-rooted running Termux downloaded from F-Droid.

![Screenshot_20230212_195223_Chrome](https://user-images.githubusercontent.com/41203200/218316929-dd678fc9-13ec-4663-a92a-e439cff458f1.jpg)
![Screenshot_20230212_195242_Chrome](https://user-images.githubusercontent.com/41203200/218316950-14675fed-8256-4693-abb1-5bf7d753b25b.jpg)

**Comment by reisxd** [comment]
APKMirror is down.

**Comment by gregist** [comment]
So currently is there any workaround for this issue? @reisxd

**Comment by reisxd** [comment]
No. If APKMirror is down then you can't do anything.
