### ISSUE TITLE
Error while compiling YouTube and YouTube Music app - Unknown chunk type '200

### ISSUE THREAD

**Issue by darkvpier** [reisxd/revanced-builder#653]
I am facing an issue while trying to compile the YouTube and YouTube Music app. Every time I try to compile the app, I receive the following error message:

"[builder] WARNING: aapt2 W 02-22 01:26:52 18917 18917] Unknown chunk type '200'."

I have tried cleaning and rebuilding the project, but the issue persists. I suspect this may be an issue with AAPT2.

Could someone please assist in resolving this issue so that I can continue with the development of the app? Any help would be greatly appreciated.

Steps to Reproduce:

Select the version and patches of the YouTube or YouTube Music app.
Attempt to compile the app.
Observe the error message: "[builder] WARNING: aapt2 W 02-22 01:26:52 18917 18917] Unknown chunk type '200'."
Expected behavior:
The YouTube and YouTube Music app should compile successfully without any errors.

Actual behavior:
The app fails to compile due to the error message: "[builder] WARNING: aapt2 W 02-22 01:26:52 18917 18917] Unknown chunk type '200'."
![Screenshot_20230222-012720~2](https://user-images.githubusercontent.com/84262682/220448786-b45326e9-34a6-43bb-993d-14625f33d735.png)

**Comment by reisxd** [comment]
Read.
