### ISSUE TITLE
Missing youtube recommended version 

### ISSUE THREAD

**Issue by X4V1** [reisxd/revanced-builder#662]
**Describe the bug**
The version 18.03.36 is too old and not visible in the list of YouTube versions available. 

**To Reproduce**
Try to patch YouTube app and see that that the version 18.03.36 is not listed. 

**Screenshots**
Not needed

**revanced-builder Version:** latest

**Desktop (please complete the following information):**

- OS: Andrlld
- Version: 13

**Comment by reisxd** [comment]
Not an issue with Builder.
