### ISSUE TITLE
Getting error while extracting zip

### ISSUE THREAD

**Issue by theleanbow** [reisxd/revanced-builder#67]
**Describe the bug**
Getting error while extracting zip file
**To Reproduce**

1.Extract file(using 7zip)
**Screenshots**

**revanced-builder Version:** [e.g. v2.0.0]

**Desktop (please complete the following information):**

- OS: [Windows]
- Version: [10]

![image](https://user-images.githubusercontent.com/66841515/179405200-335d9dda-43c4-4d76-8ab5-d82b6433858a.png)

**Comment by reisxd** [comment]
Thats an... warning?
