### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by RabahX** [reisxd/revanced-builder#671]
Describe the bug
Can't build YouTube ReVanced

To Reproduce

Go to 'Select the app to patch'
Select 'YouTube ReVanced'
Click on "Continue"

![ReVanced Builder by Reis - Personne 1 - Microsoft​ Edge 3_20_2023 11_57_28 AM](https://user-images.githubusercontent.com/64314390/226855112-d18f310e-a550-4402-9b22-f9159f5d71df.png)

**revanced-builder Version: v3.8.0

**Desktop (please complete the following information): **

OS: Windows
Version: 11

**Comment by shrihanDev** [comment]
Delete everything and start from scratch.
