### ISSUE TITLE
Revanced-builder on Android does not let you select the recommended version to download.


### ISSUE THREAD

**Issue by Ekim0789** [reisxd/revanced-builder#674]
**Describe the bug**
Cannot select the recommended version to patch when using revanced-builder for Android 

**To Reproduce**

1. Run revanced-builder.sh in Termux
2. Select YouTube to patch
3. Select the patches you want
4. Under "select the version you want to download" when you scroll all the way down the oldest version you can select is 18.06.39, but the recommended version is 18.05.40

This did not happen in revanced-builder 3.8.0, only after I updated to 3.9.0

**Screenshots**
![Screenshot_20230325-164219.png](https://user-images.githubusercontent.com/25417912/227743606-dc43929a-c98e-48f1-9878-daf0c1531fef.png)

![Screenshot_20230325-164230.png](https://user-images.githubusercontent.com/25417912/227743611-8b2d106e-8546-43a7-85c6-7ab4bab4e87c.png)

**revanced-builder Version:** [e.g. v1.2.10]
3.9.0

**Desktop (please complete the following information):**
Android 13

**Additional context**
Pixel 6 Pro

**Comment by Skcyte** [comment]
Confirmed this as well in Windows 
![image](https://user-images.githubusercontent.com/18594247/227752123-70c0ae17-1b9c-4813-b521-d86c88f7de3e.png)

**Comment by reisxd** [comment]
Same issue as before, the recommended version is too old.
