### ISSUE TITLE
[builder] An error occured.

### ISSUE THREAD

**Issue by b0unty1** [reisxd/revanced-builder#678]
**Describe the bug**
-----------------------
Error: EBUSY: resource busy or locked, unlink '\\?\e:\ANDROID\revanced_builder\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\revanced-builder\wsEvents\patchApp.js:28:3)
    at Socket.<anonymous> (C:\snapshot\revanced-builder\wsEvents\patchApp.js:186:53)

**To Reproduce**
-------------------
Every-time i try to build with these files

**revanced-builder Version:**
--------------------------------
revanced-builder-win.exe version 3.9.0

**Desktop (please complete the following information):**
---------------------------------------------------------------
- OS: Windows 10 Enterprise LTSC
- Version: 21H2 19044.2728

**Additional context**
i use the following files:
--------------------------
com.google.android.youtube v18.05.40
revanced-cli-v2.20.1.jar
revanced-integrations-v0.101.0.apk
revanced-patches-v2.167.0.jar
revanced-patches-v2.167.0.json

with the following settings:
------------------------------
{
  "sources": {
    "patches": "revanced/revanced-patches",
    "integrations": "revanced/revanced-integrations"
  },
  "patches": [
    {
      "name": "com.google.android.youtube",
      "patches": [
        "client-spoof",
        "copy-video-url",
        "custom-video-buffer",
        "custom-video-speed",
        "disable-fullscreen-panels",
        "disable-player-popup-panels",
        "disable-shorts-on-startup",
        "disable-zoom-haptics",
        "general-ads",
        "hdr-auto-brightness",
        "hide-cast-button",
        "hide-player-buttons",
        "hide-video-action-buttons",
        "hide-watermark",
        "microg-support",
        "minimized-playback",
        "old-quality-layout",
        "predictive-back-gesture",
        "premium-heading",
        "remember-video-quality",
        "remove-screenshot-restriction",
        "sponsorblock",
        "spoof-signature-verification",
        "spoof-wifi-connection",
        "swipe-controls",
        "video-ads"
      ]
    }
  ]
}

**Comment by rsmyst** [comment]
+1 facing same issue when trying ot patch nova.

**Comment by mi875** [comment]
I'm facing the same issue too.

**Comment by b0unty1** [comment]
Back to report
I updated my openJDK 17 LTS to the latest official build and I no longer have any crashes
I've also modified my settings to:
"patches": [
        "client-spoof",
        "disable-fullscreen-panels",
        "disable-shorts-on-startup",
        "disable-zoom-haptics",
        "enable-wide-searchbar",
        "general-ads",
        "hdr-auto-brightness",
        "hide-cast-button",
        "hide-player-buttons",
        "hide-video-action-buttons",
        "microg-support",
        "minimized-playback",
        "predictive-back-gesture",
        "premium-heading",
        "remember-playback-speed",
        "remember-video-quality",
        "remove-screenshot-restriction",
        "sponsorblock",
        "spoof-wifi-connection",
        "swipe-controls",
        "video-ads"
      ]
