### ISSUE TITLE
the system cannot find the file specified

### ISSUE THREAD

**Issue by NightmareMare** [reisxd/revanced-builder#682]
**Describe the bug**
the build stops after compiling resources

**To Reproduce**

1 Go to 'Select the app to patch'
2 Select 'YouTube'
3 Upload 'com.google.android.youtube_18.05.40-1535903168_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com'
3 Click on 'Continue'

[builder] INFORMACI�N: Reading dex files
[builder] INFORMACI�N: Decoding AndroidManifest.xml only, because resources are not needed
[builder] INFORMACI�N: Skipping always-autorepeat: Manually excluded
[builder] INFORMACI�N: Skipping comments: Manually excluded
[builder] INFORMACI�N: Skipping custom-video-buffer: Manually excluded
[builder] INFORMACI�N: Skipping debugging: Manually excluded
[builder] INFORMACI�N: Skipping disable-auto-captions: Manually excluded
[builder] INFORMACI�N: Skipping disable-shorts-on-startup: Manually excluded
[builder] INFORMACI�N: Skipping export-all-activities: Manually excluded
[builder] INFORMACI�N: Skipping hdr-auto-brightness: Manually excluded
[builder] INFORMACI�N: Skipping hide-album-cards: Manually excluded
[builder] INFORMACI�N: Skipping hide-artist-card: Manually excluded
[builder] INFORMACI�N: Skipping hide-autoplay-button: Manually excluded
[builder] INFORMACI�N: Skipping hide-breaking-news-shelf: Manually excluded
[builder] INFORMACI�N: Skipping hide-captions-button: Manually excluded
[builder] INFORMACI�N: Skipping hide-crowdfunding-box: Manually excluded
[builder] INFORMACI�N: Skipping hide-email-address: Manually excluded
[builder] INFORMACI�N: Skipping hide-endscreen-cards: Manually excluded
[builder] INFORMACI�N: Skipping hide-info-cards: Manually excluded
[builder] INFORMACI�N: Skipping hide-my-mix: Manually excluded
[builder] INFORMACI�N: Skipping hide-player-buttons: Manually excluded
[builder] INFORMACI�N: Skipping hide-seekbar: Manually excluded
[builder] INFORMACI�N: Skipping hide-shorts-button: Manually excluded
[builder] INFORMACI�N: Skipping hide-timestamp: Manually excluded
[builder] INFORMACI�N: Skipping hide-watermark: Manually excluded
[builder] INFORMACI�N: Skipping predictive-back-gesture: Manually excluded
[builder] INFORMACI�N: Skipping premium-heading: Manually excluded
[builder] INFORMACI�N: Skipping remember-playback-speed: Manually excluded
[builder] INFORMACI�N: Skipping spoof-app-version: Manually excluded
[builder] INFORMACI�N: Skipping spoof-wifi-connection: Manually excluded
[builder] INFORMACI�N: Skipping swipe-controls: Manually excluded
[builder] INFORMACI�N: Skipping tablet-mini-player: Manually excluded
[builder] INFORMACI�N: Merging C:\Users\Salas Sof�a\Downloads\revanced\revanced-integrations-v0.101.0.apk
[builder] INFORMACI�N: Deleting existing resource cache directory
[builder] GRAVE: Failed to delete existing resource cache directory
[builder] INFORMACI�N: Decoding resources
[builder] INFORMACI�N: client-spoof succeeded
[builder] INFORMACI�N: copy-video-url succeeded
[builder] INFORMACI�N: custom-branding succeeded
[builder] INFORMACI�N: custom-video-speed succeeded
[builder] INFORMACI�N: disable-fullscreen-panels succeeded
[builder] INFORMACI�N: disable-player-popup-panels succeeded
[builder] INFORMACI�N: disable-zoom-haptics succeeded
[builder] INFORMACI�N: downloads succeeded
[builder] INFORMACI�N: enable-wide-searchbar succeeded
[builder] INFORMACI�N: general-ads succeeded
[builder] INFORMACI�N: hide-cast-button succeeded
[builder] INFORMACI�N: hide-create-button succeeded
[builder] INFORMACI�N: hide-floating-microphone-button succeeded
[builder] INFORMACI�N: hide-video-action-buttons succeeded
[builder] INFORMACI�N: hide-watch-in-vr succeeded
[builder] INFORMACI�N: microg-support succeeded
[builder] INFORMACI�N: minimized-playback succeeded
[builder] INFORMACI�N: old-quality-layout succeeded
[builder] INFORMACI�N: open-links-externally succeeded
[builder] INFORMACI�N: remember-video-quality succeeded
[builder] INFORMACI�N: remove-player-button-background succeeded
[builder] INFORMACI�N: remove-screenshot-restriction succeeded
[builder] INFORMACI�N: return-youtube-dislike succeeded
[builder] INFORMACI�N: seekbar-tapping succeeded
[builder] INFORMACI�N: sponsorblock succeeded
[builder] INFORMACI�N: spoof-signature-verification succeeded
[builder] INFORMACI�N: theme succeeded
[builder] INFORMACI�N: video-ads succeeded
[builder] INFORMACI�N: Compiling resources
[builder] ADVERTENCIA: C:\Users\Salas Sofía\Downloads\.\revanced-cache\res: error: failed to open directory: El sistema no puede encontrar el archivo especificado. (2).
[builder] brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SALASS~1\AppData\Local\Temp\brut_util_Jar_73836818448275759171610736541325542528.tmp, compile, --dir, C:\Users\Salas Sof�a\Downloads\.\revanced-cache\res, --legacy, -o, C:\Users\Salas Sof�a\Downloads\.\revanced-cache\build\resources.zip] at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365) at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619) at app.revanced.patcher.Patcher.save(Patcher.kt:126) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SALASS~1\AppData\Local\Temp\brut_util_Jar_73836818448275759171610736541325542528.tmp, compile, --dir, C:\Users\Salas Sof�a\Downloads\.\revanced-cache\res, --legacy, -o, C:\Users\Salas Sof�a\Downloads\.\revanced-cache\build\resources.zip] at brut.util.OS.exec(OS.java:99) at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361) ... 13 more

**revanced-builder Version:** [e.g. v1.2.10]
3.9.0 

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10 Pro

**Additional context**
Failed to delete existing resource cache directory pops up too. I don't have this: %localappdata%\apktool.

**Comment by shrihanDev** [comment]
Delete everything and start from scratch.
