### ISSUE TITLE
Error when patching

### ISSUE THREAD

**Issue by anonid64** [reisxd/revanced-builder#687]
I have an error when build, as in below image
`[builder] Error: Invalid or corrupt jarfile /app/revanced-builder/revanced/revanced-cli-v2.20.1.jar`

![image](https://user-images.githubusercontent.com/34296806/232078380-70653186-0ece-4c0b-aabd-32f4afa8408f.png)

**Comment by shrihanDev** [comment]
Delete everything and start from scratch.
