### ISSUE TITLE
Revanced Builder fails to open on Termux

### ISSUE THREAD

**Issue by ArijitBh** [reisxd/revanced-builder#691]
**Describe the bug**
Revanced Builder throws up the following error while running the CLI on Termux

```

./revanced-builder.sh: line 127: cd: /data/data/com.termux/files/home/revanced-builder || exit: No such file or directory
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module '/data/data/com.termux/files/home'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.13.0
```

**To Reproduce**

1. Open Termux
2. Enter `./revanced-builder.sh`
3. Get error
4. Retry with `./revanced-builder.sh update && ./revanced-builder.sh`
5. Get error again

**Screenshots**
![Screenshot_20230416-091054-468](https://user-images.githubusercontent.com/102469938/232265219-285f5c3a-0235-4bf8-a57c-619179ae4f7c.png)

**revanced-builder Version:** [e.g. v3.70]

**Mobile Phone (please complete the following information):**

- OS: ANDROID
- Version: 12

**Comment by Indiana630** [comment]
same, some solution?

**Comment by shrihanDev** [comment]
Re-download `revanced-builder.sh` by following the instructions; it has been fixed.
