### ISSUE TITLE
Fastlist.exe?

### ISSUE THREAD

**Issue by Serizon** [reisxd/revanced-builder#694]
An error occured:Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT at ChildProcess._handle.onexit (node:internal/child_process:283:19) at onErrorNT (node:internal/child_process:476:16) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by Aphyxia** [comment]
I got this error too but I took the signed apk file in the cache folder and it worked regardless.

**Comment by mecha-mann** [comment]
> I got this error too but I took the signed apk file in the cache folder and it worked regardless.

I am getting the same error. Can you please tell me how it works. I'm really bad with these things!!

**Comment by Aphyxia** [comment]
> I am getting the same error. Can you please tell me how it works. I'm really bad with these things!!
In the same folder as the builder, there's a revance-cache folder. Take the revanced_signed.apk from there to your device and install.

**Comment by mecha-mann** [comment]
> > I am getting the same error. Can you please tell me how it works. I'm really bad with these things!!
> 
> In the same folder as the builder, there's a revance-cache folder. Take the revanced_signed.apk from there to your device and install.

Thanks for your quick reply. I found the folder and the "revanced_signed.apk" inside it. It worked. Thanks again :)

**Comment by TgZ39** [comment]
> > I am getting the same error. Can you please tell me how it works. I'm really bad with these things!!
> 
> In the same folder as the builder, there's a revance-cache folder. Take the revanced_signed.apk from there to your device and install.

And that will have all the patches I apply?

**Comment by Serizon** [comment]
great answer actually! 
on my pc when i tried , i couldnt find revanced_cache ,it couldnt work.
But for those who want 100% chances of it working , use docker (trust me it works100%)
I am closing this issue and hope it helps
