### ISSUE TITLE
Download video

### ISSUE THREAD

**Issue by Emanuele-1998** [reisxd/revanced-builder#695]
Hi congratulations for your work really very useful even if the patches are not very updated compared to the various versions, I use termux to install the most recent version of youtube but I can't find the patch for downloading the videos, in fact if I click on the icon for downloading the video I get an alert written org.schabi.newpipe is not installed, how can I fix it? 

Screen: https://postimg.cc/nXktsnyD/be15e414

**Comment by parknich081** [comment]
Install NewPipe via [F-Droid](https://f-droid.org/)

**Comment by Emanuele-1998** [comment]
it would be useful to integrate directly into patches without installing newpipe
