### ISSUE TITLE
Incorrect instructions on https://revanced.net/help

### ISSUE THREAD

**Issue by steve3p0** [reisxd/revanced-builder#698]
Hi, I am not sure if this is the appropriate place, but the instructions at https://revanced.net/help are a little off:

There is no "ReVanced Manager" to download and install referenced in step 1 and 2 below:

> For Non-Root:
> If your Android device is Non-Rooted, follow these instructions to install the app.
> 
> 1. Download and install the latest ReVanced Manager from our website.
> 2. Open the ReVanced Manager app and tap on the blue arrow at the lower right corner.
> 3. Install ReVanced microG. (If you want to sign in to your Google account, this app is required to install)
> 4. Next, install YouTube ReVanced or YouTube Music ReVanced as your desire, then log in to your Google account and enjoy!

I installed "YouTube ReVanced" first and then "ReVanced MicroG", followed by "YouTube Music ReVanced".  Everything appears to be working fine.

**Comment by mooms06** [comment]
This is not an official site, the official is https://github.com/revanced
