### ISSUE TITLE
Unhandled Rejection

### ISSUE THREAD

**Issue by Lolen10** [reisxd/revanced-builder#7]
In the newest version, **after I selected the excluded patches**, I get the following error:
```
Unhandled Rejection
Reason: FetchError: request to https://www.apkmirror.comundefined/ failed, reason: getaddrinfo ENOTFOUND www.apkmirror.comundefined
Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...
```

**Comment by reisxd** [comment]
> In the newest version, **after I selected the excluded patches**, I get the following error:
> 
> ```
> Unhandled Rejection
> Reason: FetchError: request to https://www.apkmirror.comundefined/ failed, reason: getaddrinfo ENOTFOUND www.apkmirror.comundefined
> Please make an issue at https://github.com/reisxd/revanced-builder/issues.
> Press any key to exit...
> ```

Hey, can you post the full console output?

**Comment by Lolen10** [comment]
![image](https://user-images.githubusercontent.com/24716055/177002914-e1f6ab4f-0d59-45fd-8951-b9f09be98db8.png)

**Comment by reisxd** [comment]
> ![image](https://user-images.githubusercontent.com/24716055/177002914-e1f6ab4f-0d59-45fd-8951-b9f09be98db8.png)

Weird, I cannot reproduce with v1.1.1.

**Comment by Lolen10** [comment]
Could it be related to wrong Node.js version? I installed version 18.4.0.

**Comment by reisxd** [comment]
> Could it be related to a wrong Node.js version? I installed version 18.4.0.

It shouldn't matter, try putting `console.log(ytVersion);` to https://github.com/reisxd/revanced-builder/blob/main/index.js#L119 and it should log your YouTube version.

**Comment by shrihanDev** [comment]
@reisxd Apparently, the error is because `apklink` is undefined, somehow?

```js
const apkLink = apkPage('a[rel="nofollow"]').first().attr('href');

  console.log("Downloading the YouTube APK, this'll take some time!");
  await dloadFromURL(
    `https://www.apkmirror.com${apkLink}`,
    './revanced/youtube.apk'
  );
  return console.log('Download complete!');
}
```
See: https://github.com/reisxd/revanced-builder/blob/67137decdf6b9af14a3de0f5b197cbedfdf0fef4/index.js#L147

**Comment by reisxd** [comment]
> @reisxd Apparently, the error is because `apklink` is undefined, somehow?
> 
> See:
> 
> https://github.com/reisxd/revanced-builder/blob/67137decdf6b9af14a3de0f5b197cbedfdf0fef4/index.js#L147-L154

I think its not the `apkLink` but its the `pageLink`

**Comment by reisxd** [comment]
I think @Lolen10 got Cloudflare'd, making revanced-builder not able to scrape. Or something else that I don't even know.

**Comment by Lolen10** [comment]
![image](https://user-images.githubusercontent.com/24716055/177003778-5476c12c-3dfb-4c24-a3f7-780f0bea4922.png)
Weird. If I don't select any patches it works...

**Comment by reisxd** [comment]
> ![image](https://user-images.githubusercontent.com/24716055/177003778-5476c12c-3dfb-4c24-a3f7-780f0bea4922.png) Weird. If I don't select any patches it works...

Ok, it might be the thing i said before, [try doing what i said here](https://github.com/reisxd/revanced-builder/issues/7#issuecomment-1172899942)
(I couldn't reproduce it though, I don't know why (yes, i excluded microg-support))

**Comment by Lolen10** [comment]
![image](https://user-images.githubusercontent.com/24716055/177004212-5d3b6a24-bc6c-42a0-8098-9bb3f347ff4e.png)
There.

**Comment by reisxd** [comment]
> ![image](https://user-images.githubusercontent.com/24716055/177004212-5d3b6a24-bc6c-42a0-8098-9bb3f347ff4e.png) There.

I see. Thats why it fails.

**Comment by reisxd** [comment]
Or it didnt....
Regex moment (worked in my browser, didnt in nodejs)

**Comment by reisxd** [comment]
> Got this error. It worked fine on my `W:\Downloads` folder, but not after I moved it to `C:\Program Files (x86)\ReVanced Builder` (running as admin) or `C:\ReVanced Builder` (non admin) ![image](https://user-images.githubusercontent.com/20804322/177383264-450c10e3-4aa8-471c-be94-390c20426f4a.png) Nor `W:\ReVanced Builder`, `W:\Downloads\ReVanced Builder` or even `W:\Downloads`
> 
> EDIT: The issue also didn't come from me renaming the file to `Youtube ReVanced Builder.exe`
I have no idea why that happens, maybe because of spaces?
Still, that shouldn't happen just because theres a space in the folder name.

**Comment by hyoretsu** [comment]
@reisxd I think the error comes from the binary, cloning the repo and running starts downloading YT just fine. (Though I'm running the .exe from Windows and the Node from Linux)

**Comment by CalebJohnathen** [comment]
I am still getting this error with both the binary and building from source

**Comment by CalebJohnathen** [comment]
It only happens when trying to build the root versions of YouTube or YouTube Music
