### ISSUE TITLE
Error with builder version v3.9.1 

### ISSUE THREAD

**Issue by mooms06** [reisxd/revanced-builder#700]
**Describe the bug**
I've used the builder version v3.9.1 and youtube apk 18.05.40, at the end I have the following message displayed:

[builder] An error occured:
Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT
at ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:476:16)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

Previous version was working fine with the same settings.

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/25405517/233027398-02f57c07-31de-429f-af64-7d108b6b7e8e.png)

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

Windows 10
**Additional context**

**Comment by ahmadsyarbini** [comment]
> Same issue on my end with v3.9.1, using 3.9.0 does not have this error.

3.9.0 also have this error. Both with admin and without admin run.

**Comment by Arahaon** [comment]
I get the same

**Comment by mooms06** [comment]
> > Same issue on my end with v3.9.1, using 3.9.0 does not have this error.
> 
> 3.9.0 also have this error. Both with admin and without admin run.

Indeed, now both have the error, but it was not the case earlier, as I successfully builded with it.

**Comment by suspiciousRaccoon** [comment]
same error with v3.9.1 and apk version 18.08.37

**Comment by parknich081** [comment]
I am also having this issue #709

**Comment by rajen77** [comment]
I can confirm, this is the problem for me too.

**Comment by mosfetish** [comment]
And for me. Very frustrating. Windows 10 latest.

**Comment by suspiciousRaccoon** [comment]
> In the meantime, you can use the [ReVanced Manager](https://www.reddit.com/r/revancedapp/comments/xlcny9/revanced_manager_guide_for_dummies/) to build the apk on Android, it works.

can't do that from my device unfortunately, the patching fails due to armv7 architecture

**Comment by mooms06** [comment]
Indeed. 
I also have a _revanced.apk_ in the _revanced_ folder, after comparison it's the same as _revanced_signed.apk_.

**Comment by Keiishu** [comment]
Running the app without packaging it works. I suspect it's related to `ps-list`, used by `fkill`, added in c2707da6996a7b7f3a172a31e6888660a8f839f4

**Comment by plasma3000** [comment]
For me, v3.9.0 does not have this error

**Comment by chollangimanojkumar** [comment]
Yup same issue with windows 11

**Comment by Helix13Underscore** [comment]
Just got the same issue on Windows 10

**Comment by mosfetish** [comment]
Just to confirm what several others have said.

In the revanced folder, revanced.apk and VancedMicroG[version here].apk seem to work just fine.

Install MicroG. Note: it won't show up in apps after install. Then install revanced and log in to your google account. Works fine.

Inconvenient error, though. Thanks a bunch to those on this issue thread and to the developer. Insane app.

**Comment by Legitti** [comment]
Same issue here.

**Comment by Lau893** [comment]
> Same issue on my end with v3.9.1, using 3.9.0 does not have this error.

i changed it and its the same, you changed something else?

**Comment by Zerogoki00** [comment]
> > Same issue on my end with v3.9.1, using 3.9.0 does not have this error.
> 
> i changed it and its the same, you changed something else?

@Lau893 try version 3.8.0, works with no problems

**Comment by mooms06** [comment]
3.9.1 is working, just use the revanced.apk in the revanced folder, as already said.

Oh, and please stop replying to this issue with meaningless messages, every time someone reply it sends an e-mail.

**Comment by iamzahid** [comment]
The error its showing its just a bug you will still get working APK File in the Folder with name Revanced.apk 
Just don't use all Patches Available on the Builder I used only to Block Sponsor and General Ads and then Build App

**Comment by parknich081** [comment]
@iamzahid you cant do that if you are doing a rooted build

**Comment by usafle** [comment]
I'm going to chime in as well with the same error on the newest version

**Comment by mooms06** [comment]
What ? v3.9.1 released 04/18 is still the latest version.

**Comment by Legitti** [comment]
Happens with all the apps, not just YouTube

**Comment by shrihanDev** [comment]
Fixed in 375c863, hopefully.
