### ISSUE TITLE
Recommended youtube apk version not on list

### ISSUE THREAD

**Issue by MIC132** [reisxd/revanced-builder#702]
**Describe the bug**
I'm using the version of builder that you run from termux on android. I'm not sure if that's still supported, but it does show as the latest 3.9.1
The problem I have is that in the step where you select which apk version you want to use (when you are not providing your own .apk file), the list shows a few most recent versions, but the recommended version (18.05.40) is not on the list (it's too old, I'm guessing?).

**revanced-builder Version:** [e.g. v3.9.1]

**Desktop (please complete the following information):**

- OS: Android
- Version: 12

**Comment by mooms06** [comment]
V3.9.1 was released to fix the issue, you have to change page, it's on page 2 right now.
