### ISSUE TITLE
Failure trying to build revanced on pc.

### ISSUE THREAD

**Issue by Madarox** [reisxd/revanced-builder#704]
Revanced builder fails on my pc using opera gx and chrome ; 
![image](https://user-images.githubusercontent.com/131321621/233234623-ea982149-6575-489e-9423-2aa923a02add.png)
My pc specs : 
AMD Ryzen 5 PRO 4650G with Radeon Graphics   4.00 GHz.
16,0 Go of ram.
French language.
Windows 10 Professionnel
Version 22H2
Build 19045.2846
Windows Feature Experience Pack 120.2212.4190.0

**Comment by Dumanotucghe** [comment]
![image](https://user-images.githubusercontent.com/78786149/233251367-9c199c45-1f72-44e7-8f12-f85ec5a96ee4.png)
Edge:

**Comment by Phantom0013** [comment]
![image](https://user-images.githubusercontent.com/77114925/233343407-f3fa96e2-a659-4d0f-b494-2244930a25a0.png)
Same here

**Comment by Madarox** [comment]
Version [3.9.0](https://github.com/reisxd/revanced-builder/releases/tag/v3.9.0) works properly using opera gx.
![image](https://user-images.githubusercontent.com/131321621/233347808-9148742d-1577-4034-af0f-12b3af51ccce.png)

**Comment by KoleckOLP** [comment]
```
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
```

crashes for me as well, and doing the same build in 3.9.0 works just fine.

**Comment by Phantom0013** [comment]
![image](https://user-images.githubusercontent.com/77114925/233368609-e48cbe90-40d8-4870-80b6-a16865b20990.png)
Also This is something happening every time aswell (that error)

**Comment by Madarox** [comment]
> ![image](https://user-images.githubusercontent.com/77114925/233367450-f5462e77-f758-4633-b7c8-28219bc840d2.png) Tried with 3.9.0 in OperaGX. Still Failing

trying moving the build to a different location other then system drive also execute in administrator mode.

**Comment by KoleckOLP** [comment]
I have my builder in the root of C drive (just like I do with 3.9.0) and I run it as admin, still the same issue.

**Comment by bbksleazy** [comment]
[same problem,](https://www.reddit.com/r/revancedapp/comments/12t6voe/using_reisxds_revancedbuilder_i_get_this_error/) writing here so i get the fixed notification

**Comment by ITESaurabh** [comment]
+1

**Comment by b0unty1** [comment]
+1

**Comment by KoleckOLP** [comment]
![image](https://user-images.githubusercontent.com/22729896/234203631-157465ad-aad0-4d23-a094-67157f0aeeed.png)
this is still a problem, I have to use version 3.9.0 or I am not able to build.

**Comment by Songgumdhk** [comment]
Just ignore the error, and go to the revanced folder. There you can see the revanced.apk file. you can transfer this file to android and install it. It will work without any problem.

**Comment by bbksleazy** [comment]
Is the issue even fixed yet?
