### ISSUE TITLE
issue while patching.

### ISSUE THREAD

**Issue by nik447n** [reisxd/revanced-builder#705]
![Screenshot 2023-04-20 193044](https://user-images.githubusercontent.com/113538066/233390084-70e80afd-b2cb-4afb-9f4d-30b4ece823b3.jpg)

**Comment by bbksleazy** [comment]
Exact same issue [posted this on reddit](https://www.reddit.com/r/revancedapp/comments/12t6voe/using_reisxds_revancedbuilder_i_get_this_error/) to see if i can find any results there.

**Comment by nik447n** [comment]
> Exact same issue [posted this on reddit](https://www.reddit.com/r/revancedapp/comments/12t6voe/using_reisxds_revancedbuilder_i_get_this_error/) to see if i can find any results there.

I tried using older version to build but that build crashes when you open the app.

**Comment by ITESaurabh** [comment]
+1

**Comment by nik447n** [comment]
Build using Android app (revanced manager). It is working fine.

**Comment by SangeethSujith** [comment]
Yea iam also facing this issue

**Comment by bbksleazy** [comment]
He closed this as not planned, does that mean he's not gonna fix it?

**Comment by nik447n** [comment]
There are others reporting similar issues so he may have closed some

**Comment by bbksleazy** [comment]
sn

**Comment by bbksleazy** [comment]
I tried using mobile to build revanced but when i get into the patching section it gets stuck on a line which says, "... 16 more". My phone did time out a couple of times. Does your phone timing out or switching to other apps on your phone effect the process.

**Comment by nik447n** [comment]
Which version are you building?
 
I didn't face any problems with mobile builder. My device is Samsung f23 5g

**Comment by bbksleazy** [comment]
I simply followed this, https://github.com/reisxd/revanced-builder/wiki/How-to-use-revanced-builder-on-Android

**Comment by nik447n** [comment]
Lol that's soo much work. Just download this on Android and build using it. 

https://github.com/reisxd/revanced-builder/releases/download/v3.9.1/revanced-builder-win.exe

**Comment by bbksleazy** [comment]
Ain't that the whole reason why this post was created, this doesn't work, or does it work now?

**Comment by nik447n** [comment]
No this post was for pc builder. The link I shared you is of Android builder. The pc builder is having issue but the Android builder worked fine for me.

**Comment by bbksleazy** [comment]
Yh uou must've sent the wrong link or somthing, cuz that clealy says .exe at the end not .apk

**Comment by nik447n** [comment]
Sorry that's was my mistake... Here : 

https://github.com/revanced/revanced-manager/releases/download/v0.0.57/revanced-manager-v0.0.57.apk

**Comment by bbksleazy** [comment]
Oh you're talking about the official revanced manager.  Yh im using the vanced builder because the revanced manager doesn't work. When i select my patches, and the recommended version and install it, the revanced app instantly crashes when opening, so i cant use it

**Comment by SangeethSujith** [comment]
the issue is still not fixed
