### ISSUE TITLE
Maintenance of the CLI and GUI

### ISSUE THREAD

**Issue by shrihanDev** [reisxd/revanced-builder#71]
At this point, the GUI version is present in `main`, while the code for the last CLI version, v1.2.10. is in `cli`. Say, there's a weird bug arising from GH API changes and/or APKMirror changing its markup, then:

- If you decide to maintain CLI **and** GUI: Make the changes in BOTH the branches, and run the GitHub action workflow for BOTH of them.
- If you decide to maintain only GUI: Make the change in `gui`, but then `cli` will remain there stagnant.

I want to ask, how are you going to tackle this mess? Will you maintain both the versions or just the GUI? In my opinion, I think the CLI version is pointless atm because this tool is targeted for layman users, so the GUI is better, far better. I don't think I can deduce any use cases for the CLI...

**Comment by reisxd** [comment]
> At this point, the GUI version is present in `main`, while the code for the last CLI version, v1.2.10. is in `cli`. Say, there's a weird bug arising from GH API changes and/or APKMirror changing its markup, then:
> 
> - If you decide to maintain CLI **and** GUI: Make the changes in BOTH the branches, and run the GitHub action workflow for BOTH of them.
> - If you decide to maintain only GUI: Make the change in `gui`, but then `cli` will remain there stagnant.
> 
> I want to ask, how are you going to tackle this mess? Will you maintain both the versions or just the GUI? In my opinion, I think the CLI version is pointless atm because this tool is targeted for layman users, so the GUI is better, far better. I don't think I can deduce any use cases for the CLI...

CLI might be useful for people that wants to update ReVanced quickly with a script or people who maked those cloud baed scripts. But yes, you are right, this is a mess. I don't think I should make new releases for CLI because CLI is now meant for people who knows what they're doing.

**Comment by shrihanDev** [comment]
> CLI might be useful for people that wants to update ReVanced quickly with a script or people who make those cloud based scripts

Yeah, but wouldn't they be better off using the revanced-cli itself? I mean, individual people would definitely have their own fixed set of choices, so their patch command is just `java -jar CLI.jar -a APK.apk -b Patches.jar -m Integrations.apk -i/-e ...`.

> I don't think I should make new releases for CLI

What if APKMirror decides to change their markup of the download pages? You'd have to update the ripping code for that too, and that will demand a release.

**Comment by reisxd** [comment]
> > CLI might be useful for people that wants to update ReVanced quickly with a script or people who make those cloud based scripts
> 
> Yeah, but wouldn't they be better off using the revanced-cli itself? I mean, individual people would definitely have their own fixed set of choices, so their patch command is just `java -jar CLI.jar -a APK.apk -b Patches.jar -m Integrations.apk -i/-e ...`.

>> for people who wants to update ReVanced quickly
I do know that they can use revanced-cli but they could also use the CLI version for automatically downloading the latest files and the latest YT APK
> 
> > I don't think I should make new releases for CLI
> 
> What if APKMirror decides to change their markup of the download pages? You'd have to update the ripping code for that too, and that will demand a release.

>> for people who knows what they're doing
