### ISSUE TITLE
Stable Error?? (Not Beta)

### ISSUE THREAD

**Issue by MarshMeadow** [reisxd/revanced-builder#711]
![image](https://user-images.githubusercontent.com/88599122/233871544-de2bd178-83c8-42ea-9933-0d5be77b4266.png)

**Comment by crok** [comment]
+1
The very same is happening on a Win10 PC I'm using at work.
The same builder release version still works flawlessly on my Manjaro.

**Comment by mooms06** [comment]
https://github.com/reisxd/revanced-builder/issues/700
