### ISSUE TITLE
Error with building tiktok

### ISSUE THREAD

**Issue by GremlineQ** [reisxd/revanced-builder#718]
I wanted to build a tiktok, at first everything worked, then it broke down, for a while it seemed to work again and finally broke całkowicie at the end 

probably to get this problem just try to build tiktok, i don't want to check every option 

links that started to break 

[builder] INFO: Decoding resources
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
[builder] WARNING: Cant find 9patch chunk in file: "o/gm.9.png". Renaming it to *.png.
.........(it was repeated many times)
[builder] WARNING: Cant find 9patch chunk in file: "o/gm.9.png". Renaming it to *.png.

[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a0.xml:3: error: not well-formed (invalid token).
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a0.xml: error: file failed to compile. WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a1.xml:2: error: not well-formed (invalid token). WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a1.xml: error: file failed to compile. (the same template was repeated that it was badly formatted, too much of it so it doesn't copy everything)

here's what he wrote at the end
[builder] INFO: Reading dex files
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
[builder] INFO: Skipping enable-android-debugging: Manually excluded
[builder] INFO: Skipping sim-spoof: Manually excluded
[builder] INFO: Skipping spoof-wifi-connection: Manually excluded
[builder] INFO: Merging /data/data/com.termux/files/home/revanced-builder/revanced/revanced-integrations-v0.104.0.apk
[builder] INFO: Deleting existing resource cache directory
[builder] INFO: Decoding resources
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
[builder] WARNING: Cant find 9patch chunk in file: "o/gm.9.png". Renaming it to *.png.
.........(it was repeated many times)
[builder] WARNING: Cant find 9patch chunk in file: "o/gm.9.png". Renaming it to *.png.
[builder] SEVERE: change-package-name failed:
[builder] app.revanced.patcher.patch.PatchResultError: Invalid package name at app.revanced.patches.all.misc.packagename.patch.ChangePackageNamePatch.execute(ChangePackageNamePatch.kt:20) at app.revanced.patches.all.misc.packagename.patch.ChangePackageNamePatch.execute(ChangePackageNamePatch.kt:11) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] INFO: disable-login-requirement succeeded
[builder] INFO: downloads succeeded
[builder] INFO: export-all-activities succeeded
[builder] INFO: feed-filter succeeded
[builder] INFO: fix-google-login succeeded
[builder] INFO: hide-ads succeeded
[builder] INFO: playback-speed succeeded
[builder] INFO: predictive-back-gesture succeeded
[builder] INFO: remove-screenshot-restriction succeeded INFO: settings succeeded
[builder] INFO: show-seekbar succeeded
[builder] INFO: Compiling resources
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a0.xml:3: error: not well-formed (invalid token).
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a0.xml: error: file failed to compile. WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a1.xml:2: error: not well-formed (invalid token). WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a1.xml: error: file failed to compile.
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a2.xml:2: error: not well-formed (invalid token). WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a2.xml: error: file failed to compile.
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a3.xml:2: error: not well-formed (invalid token).
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a3.xml: error: file failed to compile. WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a4.xml:2: error: not well-formed (invalid token).
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a4.xml: error: file failed to compile.
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a5.xml:2: error: not well-formed (invalid token).
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a5.xml: error: file failed to compile.
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a6.xml:3: error: not well-formed (invalid token). WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a6.xml: error: file failed to compile.
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a7.xml:3: error: not well-formed (invalid token).
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a7.xml: error: file failed to compile. WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a8.xml:3: error: not well-formed (invalid token).
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/a8.xml: error: file failed to compile.
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/ac.xml:2: error: not well-formed (invalid token).
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res/anim/ac.xml: error: file failed to compile.
[builder] brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/home/revanced-builder/revanced/aapt2, compile, --dir, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res, --legacy, -o, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/build/resources.zip] at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365) at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619) at app.revanced.patcher.Patcher.save(Patcher.kt:126) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/home/revanced-builder/revanced/aapt2, compile, --dir, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/res, --legacy, -o, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/build/resources.zip] at brut.util.OS.exec(OS.java:99) at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361) ... 13 more

Version 3.9.1

OS: Android 13 with termux

**Comment by Legitti** [comment]
Same issue here, also same with Twitter & Twitch.
