### ISSUE TITLE
youtube build failed

### ISSUE THREAD

**Issue by way2harshraj090** [reisxd/revanced-builder#719]
An error occured:Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENTat ChildProcess._handle.onexit (node:internal/child_process:283:19)at onErrorNT (node:internal/child_process:476:16)at process.processTicksAndRejections (node:internal/process/task_queues:82:21)Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by MirazMac** [comment]
Facing the same issue

**Comment by way2harshraj090** [comment]
> Facing the same issue
It is happening because it fails to rename the file.
Actually I got a temporary solution for that.
Just go to revanced_cache folder and use the revanced_signed.apk
