### ISSUE TITLE
Error while building an app (was building YouTube)

### ISSUE THREAD

**Issue by Coherent4269** [reisxd/revanced-builder#726]
[builder] An error occured:
Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT 
at ChildProcess._handle.onexit (node:internal/child_process:283:19) 
at onErrorNT (node:internal/child_process:476:16) 
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

![Error](https://user-images.githubusercontent.com/132146540/235306380-b6bce238-b178-4813-b0bf-d0778016e8df.png)

revanced-builder Version: v3.9.1

- OS: Windows
- Version: 11

Additional Context
used the recommended version of the apk which matches the patches version too.

**Comment by TgZ39** [comment]
Same here
