### ISSUE TITLE
Error just when patching

### ISSUE THREAD

**Issue by Jonathandm77** [reisxd/revanced-builder#729]
**Describe the bug**
An error when patching

**To Reproduce**

Only upload the YouTube image from apkMirror and select all

**Screenshots**
![image](https://user-images.githubusercontent.com/115222209/235350028-f90ef528-97d5-44ce-91c0-592c4879e5d3.png)

**revanced-builder Version:** [e.g. v1.2.10]
v 3.9.1

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]
-Windows 10

**Additional context**

**Comment by CaptainKnox** [comment]
Getting the same issue on v3.9.1

Steps followed:
Selected all patches for YouTube.
Downloaded the APK from the patcher and tried to patch.

Same while trying to patch InShorts following the same steps.

**Comment by Jonathandm77** [comment]
If you only get the apk, even with the error, and you install it works.
Thanks for trying to solve my problem.
