### ISSUE TITLE
Patching Youtube Error

### ISSUE THREAD

**Issue by jonathanholbrook** [reisxd/revanced-builder#730]
Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENTat ChildProcess._handle.onexit (node:internal/child_process:283:19)at onErrorNT (node:internal/child_process:476:16)at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by LarsMudde** [comment]
I'm having the same error.
