### ISSUE TITLE
Gets an error when a patch is disabled

### ISSUE THREAD

**Issue by tzuyu18** [reisxd/revanced-builder#83]
**Describe the bug**
When all patches are selected the apk are successfuly created and transfered to my internal storage but when a patch is not selected (any patch) i get this error 

An error occured.
Error: Couldn't find the device. Please plug in the device.
    at /data/data/com.termux/files/home/revanced-builder-cli/index.js:582:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Screenshots**
![Screenshot_20220722-043026_Termux](https://user-images.githubusercontent.com/82486600/180309589-f84c8efa-1756-4fcf-8dcb-269c74b0c716.jpg)
![Screenshot_20220722-043009_Termux](https://user-images.githubusercontent.com/82486600/180309621-2b835f7f-36de-4556-ad37-a386bebf06d1.jpg)

**revanced-builder Version:** [e.g. v1.2.10]
V2.0.2
**Desktop (please complete the following information):**

- OS: android (Samsung Note 20 Ultra)
- Version: 12
- termux from fdroid

**Comment by reisxd** [comment]
You shouldn't exclude the patches that require root, and also why are you excluding that many patches?

**Comment by ronin08** [comment]
It's his choice to exclude any patch. Insteading of fixing the issue, you're telling him to adjust according to your buggy tool. Not ethical imo!
And there is not a single patch which is root specific.

**Comment by reisxd** [comment]
> It's his choice to exclude any patch. Insteading of fixing the issue, you're telling him to adjust according to your buggy tool. Not ethical imo!
> And there is not a single patch which is root specific.

Excluding microg-support and hide-cast-button (dependent of microg-support, won't be excluded  if you don't exclude microg-support) requires root and you'll need to mount ReVanced and that currently *not* possible right now. It's not buggy, it was meant to run on computers and now it's on Android, and there won't be root support until I figure out how mounting works.

**Comment by ronin08** [comment]
but i am using non root 17.26.35 with ```hide-cast-button``` patch applied

**Comment by reisxd** [comment]
> but i am using non root 17.26.35 with ```hide-cast-button``` patch applied

It won't be excluded until you exclude microg-support, which requires root to be excluded.

**Comment by ronin08** [comment]
why? so

**Comment by tzuyu18** [comment]
OMG, I'm so sorry I thought the option is to include. So I checked most of the features 😅
Please close this. Thank you for the reply!
