### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by ronin08** [reisxd/revanced-builder#85]
To make this process of building straight forward, try automating this with github-actions(workflow).

It is demonstrated in this repo: https://github.com/n0k0m3/revanced-build-template

**Comment by reisxd** [comment]
You want a workflow to build ReVanced, in a tool that builds ReVanced automatically...

Also, no, I don't like to get DMCAd.

**Comment by ronin08** [comment]
the built apk uploaded in the releases will only be visible to the user who will run on their forked/private repository.
There is no chance of getting DMCAd

**Comment by bs2kbs2k** [comment]
can you lock this as resolved

**Comment by reisxd** [comment]
You litterally gave an repository that does the *exact* same thing that you said.

**Comment by ronin08** [comment]
ok. fine.
