### ISSUE TITLE
Some patches excluded even though unselected

### ISSUE THREAD

**Issue by SahibzadaAliNoor** [reisxd/revanced-builder#86]
**Describe the bug**
After the recent cli patch update (2.7.1) some patches like HDR control and swipe control get excluded with the message "not explicitly included". 

**To Reproduce**
Start the app. Download the latest CLI and other files along with the latest YouTube apk.

The aforementioned patches don't get added although they aren't highlighted on the exclusion table.

**Screenshots**
![Screenshot_20220726-001456](https://user-images.githubusercontent.com/54205958/180856676-c34e62f3-4836-4a7e-8fcb-762b1f173088.png)

**revanced-builder Version:** 

2.0.2

**Desktop

Hp spectre 

- OS:
Win 10

**Comment by reisxd** [comment]
You can only exclude patches and not include them, and those patches are excluded by default from the patches.

**Comment by SahibzadaAliNoor** [comment]
I could add swipe controls previously to YT revanced. Is this a new development?

**Comment by SahibzadaAliNoor** [comment]
Ps thank you.

**Comment by reisxd** [comment]
> I could add swipe controls previously to YT revanced. Is this a new development?

Because most people hated it, it's now disabled by default.

**Comment by SahibzadaAliNoor** [comment]
Ahhhh I didn't know that. Don't follow the discord channel. Thank you very very much for all your hard work, you have certainly made it a breeze to build the apk for revanced. 

Warm regards,
Sahibzada Ali Noor
