### ISSUE TITLE
No such file or directory on builder-cli android

### ISSUE THREAD

**Issue by OmegaSunkey** [reisxd/revanced-builder#87]
**Describe the bug**
Revanced Builder doesnt create revanced.apk 

**To Reproduce**

1. Execute node . and do anything like a normal user would do, but on android
2. error appears at end of compiling

**Screenshots**

![20220725_174154.jpg](https://user-images.githubusercontent.com/94485936/180886636-42ef10d8-79c6-429d-be54-dabf73607856.jpg)

**revanced-builder Version:v1.0.0**

**Desktop (please complete the following information):**

- OS: Android, One Ui 2
- Version: 10

**Comment by reisxd** [comment]
This only happens when your phones architecture is not either armv7 or arm64.
Could you run a node REPL (with `node`) and type these:
```js
const { arch } = require('os');
arch();
```
then send the log here?

**Comment by OmegaSunkey** [comment]
returns 'arm'

**Comment by reisxd** [comment]
> returns 'arm'

Weird, [arm (armv7) is getting handled by the tool](https://github.com/reisxd/revanced-builder/blob/5dbc4572328421af138e670152ece5b05f2682a2/index.js#L404).

Can you try running aapt2?

**Comment by OmegaSunkey** [comment]
aapt2 downloaded by the toom or the one built in termux?

**Comment by reisxd** [comment]
> aapt2 downloaded by the toom or the one built in termux?

Wait, did you install aapt2 from Termux using `pkg` or `apt`?

**Comment by OmegaSunkey** [comment]
i dont remember i did, maybe some other tool did it.

**Comment by OmegaSunkey** [comment]
weird though, when i search in pkg it doesnt appear as installed but is indeed installed

**Comment by OmegaSunkey** [comment]
doing aapt2 version throws its made by ReVanced

**Comment by reisxd** [comment]
> i dont remember i did, maybe some other tool did it. 

Try either doing `rm /data/data/com.termux/files/usr/bin/aapt2` or `apt remove aapt2` then re running the tool.

**Comment by reisxd** [comment]
> doing aapt2 version throws its made by ReVanced

Now that is actually very weird, it installed aapt2 successfully but somehow something happens and aapt2 can't compile resources...

**Comment by shrihanDev** [comment]
> > doing aapt2 version throws its made by ReVanced
> 
> Now that is actually very weird, it installed aapt2 successfully but somehow something happens and aapt2 can't compile resources...

Whoops, I can reproduce the same problem on `arm64` too.

**Comment by reisxd** [comment]
> > > doing aapt2 version throws its made by ReVanced
> > 
> > Now that is actually very weird, it installed aapt2 successfully but somehow something happens and aapt2 can't compile resources...
> 
> Whoops, I can reproduce the same problem on `arm64` too. 

This gets weirder. On my phone, I cannot reproduce:
```bash
~ $ whereis aapt2
aapt2: /data/data/com.termux/files/usr/bin/aapt2
~ $ rm /data/data/com.termux/files/usr/bin/aapt2
~ $ cd revanced-builder-cli
~/revanced-builder-cli $ node .
Downloading required files...
[revanced-patches-2.25.1.dex] ✓
[revanced-patches-2.25.1.jar] ✓
[app-release-unsigned.apk] ✓
[microg.apk] ✓
revanced-builder has detected that you are using Android (Termux)!
JDK is already installed.
Couldn't find aapt2, installing...
[aapt2.zip] ✓
The architecture is arm64
aapt2 has been installed.
? Select the patches you want to exclude.
? Select a YT version to download. 17.29.34
Downloading the YouTube APK, this'll take some time!
[youtube.apk] ✓
Download complete!
Building ReVanced, please be patient!
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging ./revanced/app-release-unsigned.apk
INFO: Skipping compact-header: Not explicitly included
INFO: Skipping swipe-controls: Not explicitly included
INFO: Skipping enable-wide-searchbar: Not explicitly included
INFO: Skipping force-vp9-codec: Not explicitly included
INFO: Skipping always-autorepeat: Not explicitly included
INFO: Skipping enable-debugging: Not explicitly included
INFO: Skipping hdr-auto-brightness: Not explicitly included
INFO: seekbar-tapping succeeded
INFO: minimized-playback succeeded
INFO: amoled succeeded
INFO: disable-create-button succeeded
INFO: hide-cast-button succeeded
INFO: return-youtube-dislike succeeded
INFO: hide-autoplay-button succeeded
INFO: premium-heading succeeded
INFO: custom-branding succeeded
INFO: disable-fullscreen-panels succeeded
INFO: old-quality-layout succeeded
INFO: hide-shorts-button succeeded
INFO: hide-watermark succeeded
INFO: sponsorblock succeeded
INFO: microg-support succeeded
INFO: custom-playback-speed succeeded
INFO: default-video-quality succeeded
INFO: video-ads succeeded
INFO: general-ads succeeded
INFO: hide-infocard-suggestions succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes6.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes8.dex
INFO: Writing resources...
INFO: Aligning revanced_raw.apk to revanced_aligned.apk
INFO: Signing revanced_aligned.apk to revanced_signed.apk
INFO: Copying revanced_signed.apk to revanced.apk
INFO: Finished

Copying ReVanced and MicroG to phones storage...
You now can install ReVanced and MicroG! Check /storage/emulated/0/
Press any key to exit...
```

**Comment by shrihanDev** [comment]
@reisxd So, I tried to manually run the `java -jar .....` command, and this is what I get towards the end:

```
INFO: Compiling resources
WARNING: error: resource 'drawable/$$avd_anim__1__0' has invalid entry name '$$avd_anim__1__0.
WARNING: error: resource 'drawable/$$avd_anim__1__1' has invalid entry name '$$avd_anim__1__1.
WARNING: error: resource 'drawable/$$avd_anim__2__0' has invalid entry name '$$avd_anim__2__0.
WARNING: error: resource 'drawable/$$avd_anim__2__1' has invalid entry name '$$avd_anim__2__1.
WARNING: error: resource 'drawable/$$avd_anim__3__0' has invalid entry name '$$avd_anim__3__0.
WARNING: error: resource 'drawable/$$avd_anim__3__1' has invalid entry name '$$avd_anim__3__1.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__10__0' has invalid entry name '$$sud_fourcolor_progress_bar__10__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__11__0' has invalid entry name '$$sud_fourcolor_progress_bar__11__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__12__0' has invalid entry name '$$sud_fourcolor_progress_bar__12__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__1__0' has invalid entry name '$$sud_fourcolor_progress_bar__1__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__2__0' has invalid entry name '$$sud_fourcolor_progress_bar__2__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__3__0' has invalid entry name '$$sud_fourcolor_progress_bar__3__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__4__0' has invalid entry name '$$sud_fourcolor_progress_bar__4__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__5__0' has invalid entry name '$$sud_fourcolor_progress_bar__5__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__6__0' has invalid entry name '$$sud_fourcolor_progress_bar__6__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__7__0' has invalid entry name '$$sud_fourcolor_progress_bar__7__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__8__0' has invalid entry name '$$sud_fourcolor_progress_bar__8__0.
WARNING: error: resource 'drawable/$$sud_fourcolor_progress_bar__9__0' has invalid entry name '$$sud_fourcolor_progress_bar__9__0.
WARNING: error: resource 'drawable/$avd_anim__0' has invalid entry name '$avd_anim__0.
WARNING: error: resource 'drawable/$avd_anim__1' has invalid entry name '$avd_anim__1.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/bin/aapt2, compile, --dir, /data/data/com.termux/files/home/revanced-builder/revanced-cache/res, --legacy, -o, /data/data/com.termux/files/home/revanced-builder/revanced-cache/build/resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:372)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:199)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:159)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/bin/aapt2, compile, --dir, /data/data/com.termux/files/home/revanced-builder/revanced-cache/res, --legacy, -o, /data/data/com.termux/files/home/revanced-builder/revanced-cache/build/resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:368)
        ... 13 more
```
And when I run the `aapt2` command, I get the same thing, except it's not a WARNING, but an error.

**Comment by reisxd** [comment]
Weird... I seriously have no idea why this happens.

**Comment by shrihanDev** [comment]
Okay, now I tried to use the `aapt2` built by ReVanced (from reisxd/revanced-cli-termux) and the `aapt2` command succeeded. I was using the one built by Termux.

![Screenshot_2022-07-26-23-44-50-58](https://user-images.githubusercontent.com/54971391/181081260-a191fbc7-f457-430e-b56f-1dade7e56717.png)
It's so uncanny, eerie, unnatural and preternatural!

**Comment by reisxd** [comment]
> Okay, now I tried to use the `aapt2` built by ReVanced (from reisxd/revanced-cli-termux) and the `aapt2` command succeeded. I was using the one built by Termux.
> 
> ![Screenshot_2022-07-26-23-44-50-58](https://user-images.githubusercontent.com/54971391/181081260-a191fbc7-f457-430e-b56f-1dade7e56717.png)
> It's so uncanny, eerie, unnatural and preternatural!

Oh, that explains it. ReVanceds Aapt2 is acutally modified to probably fix some issue(?). And using the actual aapt2 from the Termux repo(or any) is broken.

**Comment by reisxd** [comment]
> Hmm. I guess then the issue will be closed when we actually force-use ReVanced's `aapt2` instead of checking if it exists.

Good idea, because:
![IMG_20220726_212326.jpg](https://user-images.githubusercontent.com/29177546/181082870-c00fb752-cdaf-467b-b0ca-ae27706d07d0.jpg)

**Comment by randomguy273** [comment]
how to force-use the revanced aapt2?

**Comment by reisxd** [comment]
> how to force-use the revanced aapt2?
> what commands i use?

It already does itself.

**Comment by randomguy273** [comment]
i got the same problem i don't know how fix it
![Screenshot_20220727-175701_Termux](https://user-images.githubusercontent.com/110130703/181370826-66b78336-e3a2-40ec-a8f8-1e98b9d63f9e.jpg)

**Comment by shrihanDev** [comment]
@randomguy273 Download revanced-builder again. Use the commands from the Wiki.

**Comment by ableoj** [comment]
I'm also recieving this issue.
Tried removing aapt2, and re-downloading revanced. Didn't fix.
I'm running Android, Termux.

**Comment by randomguy273** [comment]
I download it using the steps from wiki again, no fixes :/, on pkg update i put all default again, its right?

**Comment by randomguy273** [comment]
Hi, i tried to download again follow the steps from wiki, no fixes :/, on pkg update i put all on default, its right?

**Comment by profesaurus** [comment]
I also followed the wiki for installing on Android and I'm getting this error.

**Comment by reisxd** [comment]
@ableoj @randomguy273 @profesaurus Hey, can you all try building again?
