### ISSUE TITLE
App shuts down immediately

### ISSUE THREAD

**Issue by melvas6** [reisxd/revanced-builder#88]
I installed the youtube apk on the phone first and then installed the revanced apk of the same version (17.29.34). But when I open revanced, it immediately shutsdown. Kindly help.

**Comment by reisxd** [comment]
This issue is caused by microg-support patch being broken and is now fixed (no new release for now by the ReVanced team though, use an older version of YouTube).

**Comment by melvas6** [comment]
> ~Try using an older apk.~ Wait, are you building rooted or not?

Non-rooted
