### ISSUE TITLE
Youtube music app crashing after building root device

### ISSUE THREAD

**Issue by animekid51** [reisxd/revanced-builder#94]
Youtube music app crashes after building. I am using Redmi note 8 with miui Redmi Note 8 EEA V12.5.5.0.RCOEUXM with root dont really matter what patch and version of the app.

**Comment by animekid51** [comment]
Youtube music app works with microg patch, if i want to install without microg and root access every time app crash when app shows youtube music logo.

**Comment by reisxd** [comment]
Keep in mind that I cannot test rooted building. So, I cannot reproduce.

**Comment by UltraHQ** [comment]
> Keep in mind that I cannot test rooted building. So, I cannot reproduce.

Hi, just wanted to say I have the exact same problem.
I'm ready to help, if you need someone testing.
