### ISSUE TITLE
Error when copying ReVanced and microG

### ISSUE THREAD

**Issue by lotusdroid** [reisxd/revanced-builder#97]
![Screenshot_20220728-111009_Termux](https://user-images.githubusercontent.com/106517171/181418682-bde426a3-e6c0-4169-a53a-37e3de5abce6.png)

**Comment by reisxd** [comment]
@shrihanDev Can this be an issue with your PR?

**Comment by reisxd** [comment]
Tested with the latest commit and I cannot reproduce.

**Comment by shrihanDev** [comment]
@reisxd I cannot reproduce also:
![Screenshot_20220728-152053_Termux](https://user-images.githubusercontent.com/54971391/181476910-7cdf9e40-6225-46a5-ac70-11c01ced0e16.jpg)

**Comment by lotusdroid** [comment]
Why I cannt build it

**Comment by reisxd** [comment]
> Why I cannt build it

Try reinstalling it, see the wiki.

**Comment by PandoraHayami** [comment]
Reinstalled, everything up-to-date, and still happens, at least with YT-Music, normal YT works fine, haven't tried the rest. 

![Screenshots_2022-07-29-08-40-43](https://user-images.githubusercontent.com/79670265/181784165-db5992e2-13dc-4462-a93b-9c3ec6a307e3.png)

**Comment by lotusdroid** [comment]
reinstalled but also face this issue
