### ISSUE TITLE
Compact Header patch doesn't apply

### ISSUE THREAD

**Issue by iliqiliev** [reisxd/revanced-builder#98]
ReVanced Builder doesn't apply compact-header patch

Download the app, Select YT MUSIC > All patches (I do not select anything to exclude) > Select Newest version (5.16.51 right now) > Wait for it to finish

Here is the log:
`When building ReVanced finishes, please copy these two files and install them:
revanced/revanced.apk
revanced/microg.apk (if you are building YT/YTM)
INFO: Decoding resources 
INFO: Reading dex files 
INFO: Merging .\revanced\app-release-unsigned.apk 
WARNING: Skipping timeline-ads: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.twitter.android 
WARNING: Skipping general-reddit-ads: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.reddit.frontpage 
WARNING: Skipping seekbar-tapping: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping minimized-playback: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping amoled: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping disable-create-button: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-cast-button: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping return-youtube-dislike: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-autoplay-button: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping premium-heading: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping custom-branding: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping disable-fullscreen-panels: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping old-quality-layout: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-shorts-button: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-watermark: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping sponsorblock: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
INFO: Skipping compact-header: Not explicitly included 
INFO: Skipping swipe-controls: Not explicitly included 
INFO: Skipping enable-wide-searchbar: Not explicitly included 
INFO: Skipping force-vp9-codec: Not explicitly included 
INFO: Skipping always-autorepeat: Not explicitly included 
WARNING: Skipping microg-support: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping custom-playback-speed: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping remember-video-quality: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping video-ads: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping general-ads: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
WARNING: Skipping hide-infocard-suggestions: Incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube 
INFO: Skipping enable-debugging: Not explicitly included 
INFO: Skipping hdr-auto-brightness: Not explicitly included 
INFO: minimized-playback-music succeeded 
INFO: tasteBuilder-remover succeeded 
INFO: hide-get-premium succeeded 
INFO: upgrade-button-remover succeeded 
INFO: background-play succeeded 
INFO: music-microg-support succeeded 
INFO: music-video-ads succeeded 
INFO: codecs-unlock succeeded 
INFO: exclusive-audio-playback succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Writing dex file classes.dex 
INFO: Writing dex file classes2.dex 
INFO: Writing dex file classes3.dex 
INFO: Writing dex file classes4.dex 
INFO: Writing resources... 
INFO: Aligning revanced_raw.apk to revanced_aligned.apk 
INFO: Signing revanced_aligned.apk to revanced_signed.apk 
INFO: Copying revanced_signed.apk to revanced.apk 
INFO: Finished 
`

![image](https://user-images.githubusercontent.com/25604760/181471314-0f071cbd-9f13-4480-bca4-01f9dfaa88ff.png)

**revanced-builder Version:** 2.1.1

**Desktop:**

- OS: Windows
- Version: 10 (21H1)

**Comment by reisxd** [comment]
> INFO: Skipping compact-header: Not explicitly included

**Comment by iliqiliev** [comment]
I see that the log shows this, maybe its the problem with the GUI. I wrote above that **I do not select anything to exclude**

**Comment by reisxd** [comment]
> I see that the log shows this, maybe its the problem with the GUI. I wrote above that **I do not select anything to exclude**

Not a problem with the app, the patch is excluded by the patches by default and theres no way to include it back.

**Comment by iliqiliev** [comment]
So as I understand there is no way to apply it with ReVanced Builder
